### ISSUE TITLE
Bug List Hasil Test Productions

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#1027]
### How to Reproduce Bug
**Server:** Productions
**Akses:** Faskes

#### **Actual Result**
Data list hasil test kosong (seharusnya ada)

#### **Expected Result**
Data list hasil test dimunculkan sesuai inputan user

#### **Lampiran**
![image](https://user-images.githubusercontent.com/63390998/119923039-31b95e00-bf9b-11eb-9d72-a5fde014fd38.png)

**Comment by firmanJS** [comment]
apalagi ini :rofl:

**Comment by shintadewiaw** [comment]
@firmanJS ini yang kemaren mau kubuatin card oi wkwkwk tetap tenang 🤣

**Comment by firmanJS** [comment]
Kirain baru lagi, bukanya cuti kamu hari inj sin 🤣

**Comment by shintadewiaw** [comment]
gajadi mas wkwkwk
