### ISSUE TITLE
Backup dan hapus data Draft

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1045]
## Issue
![tempsnip 3](https://user-images.githubusercontent.com/11548871/121462455-d051b000-c9da-11eb-83fa-a547aa49a40a.PNG)
![tempsnip 2](https://user-images.githubusercontent.com/11548871/121462457-d182dd00-c9da-11eb-9efb-c489f6f1f226.PNG)
![tempsnip](https://user-images.githubusercontent.com/11548871/121462459-d21b7380-c9da-11eb-850f-5294f3dfba9a.png)

## Acceptance Criteria
- [ ] Backup data hasil lab pada menu draft berdasarkan village name = none && sub district none
- [ ] Hapus data hasil lab pada menu draft berdasarkan village name = none && sub district none

**Comment by erlangganugraha** [comment]
kang @firmanJS punten untuk prioritaskan ini dulu, hatur nuhun

**Comment by firmanJS** [comment]
> kang @firmanJS punten untuk prioritaskan ini dulu, hatur nuhun

@sandisunandar99 mang sandi pang backupin dulu punten udah di backup nanti aku yan delete

**Comment by sandisunandar99** [comment]
> > kang @firmanJS punten untuk prioritaskan ini dulu, hatur nuhun
> 
> @sandisunandar99 mang sandi pang backupin dulu punten udah di backup nanti aku yan delete

oh okae
