### ISSUE TITLE
Validasi unit id/unit kerja pada setiap akun puskesmas

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1046]
## Acceptance Criteria
- [x] Cek kelengkapan unit id/kerja pada semua akun puskesmas
- [x] Jika sudah lengkap, lampirkan jumlah/count akun puskemas yang sudah ada unit idnya pada komen card ini
- [x] Jika ada belum diupdate unit idnya, lampirkan jumlah/count akun puskesmasnya pada komen card ini

**Comment by firmanJS** [comment]
![Screenshot from 2021-06-10 11-12-46](https://user-images.githubusercontent.com/5679509/121463802-e7919d00-c9dc-11eb-9619-6654e041ff60.png)

faskes yang mempunyai unit id

**Comment by firmanJS** [comment]
![Screenshot from 2021-06-10 11-13-05](https://user-images.githubusercontent.com/5679509/121463828-f6784f80-c9dc-11eb-9306-13cf72ff73db.png)

faskes yang tidak punya unit id

**Comment by erlangganugraha** [comment]
nuhun kang @firmanJS , untuk faskes yang tidak punya unit ID. Minta data akunnya kang

**Comment by erlangganugraha** [comment]
![WhatsApp Image 2021-06-17 at 2 33 01 PM (1)](https://user-images.githubusercontent.com/11548871/122501619-3e235a80-d01f-11eb-8029-2a40a50585a5.jpeg)
Kang @firmanJS minta detail data akunnya yang dihighlight ini. Temen2 MO bingung updatenya

**Comment by firmanJS** [comment]
butuh attribut apa aja fullname atau apa ?

**Comment by erlangganugraha** [comment]
![image](https://user-images.githubusercontent.com/11548871/122505257-2ac7bd80-d026-11eb-9468-aa4b950f24d0.png)

Nama Pengguna, Username, Email, Hak Akses, Nomor Telepon, Unit Kerja, Alamat (Kota, kec, kab, detail)

sesuai yang ada diform ini, sudah cukup kang @firmanJS
