### ISSUE TITLE
Disclaimer caching pada menu laporan harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1067]
## Design
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?page-id=3085%3A0&node-id=3244%3A3&viewport=1769%2C-2328%2C0.8097455501556396&scaling=scale-down-width

## Acceptance Criteria
- [x] Pada disclaimer, terdapat info tanggal update berdasarkan data terbaru diperbaharui
- [x] Pada disclaimer, terdapat intruksi refresh/reload page pada disclaimer

**Comment by shintadewiaw** [comment]
mas @firmanJS nge cachenya berapa lama? ini jam 12.31 kok disclaimernya masih jam 11.33 
![image](https://user-images.githubusercontent.com/63390998/125028112-a1019200-e0b1-11eb-8812-bf33a5cc5a66.png)

**Comment by firmanJS** [comment]
10 menit @shintadewiaw

**Comment by shintadewiaw** [comment]
jamnya masih stuck di 11.33 mas
