### ISSUE TITLE
Disclaimer caching pada menu dashboard lokasi sebaran

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1069]
## Design
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?page-id=3085%3A0&node-id=3873%3A8&viewport=1769%2C-2328%2C0.8097455501556396&scaling=scale-down-width

## Acceptance Criteria
- [x] Terdapat pop up disclaimer ketika membuka page lokasi sebaran
- [x] Pada disclaimer, terdapat info tanggal update berdasarkan data terbaru diperbaharui
- [x] Pada disclaimer, terdapat intruksi refresh/reload page pada disclaimer

**Comment by firmanJS** [comment]
@Arif9878 ada perubahan result json api nya menjadi `{ map:"", date_version:"" }`

**Comment by shintadewiaw** [comment]
mas @firmanJS tanggal updatenya kenapa lama banget ya sampe 1harian?
![image](https://user-images.githubusercontent.com/63390998/124864565-587ba300-dfe3-11eb-84a9-9ff0901750a7.png)

**Comment by firmanJS** [comment]
@shintadewiaw oh iya wait

**Comment by shintadewiaw** [comment]
sama ini mas @firmanJS , setelah button "Mengerti" di klik datanya kosong
![image](https://user-images.githubusercontent.com/63390998/124864762-ad1f1e00-dfe3-11eb-9221-05cb5020a336.png)

**Comment by firmanJS** [comment]
![Screenshot from 2021-07-08 11-58-07](https://user-images.githubusercontent.com/5679509/124864869-d9d33580-dfe3-11eb-822d-8f7175453e31.png)
di aku bener @shintadewiaw

**Comment by firmanJS** [comment]
> sama ini mas @firmanJS , setelah button "Mengerti" di klik datanya kosong
> ![image](https://user-images.githubusercontent.com/63390998/124864762-ad1f1e00-dfe3-11eb-9221-05cb5020a336.png)

coba colek @Arif9878

**Comment by firmanJS** [comment]
response nya berubah mang untuk map jadi data nya ada di object `map` { map:"", date_version:"" }

**Comment by Arif9878** [comment]
@shintadewiaw coba cek di cardnya dan buka link figma

**Comment by shintadewiaw** [comment]
mas @firmanJS coba login ke yang dinkesbogor, tanggal sama jamnya ga sesuai mas

**Comment by firmanJS** [comment]
@shintadewiaw sesuai ah, jam laptop kamu mungkin shin

**Comment by shintadewiaw** [comment]
mas @firmanJS ini tampilan lokasi sebaran pertama kali kok kosong ya?padahal seharusnya ada datanya
![image](https://user-images.githubusercontent.com/63390998/125015414-a9e66980-e099-11eb-90f2-cc66420eb04e.png)



terus aku search di kota bogor juga loading doang mas
![image](https://user-images.githubusercontent.com/63390998/125015414-a9e66980-e099-11eb-90f2-cc66420eb04e.png)

**Comment by firmanJS** [comment]
mang @Arif9878 udah disamakan kah response nya karena response nya dari be berubah jadi gini

````
{
  "status": 200,
  "message": "Success",
  "data": {
    "map": [
        {},
        {},
        {},
    ],
    "date_version": "2021-07-09T02:17:48.234Z"
  }
}
````
