### ISSUE TITLE
[Dashboard] Penyesuaian Perhitungan Jumlah Pada Chart Jenis Kelamin (Backend)

### ISSUE THREAD

**Issue by alifianif** [jabardigitalservice/pikobar-pelaporan-backend#107]
![image](https://user-images.githubusercontent.com/17422311/82040059-22d57580-96d0-11ea-9415-c9f6371bb8e9.png)

- [ ] Penyesuaian perhitungan data seperti pada gambar

**Comment by shintadewiaw** [comment]
mas @firmanJS @rendiriz ini dashboardnya kosong padahal data positif aktifnya ada yaa

![image](https://user-images.githubusercontent.com/63390998/82292479-32f19b80-99d5-11ea-8e94-768c392815ae.png)

![image](https://user-images.githubusercontent.com/63390998/82292568-574d7800-99d5-11ea-8bfd-2953b930c9fb.png)
