### ISSUE TITLE
Menambahkan Unit Kerja Faskes Sukasari Sumedang

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#1086]
### Deskripsi
Unit Kerja pada Faskes Sukasari Cianjur, Purwakarta, dan Sumedang saat ini hanya ada 1 Unit Kerja sehingga data kasus yang inputkan menjadi tercampur.

### Acceptance Criteria
- [x] Membuat Unit Kerja sukasaricianjur
- [x] Membuat Unit Kerja sukasaripurwakarta
- [ ] Membuat Unit Kerja sukasarisumedang

**Comment by sandisunandar99** [comment]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/6767399/125391755-36ad6200-e3cf-11eb-91b1-a5c0cd358f2f.png">

**Comment by shintadewiaw** [comment]
ke prod langsung aja mas @sandisunandar99

**Comment by sandisunandar99** [comment]
> ke prod langsung aja mas @sandisunandar99 

Saya real men sin.. langsung di prod 🤣

**Comment by shintadewiaw** [comment]
masih nyampur ni di prodnya gan @sandisunandar99 
![image](https://user-images.githubusercontent.com/63390998/125394086-5181d580-e3d3-11eb-8784-682f556f9d89.png)

**Comment by sandisunandar99** [comment]
> masih nyampur ni di prodnya gan @sandisunandar99
> ![image](https://user-images.githubusercontent.com/63390998/125394086-5181d580-e3d3-11eb-8784-682f556f9d89.png)

yampur gmana ini teh mksd nya sin ??

**Comment by shintadewiaw** [comment]
harusnya si sukasari sumedang kan udah pake unit kerja yang baru kan mas, nah ini masih nyampur sama sukasari cianjur mas (fyi, sukasari cianjur namanya diubah jadi cilaku) @sandisunandar99

**Comment by sandisunandar99** [comment]
> harusnya si sukasari sumedang kan udah pake unit kerja yang baru kan mas, nah ini masih nyampur sama sukasari cianjur mas (fyi, sukasari cianjur namanya diubah jadi cilaku) @sandisunandar99

OH....okay @shintadewiaw sudah aku ubah nya,,cecek
