### ISSUE TITLE
Fixing issue fitur export data

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1102]
## Acceptance Criteria
- [x] Download file dibuat link pada isi surat email
- [x] Link expired selama 2 jam
- [x] Tambahkan disclaimer dibawa link download : "Link berikut hanya dapat diakses selama 2 jam. Silahkan resend email pada halaman History Export ketika link Expired"

**Comment by erlangganugraha** [comment]
@shintadewiaw review redaksi disclaimernya, takutnya penyusunan kalimat aku kurang bagus wkwk

**Comment by shintadewiaw** [comment]
mas @firmanJS kalau linknya diganti button gitu bisa ga mas?kaya "Klik Disini" misal wkwk panjang banget mas
![image](https://user-images.githubusercontent.com/63390998/126743519-04b00a32-60b5-467c-9006-a783ac031f9a.png)

**Comment by shintadewiaw** [comment]
mas mas kalo expired bisa di handle ga ya biar ga keluar error teknis gini? @firmanJS 
![image](https://user-images.githubusercontent.com/63390998/126766065-1e4a4462-6c04-468a-8820-1af7a17899d8.png)

**Comment by firmanJS** [comment]
> mas mas kalo expired bisa di handle ga ya biar ga keluar error teknis gini? @firmanJS
> ![image](https://user-images.githubusercontent.com/63390998/126766065-1e4a4462-6c04-468a-8820-1af7a17899d8.png)

itu dari aws nya @shintadewiaw ada pesan expired kan mudah2an user ngerti hehehe, sepertinya sulit untuk di custom

**Comment by shintadewiaw** [comment]
@erlangganugraha 
![image](https://user-images.githubusercontent.com/63390998/126928804-500f07d2-70fc-4e19-b10a-abcc20085b3f.png)

**Comment by erlangganugraha** [comment]
![Group 1589](https://user-images.githubusercontent.com/11548871/127095754-5d9ed8e4-fafa-4394-bb59-5f5adf3d80c4.png)

Button css style :
/* Auto Layout */

display: flex;
flex-direction: row;
align-items: center;
padding: 12px 24px;

position: absolute;
width: 140px;
height: 38px;

/* Green 2 */

background: #27AE60;
border-radius: 8px;

**Comment by erlangganugraha** [comment]
desain konten udah jadi guys @firmanJS @shintadewiaw
