### ISSUE TITLE
Optimasi Service Pada Backend

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1113]
## Acceptance Criteria
- [x] Memindahkan service export pada server terpisah
- [x] Memindahkan service dashboard pada server terpisah

**Comment by firmanJS** [comment]
sundul @shintadewiaw

**Comment by shintadewiaw** [comment]
yuhuu masih di tes gan @firmanJS

**Comment by shintadewiaw** [comment]
mas @firmanJS yang informasi klinis ngirim ke emailnya sampai 2x mas
![image](https://user-images.githubusercontent.com/63390998/128296297-403cd54e-b089-4e67-b14e-7c4f0732cec1.png)

**Comment by firmanJS** [comment]
coba cek lagi

**Comment by shintadewiaw** [comment]
mas masih dobeeel @firmanJS

**Comment by firmanJS** [comment]
coba kirim ke email lain dan coba hapus email2 yang masuk nya

**Comment by shintadewiaw** [comment]
udah aku hapus email lainnya, yaudah kucoba sekali lagi @firmanJS

**Comment by shintadewiaw** [comment]
mas aku udah kirim ke email baru masih double huhu jedanya 1 jam sekarang @firmanJS 
![image](https://user-images.githubusercontent.com/63390998/128463579-af6e26ce-8883-42f4-98c8-4de684edd1f3.png)

**Comment by firmanJS** [comment]
Isi file nya sama ga ? @shintadewiaw

**Comment by shintadewiaw** [comment]
samaa @firmanJS

**Comment by erlangganugraha** [comment]
![image](https://user-images.githubusercontent.com/11548871/128467716-3740d47d-ef94-4045-8507-31500a9b95d2.png)
dikirim ke email saya juga jadi double ternyata
cc @firmanJS @shintadewiaw
