### ISSUE TITLE
Improvement Fitur Import Registrasi Rujukan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1124]
## Desain/Prototype
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?page-id=363%3A0&node-id=1810%3A47&viewport=313%2C48%2C0.48&scaling=min-zoom&starting-point-node-id=1810%3A47&show-proto-sidebar=1

### Interface Form import 
- [x] Terdapat contoh template yang bisa didownload
- [x] Terdapat tab cara penggunaan
- [x] Terdapat tab Syarat & Ketentuan

### Validasi/Ketentuan
- [x] Maximal rows yang diimport <=200
- [x] Error ditampilkan dalam bentuk table ketika tahap review
- [x] Apabila ada kolom mandatory isiannya kosong, maka data yang diimportkan error

### Template Import
https://drive.google.com/drive/folders/1isw-TM20k2xcVfQ9ehLrwHgVeu8bg2DR?usp=sharing

### Syarat & Ketentuan
Setiap data wajib memiliki NIK
Jumlah maksimum data dalam sekali import adalah 200 baris

**Comment by erlangganugraha** [comment]
@sandisunandar99  desain prototype udah jadi, udah dilampirin didesc cardnya mang

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 aku cobain import kok keluar error ini ya?kira kira kenapa tu mas? 

![image](https://user-images.githubusercontent.com/63390998/145179229-46a4795e-16be-4926-b076-72d2250322fc.png)
![image](https://user-images.githubusercontent.com/63390998/145179625-51f9dfda-80ae-461f-be60-ede1146274a0.png)


format import yang dipakai (punya mas sandi yang udah di upload di gdrive)
https://drive.google.com/drive/folders/1isw-TM20k2xcVfQ9ehLrwHgVeu8bg2DR

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 aku import dengan mengosongkan beberapa field required terus error 500, belum di handle kah mas untuk validasi kolom yang requirednya?

![image](https://user-images.githubusercontent.com/63390998/145195465-2672a50c-9178-41b6-9d67-0999193bd9b0.png)
![image](https://user-images.githubusercontent.com/63390998/145195348-1cde070c-59d6-42ee-a270-c341ea01867e.png)
![image](https://user-images.githubusercontent.com/63390998/145195379-a543f19a-9c7a-4398-8841-a6c4eac4f900.png)

**Comment by sandisunandar99** [comment]
@shintadewiaw di coba lagi ya

**Comment by shintadewiaw** [comment]
@sandisunandar99 mengubah flow validasi, perlu melakukan validasi >200 data terlebih dahulu kemudian validasi data per row

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 ini emang errornya begini?
![image](https://user-images.githubusercontent.com/63390998/145551521-caeab3e5-addf-4657-a4a6-b867bd075d20.png)
