### ISSUE TITLE
Improvement Form Input Registrasi Rujukan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1126]
## Acceptance Criteria
- [x] Field kriteria diganti menjadi **Tujuan Pemeriksaan**
- [x] Add field **Detail Pemeriksaan** setelah field Tujuan Pemeriksaan
- [x] Field **Detail Pemeriksaan** diset mandatory

### Pengkondisian List Pilihan Detail Pemeriksaan
- [x] Jika Tujuan Pemeriksaan memilih Suspect, maka list pilihan Detail Pemeriksaan : Entry Test, Exit Test
- [x] Jika Tujuan Pemeriksaan memilih Kontak Erat, maka list pilihan Detail Pemeriksaan : Entry Test, Exit Test
- [x] Jika Tujuan Pemeriksaan memilih Screening, maka list pilihan Detail Pemeriksaan : Pelaku Perjalanan, Alasan Medis, Alasan Lainnya, Pembelajaran Tatap Muka
- [x] Jika Tujuan Pemeriksaan memilih Follow Up, maka list pilihan Detail Pemeriksaan : Pelaku Perjalanan, Alasan Medis, Alasan Lainnya, Pembelajaran Tatap Muka

### Perubahan Master Data Kode Pemeriksaan
Tujuan Pemeriksaan
1 = Suspect
2 = Kontak Erat
3 = Screening
4 = Follow Up

Detail Pemeriksaan
1 = Pelaku Perjalanan
2 = Alasan Medis
3 = Alasan Lainnya
4 = Pembelajaran Tatap Muka
5 = Tidak Ada
8 = Entry Test
9 = Exit Test

**Comment by maruf12** [comment]
@erlangganugraha Untuk tujuan pemeriksaan sudah ada data di existing yaitu kriteria. tapi idnya berbeda. Nah ini perlu diskusi lebih lanjut.

**Comment by erlangganugraha** [comment]
> @erlangganugraha Untuk tujuan pemeriksaan sudah ada data di existing yaitu kriteria. tapi idnya berbeda. Nah ini perlu diskusi lebih lanjut. kemudian untuk status yang tidak didefinisikan apakah akan dibikin value default. kalau default, pakai nilai yang mana.

kalo status yang tidak didefinisikan itu yang mana mang ? @maaruf12

**Comment by erlangganugraha** [comment]
> @erlangganugraha Untuk tujuan pemeriksaan sudah ada data di existing yaitu kriteria. tapi idnya berbeda. Nah ini perlu diskusi lebih lanjut. kemudian untuk status yang tidak didefinisikan apakah akan dibikin value default. kalau default, pakai nilai yang mana.

iya mang data-data dgn kode lama nanti perlu diconvert datanya ke kode baru @maruf12

**Comment by erlangganugraha** [comment]
btw @maruf12  ada penambahan kode detail pemeriksaan, yaitu : 5 = Tidak Ada
udah ditambahkan di desc mang

**Comment by sandisunandar99** [comment]
boleh ga ini di detilkan terutama yang kode di tujuan pemeriksaan. kode yang sebelum(existing)  dan kode sekarng yg berubah.
contoh : 
misal kontak erat, kan sekarng jadi angka 2 dan di data yang dulu angka nya 5 terakhir diskusi berang @maruf12 kamarin. nah ini supaya kita ga nerka2 dan jadi bingung juga di tulis aja di card nya. 

cc : @erlangganugraha @maruf12 @shintadewiaw
