### ISSUE TITLE
Improvement List Data Registrasi Mandiri

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1128]
## Acceptance Criteria
- [x] Kolom kriteria diganti menjadi Tujuan Pemeriksaan

**Comment by maruf12** [comment]
@erlangganugraha Untuk tujuan pemeriksaan sudah ada data di existing yaitu kriteria. tapi idnya berbeda. Nah ini perlu diskusi lebih lanjut. Karena jika diupdate maka data yang lama akan berubah nilai statusnya.
kemudian untuk status yang tidak didefinisikan apakah akan dibikin value default. kalau default, pakai nilai yang mana.

Ini related sama task yang ini #1126
