### ISSUE TITLE
Improvement Fitur Import Registrasi Mandiri

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1131]
## Desain/Prototype
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?page-id=363%3A0&node-id=2483%3A5762&viewport=313%2C48%2C0.48&scaling=scale-down-width&starting-point-node-id=2483%3A5762&show-proto-sidebar=1

### Interface Form import 
- [x] Form import tidak dibuat pop up, samakan dengan desain prototype
- [x] Proses import yang diawali pilih file sampai import berhasil, flownya disamakan dengan import di **Registrasi Rujukan**
- [x] Terdapat contoh template yang bisa didownload
- [x] Terdapat content Syarat Penggunaan

### Validasi/Ketentuan
- [x] Maximal rows yang diimport <=200
- [x] Error ditampilkan dalam bentuk table ketika tahap review
- [x] Apabila ada kolom mandatory isiannya kosong, maka data yang diimportkan error

### Template Import
https://drive.google.com/drive/folders/1isw-TM20k2xcVfQ9ehLrwHgVeu8bg2DR?usp=sharing

### Syarat & Ketentuan
Setiap data wajib memiliki NIK
Jumlah maksimum data dalam sekali import adalah 200 baris

**Comment by erlangganugraha** [comment]
@sandisunandar99  desain prototype udah jadi, udah dilampirin didesc cardnya kang

**Comment by shintadewiaw** [comment]
**Feedback & Issue 13/12/2021**

1. Ketika import (masih dalam keadaan preview di FE) tetapi data sudah masuk ke dalam list

2. Ketika import data (positif case) di list Nama Lengkap, Status, Sumber Pasien null

3. Kolom jenis kelamin belum tervalidasi 

4. Ketika kab/kota kosong error SQL state
![image](https://user-images.githubusercontent.com/63390998/145801393-5d2ff384-e3e0-44ce-b26b-4d1c81751c08.png)

**Comment by sandisunandar99** [comment]
Oke @shintadewiaw nuhun
