### ISSUE TITLE
Page Daftar Sample WGS

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1135]
## Protoype Page Daftar Sample WGS
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?node-id=2269%3A750&scaling=scale-down&page-id=2160%3A351&starting-point-node-id=2251%3A14579

## Acceptance Criteria
- [x] Terdapat fungsi untuk memfilter data berdasarkan Nomor Sample, Tanggal Swab, dan Instansi Pengirim
- [x] Terdapat button import data dari SIM Lab (Import Pikobar) untuk direct ke page Form Import Pikobar
- [x]  Terdapat Reset Filter (Clear Filter)
- [x] Terdapat button Import Excel untuk direct ke form Import Excel
- [x] Terdapat list daftar sample pasien, order by Tanggal Input DESC
- [x] Terdapat button untuk direct ke page Detail Data

**Comment by firmanJS** [comment]
@maruf12 GET /api/v1/kriteria-wgs?page=1&perpage=20&order=&order_direction=

**Comment by shintadewiaw** [comment]
link preview: https://deploy-preview-779--staging-pikobar-lab.netlify.app/wgs/index

![image](https://user-images.githubusercontent.com/9880869/148158469-0600af88-5638-44b5-9b8f-22a3a9e66243.png)
filter fasyankes dibikin kyk di gambar aja. namenya `fasyankes` terus valuenya `id` nya aja jangan name. Ini biar seragam sama list yang lain. Saat ini kalo dikirim filter kyk gitu masih belum jalan soalnya.

@sandisunandar99

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 yang di list ini jadinya diganti kriteria, di responsnya minta tolong sesuain ya mas (saat ini masih kategori)
![image](https://user-images.githubusercontent.com/63390998/150464726-010aa23e-349e-40b8-b550-c16463d3f501.png)

**Comment by sandisunandar99** [comment]
> mas @sandisunandar99 yang di list ini jadinya diganti kriteria, di responsnya minta tolong sesuain ya mas (saat ini masih kategori)
> ![image](https://user-images.githubusercontent.com/63390998/150464726-010aa23e-349e-40b8-b550-c16463d3f501.png)
> 

Ini udah sin.. coba cek di response di inspec.. kalo ga salah di FE nya hrus bhasa indo.. wkwk kmrin udh d obrolin ke @maruf12 .. cc : @shintadewiaw

**Comment by shintadewiaw** [comment]
ini responsnya mas, ga ada kriteria @sandisunandar99 
![image](https://user-images.githubusercontent.com/63390998/150479619-b460836a-afe6-4703-bb42-ef2bdfc36f20.png)

**Comment by maruf12** [comment]
@sandisunandar99 datanya diubah kang, yang kemaren kan `kategori`. Nah bisnis proses yang baru, harusnya nampilinnya `kriteria` bukan `kategori`. Data `kriteria` diambil dari endpoint yang `POST` /kriteria-wgs. 
Sorry2 ini kmaren lupa nulis disini perubahan terbarunya.
cc @shintadewiaw

**Comment by sandisunandar99** [comment]
wkwk siap @maruf12 @shintadewiaw sya cek dlu,,

**Comment by sandisunandar99** [comment]
![Uploading Screen Shot 2022-01-24 at 11.45.35.png…]()
@shintadewiaw @maruf12
