### ISSUE TITLE
Page Detail Sample

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1136]
## Prototype Page Detail Daftar Sample
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?node-id=2269%3A750&scaling=scale-down&page-id=2160%3A351&starting-point-node-id=2251%3A14579

## Acceptance Criteria
- [ ] Terdapat informasi data daftar sample secara detail, dengan 2 sub group :
   - [ ] 1. Detail Informasi Sample
   - [ ] 2. Detail Kriteria WGS
- [ ] Terdapat button Perbarui Data untuk direct ke Page Edit Daftar Sample WGS
- [ ] kode_sampel di rename menjadi kode_sampel_wgs

**Comment by firmanJS** [comment]
@maruf12 /api/v1/kriteria-wgs?page=1&perpage=20&order=created_at&order_direction=asc

**Comment by shintadewiaw** [comment]
Kode Sampel: Kode sampel wgs (ketika sudah terdaftar sebagai kode sampel wgs) generate otomatis --> di Backend kode_sampel di rename menjadi kode_sampel_wgs @sandisunandar99
Nomor Sampel: Bawaan dari kode sampel yang registrasi
