### ISSUE TITLE
Menambahkan Kodefikasi Kode Sampel W

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#1145]
## User Storie
User labkes membutuhkan klasifikasi sampel dari pasien yang terkena HIV untuk membedakan dengan sample yang lain

## Detail Request
- [x] Menambahkan kode sample W pada Menu Registrasi Mandiri SIM Lab
- [x] Menambahkan kode sample W pada Pendaftaran

**Comment by shintadewiaw** [comment]
perlu info ke mas novan er @erlangganugraha 
cc:  @rachadiannovansyah

**Comment by shintadewiaw** [comment]
perlu info ke mas novan er, eh apa udah di handle mas sandi? @erlangganugraha
cc: @sandisunandar99 @rachadiannovansyah

**Comment by erlangganugraha** [comment]
info terkait apa ke novan shin @shintadewiaw ?

**Comment by shintadewiaw** [comment]
maksudnya dia kan BE pendaftaran yang dulu, berarti yang ngerjain mas sandi ya? @erlangganugraha

**Comment by erlangganugraha** [comment]
yes betul kang sandi @shintadewiaw
