### ISSUE TITLE
[Dashboard] Filter pie chart jenis kelamin

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#117]
## Desain
Desain seperti :
![Screenshot_2020-05-19 Pikobar - Pusat Informasi dan Koordinasi COVID-19 Jawa Barat](https://user-images.githubusercontent.com/11548871/82246512-06a33400-996f-11ea-89bd-6f451bf89fa5.png)

## Acceptance Criteria
Pilihan filter :

- [x] 1. Semua Status
- [x] 2. Positif Covid-19
- [x] 3. Positif - Aktif
- [x] 4. Positif - Sembuh
- [x] 5. Positif - Meninggal
- [x] 6. ODP - Proses
- [x] 7. ODP - Selesai
- [x] 8. PDP - Proses
- [x] 9. PDP - Selesai
- [x] 10. OTG - Proses
- [x] 11. OTG - Selesai

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by firmanJS** [comment]
@erlangganugraha @alifianif status `Positif Covid-19` kondisinya status pasien yang kena covid baik itu sembuh, meninggal dan positif aktif kah atau gimana ?

**Comment by rendiriz** [comment]
![Screen Shot 2020-05-21 at 18 40 22](https://user-images.githubusercontent.com/16224915/82555770-983ebb80-9b92-11ea-89ef-df9ba8c573d6.png)

**Comment by firmanJS** [comment]
@rendiriz done mang bug na

**Comment by shintadewiaw** [comment]
mas @rendiriz @firmanJS ada beberapa issue
1. Untuk yang perhitungan **ODP - Proses** tadi coba aku hitung manual per pagenya, totalnya 128 kasus, tapi di chartnya kalau di total cuma 153

![image](https://user-images.githubusercontent.com/63390998/82879432-21753a00-9f67-11ea-93ab-37ea3483f448.png)

2. Untuk perhitungan **Positif - Aktif** (Perempuan) Tidak sesuai
![image](https://user-images.githubusercontent.com/63390998/82880880-3226af80-9f69-11ea-9c6d-1c36a1c35fe5.png)

![image](https://user-images.githubusercontent.com/63390998/82880960-45d21600-9f69-11ea-9275-db9bb5802f0f.png)


sama mau tanya kalau Positif Covid-19 itu keseluruhan atau gimana er? @erlangganugraha

**Comment by rendiriz** [comment]
cc: @firmanJS 
kunaon nya mang?

1.
![Screen Shot 2020-05-26 at 16 06 23](https://user-images.githubusercontent.com/16224915/82882806-c85bd500-9f6b-11ea-83d9-92636e8299e2.png)

2.
![Screen Shot 2020-05-26 at 16 14 07](https://user-images.githubusercontent.com/16224915/82883250-63ed4580-9f6c-11ea-8311-94742c9688af.png)
![Screen Shot 2020-05-26 at 16 17 10](https://user-images.githubusercontent.com/16224915/82883272-694a9000-9f6c-11ea-929b-9f3991410b66.png)

**Comment by firmanJS** [comment]
@rendiriz ok di cek hela

**Comment by firmanJS** [comment]
@shintadewiaw itu ngitung 128 jumlah laki-laki dan perempuan nya ?

**Comment by firmanJS** [comment]
@shintadewiaw itu karena hasilnya - berarti terhitung nya masih positif aktif

**Comment by shintadewiaw** [comment]
> @shintadewiaw itu ngitung 128 jumlah laki-laki dan perempuan nya ?

Iya betul mas jumlah keseluruhan kasus ODP yang statusnya proses

**Comment by shintadewiaw** [comment]
> @shintadewiaw itu karena hasilnya - berarti terhitung nya masih positif aktif 

Oh maksutnya statusnya Selesai tapi hasilnya (-) dianggapnya positif aktif ya mas?

**Comment by firmanJS** [comment]
@shintadewiaw iya begitu rumus nya

**Comment by firmanJS** [comment]
@shintadewiaw yang odp proses bener juga aaku cek itu bedanya gimana ?

**Comment by shintadewiaw** [comment]
> @shintadewiaw yang odp proses bener juga aaku cek itu bedanya gimana ?

Aku hitung manual dari list kasus, terus di cocokin total yang ada di dashboard, coba cek pake query di list kasus mas, sama tidak?bisi aku yang kurang teliti

**Comment by firmanJS** [comment]
@shintadewiaw udah bener aku cek antara list sama dashboard kalo bisa di videoin dong biar ga salah persepsi wkwk

**Comment by shintadewiaw** [comment]
> @shintadewiaw udah bener aku cek antara list sama dashboard kalo bisa di videoin dong biar ga salah persepsi wkwk 

Ok barusan aku cek lagi udah bener, besok lagi ku videoin deh sumpah aku ampe 3 kali cek hasilnya beda😭

**Comment by firmanJS** [comment]
@shintadewiaw tetap tenang kopi dulu wwkwk

**Comment by shintadewiaw** [comment]
mas @firmanJS kalo yang Positif Covid-19 ngitungnya keseluruhan atau gimana?

**Comment by firmanJS** [comment]
@shintadewiaw keseluruhan positif

**Comment by shintadewiaw** [comment]
@firmanJS ini yang Positif Covid-19 kalo berdasarkan total keseluruhan positif datanya ga sesuai

![image](https://user-images.githubusercontent.com/63390998/82974580-8337b180-a004-11ea-9150-803971f46168.png)

![image](https://user-images.githubusercontent.com/63390998/82974781-fb05dc00-a004-11ea-8d8f-38bf48a8426a.png)

**Comment by rendiriz** [comment]
@shintadewiaw sudah dibenerin ya yg positif - covid-19, dicek lagi
