### ISSUE TITLE
[Laporan Harian] API Laporan Harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#119]
## Desain
<img width="839" alt="81374556-b8e62a80-9129-11ea-934f-ca0d97c7a366" src="https://user-images.githubusercontent.com/11548871/82247216-3868ca80-9970-11ea-894c-eaaaf2734db3.png">

## Acceptance Criteria

- [x] Buat seperti mockup/desain
- [x] Tambahkan side bar menu "Laporan Harian"
- [x] Title form : "Rekap Kasus [Nama Dinkes] 19 Mei 2020 - 13:00 WIB
- [x] Terdapat filter berdasarkan tanggal input
- [x] Bisa reset filter

### Roles Dinkes Kota/Kab

> **Tabel berisi list kecamatan dengan isian kolom sbb** :

- [x] 1. OTG Proses
- [x] 2. OTG Selesai
- [x] 3. ODP Proses
- [x] 4. ODP Selesai
- [x] 5. PDP Proses
- [x] 6. PDP Selesai
- [x] 7. Positif Aktif
- [x] 8. Positif Sembuh
- [x] 9. Positif Meninggal

 ### Roles Dinkes Provinsi
> **Tabel berisi list Kota/Kabupaten dengan isian kolom sbb :**

- [x] 1. OTG Proses
- [x] 2. OTG Selesai
- [x] 3. ODP Proses
- [x] 4. ODP Selesai
- [x] 5. PDP Proses
- [x] 6. PDP Selesai
- [x] 7. Positif Aktif
- [x] 8. Positif Sembuh
- [x] 9. Positif Meninggal

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by alifianif** [comment]
1. Saya nambahin dua data positif proses hari ini, tanggal 27 Mei 2020 pada pukul 12.37 seperti di bawah, tapi di halaman laporan harian kosong. Padahal di excelnya

- ![image](https://user-images.githubusercontent.com/17422311/82981820-0bbf4d80-a017-11ea-8cfe-1c2c8178ac5d.png)

- ![image](https://user-images.githubusercontent.com/17422311/82981867-21347780-a017-11ea-8699-baac1ad5d952.png)

2. Kalau di excel, setiap kali menambah data pasien positif dengan tahapan proses, ditambahkannya ke kolom positif aktif, tapi di halaman Laporan Harian adanya kolom Positif Proses, dimana kalau di excel kolom Positif Proses isinya kosong. Mungkin itulah mengapa angkanya tidak bertambah. Jadi sepertinya perlu diseragamkan lagi apakah kolom yang dipakai adalah Positif Aktif atau Positif Proses? @erlangganugraha 

- ![image](https://user-images.githubusercontent.com/17422311/82982553-a8361f80-a018-11ea-9c25-24f36f480231.png)

- ![image](https://user-images.githubusercontent.com/17422311/82982622-c56aee00-a018-11ea-8c31-5f46a32fb2d3.png)

3. Nama kota/kab tidak muncul, tapi di export excelnya muncul:
![image](https://user-images.githubusercontent.com/17422311/82982064-8d16e000-a017-11ea-9f70-46ea29bc1683.png)
