### ISSUE TITLE
[Laporan Harian] API Export Laporan Harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#120]
## User Story
Sebagai dinkes kota/kab/provinsi saya ingin mengexport laporan harian sebagai laporan harian kepada dinkes provinsi

> <img width="839" alt="81374556-b8e62a80-9129-11ea-934f-ca0d97c7a366" src="https://user-images.githubusercontent.com/11548871/82247216-3868ca80-9970-11ea-894c-eaaaf2734db3.png">

## Acceptance Criteria :
* [x] Dinkes provinsi bisa export data
* [x] Dinkes kota/kab bisa export data
* [x] Export data to jpg/png/pdf
* [x] Export data to excel berformat .xlsx
* [x] Jika data yang di filter/sorting maka data yang diexport sesuai hasil filter

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by firmanJS** [comment]
@Arif9878 ini di kerjain mang sandi ya yang request tadi

**Comment by shintadewiaw** [comment]
ini kabupaten/kota redaksinya diganti Kecamatan ya guys, excel dan FE nya

- [ ] ![image](https://user-images.githubusercontent.com/63390998/83378641-874c4080-a403-11ea-80e1-1844e963df71.png)  

- [ ] ![image](https://user-images.githubusercontent.com/63390998/83378708-bb276600-a403-11ea-9712-6739516a9bba.png)


@Arif9878 & @sandisunandar99

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 redaksi excelnya belum diubah yaa
1. Jika login sebagai dinkeskabkota: Kecamatan
2. Jika login sebagai staffprov: Kabupaten/Kota

![image](https://user-images.githubusercontent.com/63390998/83852720-6c006e80-a73e-11ea-949e-4ec9037189a4.png)
