### ISSUE TITLE
[Laporan Kasus] Export to Formulir PE (backend)

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#123]
## Form Lampiran 6
![Screenshot_2020-05-19 REV-04_Pedoman_P2_COVID-19_ 27 Maret2020_Tanpa TTD pdf pdf](https://user-images.githubusercontent.com/11548871/82249456-fc376900-9973-11ea-96bc-4e210a058e6e.png)
![Screenshot_2020-05-19 REV-04_Pedoman_P2_COVID-19_ 27 Maret2020_Tanpa TTD pdf pdf(1)](https://user-images.githubusercontent.com/11548871/82249455-fb063c00-9973-11ea-987f-6b9290bf6e8e.png)
![Screenshot_2020-05-19 REV-04_Pedoman_P2_COVID-19_ 27 Maret2020_Tanpa TTD pdf pdf(2)](https://user-images.githubusercontent.com/11548871/82249451-f9d50f00-9973-11ea-8fff-ca543b99f60f.png)

## Acceptance Criteria

- [ ] Export menjadi formulir PE dalam bentuk PDF

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by khihadysucahyo** [comment]
API `{host}/api/cases/{caseId}/export-to-pe-form`

**Comment by shintadewiaw** [comment]
1. Tanggal Lahir Invalid Date, lebih baik jika kosong (-)

2. Umur 23 Tahun, 0 Bulan atau Umur 23 Tahun, - Bulan

![image](https://user-images.githubusercontent.com/63390998/83377671-87970c80-a400-11ea-898e-609dfe705096.png)

3. Saat menambahkan kasus kondisi penyerta di ceklist semua, tetapi di PDF ada yang tidak masuk datanya, data informasi juga disesuaikan

Tambah Kasus
![image](https://user-images.githubusercontent.com/63390998/83377824-07bd7200-a401-11ea-8eb3-5c0b5b43fe3c.png)

PDF
![image](https://user-images.githubusercontent.com/63390998/83377963-6e429000-a401-11ea-8bbd-b9b9188c6206.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw yang ceklistnya ga sesuai data yang mana ya? nanrti saya cekkan, barusan ngecek dan nyoba bikin baru udah sesuai soalnya.

**Comment by shintadewiaw** [comment]
mas @khihadysucahyo , saya update kasus dari OTG jadi positif - sembuh tapi di PDF nya ga ke ceklist

![image](https://user-images.githubusercontent.com/63390998/83737169-d7820780-a67c-11ea-9375-3371647cf976.png)

![image](https://user-images.githubusercontent.com/63390998/83737081-bf11ed00-a67c-11ea-9e28-339f5ce8d195.png)
