### ISSUE TITLE
[Laporan Harian] Penambahan kolom baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#125]
![Screenshot_2020-05-19 4 UPDATE LAPORAN HARIAN 15-5-20(1) pdf](https://user-images.githubusercontent.com/11548871/82253435-2c363a80-997b-11ea-87eb-be160bfc3d53.png)

## Acceptance Criteria :

- [x] Total WNI
- [x] Total WNA
- [x] Total laki-laki disetiap status
- [x] Total perempuan disetiap status
- [x] Total usia disetiap status

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by Arif9878** [comment]
@sandisunandar99 Total WNA/Total WNI belum ada yang per status otg, odp, pdp atau positif mang

**Comment by sandisunandar99** [comment]
Oh acan mang.@Arif9878 . kan desain na anyar eta ..

**Comment by sandisunandar99** [comment]
@shintadewiaw ini kenapa kembali lagi ke revisi ya?
