### ISSUE TITLE
[Pelaporan Kasus] Penambahan Bulan pada Kolom Umur

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#158]
## Design
![image](https://user-images.githubusercontent.com/63390998/83996879-53cf6000-a987-11ea-8626-4f69670cecf4.png)

## Acceptance Criteria
- [ ] Menambahkan Kolom Tahun & Bulan pada Usia
- [ ] Kolom Tahun & Bulan dibuat mandatory

### Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by sandisunandar99** [comment]
@shintadewiaw ini gmna mksd nya ya?? ga ada gambarannya gitu ,,, wkwkwk

**Comment by shintadewiaw** [comment]
sudah ditambahkan ya mas @sandisunandar99

**Comment by sandisunandar99** [comment]
@shintadewiaw @alifianif untuk penambahan bulan pada umur itu di convert ke desimal ya,,
misal contoh:
*) 1 tahun 6 bulan jadi 1,5 tahun
*) 5 tahun 1 bulan jadi 5,08 tahun
itu masuk ke data backend nya
ini kenapa jadi kya gini,, unutk mempermudah perhitungan di dashboard.. soalnya ada keterkaitan kesana nya

cara hitungan nya,, age = bulan /12

**Comment by shintadewiaw** [comment]
@sandisunandar99 mas yang ditampilin di list yang di kolom tahun aja

![image](https://user-images.githubusercontent.com/63390998/84102241-1546ad80-aa3a-11ea-80f0-71bab5d9af2b.png)

**Comment by shintadewiaw** [comment]
masih belum ada perubahan mas, terus misalkan saya input tahun 0 bulan 5 kenapa konversinya 0,41 ya?bukan 0,5?

![image](https://user-images.githubusercontent.com/63390998/84223536-5efbca80-ab04-11ea-9db6-feb4ace11751.png)

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/84245726-b2cfd900-ab2f-11ea-9fb5-4761296de8d9.png)


belum ada perubahan ya guys @naufalihsank @sandisunandar99

**Comment by shintadewiaw** [comment]
mas @naufalihsank  ini januari kok kehitungnya 5 bulan ya?
![image](https://user-images.githubusercontent.com/63390998/84252087-5cb36380-ab38-11ea-86de-3fd8f7f223e0.png)
