### ISSUE TITLE
[Tambah Kasus] Bug Validasi NIK

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#160]
### **How to Reproduce Bug:**
1. Tambah Kasus dengan Memasukkan NIK random
2. Tekan tombol Lanjutkan
3. Tidak ada respon dari sistem (setelah di cek teryata ada validasi NIK dari BE yang tidak di tampilkan pada FE)

### **Role**
- Dinkes Kab/Kota
- Faskes

![image](https://user-images.githubusercontent.com/63390998/83376691-5ec14800-a3fd-11ea-8491-8f8212abb537.png)

**Comment by sandisunandar99** [comment]
@shintadewiaw ini udah ga ada papa, aku coba barusan pake nik dan ga pake nik input casus nya,, coba di cek lagi aja ya,,,

**Comment by shintadewiaw** [comment]
masih belum bisa kalo pake nik random mas @sandisunandar99 
![image](https://user-images.githubusercontent.com/63390998/83987979-15787780-a96c-11ea-8004-36d305362947.png)

**Comment by sandisunandar99** [comment]
@shintadewiaw nik nya 16 angka coba .. kan standarnya jga gitu ,,

**Comment by shintadewiaw** [comment]
mas @naufalihsank minta tolong validasiin di FEnya dong mas kalau tidak sesuai kode provinsi dan 16 angka

**Comment by naufalihsank** [comment]
buat yang ini validasi di FE nya udah bisa, cuma paling beberapa field di form ini pas belum sesuai isinya, pesan errornya ga muncul Masih di cek bareng kang arif juga terkait kenapa ga muncul si pesannya
