### ISSUE TITLE
[Rujukan] Create Kasus Rujukan Baru (yang belum terdata)

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#166]
### Form Buat Rujukan
![Buat Rujukan](https://user-images.githubusercontent.com/63390998/84238459-494acd00-ab25-11ea-8df0-eedd5e08cead.png)

### Form Buat Rujukan Pasien Tidak Terdata
![Popup Buat Rujukan Pasien Tidak Terdata](https://user-images.githubusercontent.com/63390998/84237182-17d10200-ab23-11ea-9fcf-64b074b80c8a.png)

**NOTES**
Pasien belum terdata dan langsung dirujuk ke RS —> verifikasi ke dinkes dilakukan oleh RS setelah data di transfer ke RS

### Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by khihadysucahyo** [comment]
### API
`POST: {{host}}/api/cases-transfer`
Request payload: Sama seperti Create Kasus,hanya ditambahkan berikut:
```
{
    ...CreateCasePayload,
   "transfer_to_unit_id": "5ee30cd5e2265a001111848d",
   "transfer_to_unit_name": "RSU Dr Hasan Sadikin"
}
```
`Response jika berhasil:
```
{
    "status": 200,
    "message": "Success",
    "data": {
        "is_hospital_case_last_status": true,
        "_id": "5ee33aed7b9fea00115b9be0",
        "transfer_status": "pending",
        "transfer_to_unit_id": "5ee30cd5e2265a001111848d",
        "transfer_to_unit_name": "RSU Dr Hasan Sadikin",
        "transfer_from_unit_id": "5ee1d415fc70e60011794adc",
        "transfer_from_unit_name": "UPT CIBUNTU",
        "transfer_comment": null,
        "transfer_case_id": "5ee33aed7b9fea00115b9bd9",
        "createdBy": "5e86b510d6aa0f0012d42794",
        "createdAt": "2020-06-12T08:21:01.212Z",
        "updatedAt": "2020-06-12T08:21:01.212Z",
        "__v": 0,
        "case": { ...CaseObjectPaylod }
    }
}
```
422 Error: Only user have unit credential can transfer Case.
```
{
    "status": 422,
    "message": "Anda tidak memiliki akses unit, silahkah edit profil user unit!",
    "data": null
}
```
409 Error: If NIk Case is filled in, Check is registered or processed in another unit.
```
{
    "status": 409,
    "message": "NIK 6473020586960001 atas nama tes mantap Sudah terdata di laporan kasus RSU Dr Hasan Sadikin",
    "data": null
}
```
409 Error: If there is a NIK Case, it is in the process of transferring (declined/pending)
```
{
    "status": 409,
    "message": "NIK 6473020586960001 atas nama tes mantap Sedang dalam proses rujukan ke RSU Dr Hasan Sadikin",
    "data": null
}
```

**Comment by khihadysucahyo** [comment]
cc @Arif9878

**Comment by shintadewiaw** [comment]
@khihadysucahyo pencarian hanya dapat dilakukan pada data pasien di puskesmas tersebut
