### ISSUE TITLE
[Rujukan] Proses Terima/Tolak Rujukan

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#168]

**Comment by khihadysucahyo** [comment]
### API
`POST: {{host}}/api/cases/{id}/transfers/{transferId}/{action}`

Request Payload:
`action: /* [ approve, decline, abort ] */`
```
{
  "transfer_comment": "debug purpose" /*optional*/
}
```

**Comment by khihadysucahyo** [comment]
cc @Arif9878

**Comment by ReksaMohammad** [comment]
@shintadewiaw 

<img width="503" alt="Screen Shot 2020-06-15 at 12 08 57" src="https://user-images.githubusercontent.com/42407562/84620017-0613a400-af01-11ea-8ace-e9ba5b104aa0.png">

**Comment by khihadysucahyo** [comment]
@Arif9878 @ReksaMohammad @shintadewiaw Terima rujukan ini juga sekaligus update data profil dan riwayat sekaligus? 

atau hanya ubah status transfer jadi terima saja seperti di fitur approval(field2nya read only)?

**Comment by shintadewiaw** [comment]
> @Arif9878 @ReksaMohammad @shintadewiaw Terima/Tolak rujukan ini juga sekaligus update data profil dan riwayat sekaligus? 
> 
> 
> 
> atau hanya ubah status transfer jadi terima/tolak saja seperti di fitur approval(field2nya read only)?

Ubah status transfer aja mas seperti fitur approval

**Comment by khihadysucahyo** [comment]
@shintadewiaw berarti kalo mengacu dari desain tampilan diatas, field2 itu hanya readonly kan?
