### ISSUE TITLE
[Rujukan] Create Kasus Rujukan yang Sudah Terdata di Faskes (Puskesmas)

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#170]
### Form Buat Rujukan
![Buat Rujukan](https://user-images.githubusercontent.com/63390998/84238459-494acd00-ab25-11ea-8df0-eedd5e08cead.png)

### Form Buat Rujukan Pasien Tidak Terdata
![Popup Buat Rujukan Pasien Terdata](https://user-images.githubusercontent.com/63390998/84237838-41d6f400-ab24-11ea-8d36-4840becacc63.png)

**NOTES**
Pasien sudah terdata sebagai OTG/ODP/PDP di puskesmas —> rujukan hanya bisa dilakukan setelah data terverifikasi oleh dinkes

### Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by khihadysucahyo** [comment]
### API

`{host}/api/cases/{id}/transfers`
Request Payload:
```
{
  "transfer_to_unit_id": "5ee27b3fa5f3aefbd5859159",
  "transfer_to_unit_name": "RS  HASAN SADIKIN",
  "transfer_comment: /* optional */
}
```

**Comment by khihadysucahyo** [comment]
cc @Arif9878

**Comment by Arif9878** [comment]
> ### API
> `{host}/api/cases/{id}/transfers`
> Request Payload:
> 
> ```
> {
>   "transfer_to_unit_id": "5ee27b3fa5f3aefbd5859159",
>   "transfer_to_unit_name": "RS  HASAN SADIKIN",
>   "transfer_comment: /* optional */
> }
> ```
> 
> Only allow to transfer if Case data has been verified by Dinkes
> 
> ```
> {
>     "status": 422,
>     "message": "Data Kasus belum terverifikasi oleh Dinkes!",
>     "data": null
> }
> ```

user id nya perlu atau gk had @khihadysucahyo

**Comment by shintadewiaw** [comment]
@khihadysucahyo pencarian hanya dapat dilakukan pada data pasien di puskesmas tersebut
