### ISSUE TITLE
[Hasil Test] API Pencarian nama pasien

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#171]
## Acceptance Criteria
- [x] Pencarian berdasarkan nama, nik, no telepon
- [x] Data yang diambil merupakan list kasus dengan semua status
- [x] Data yang diambil merupakan list kasus dengan semua tahapan
- [x] Value data yang diambil adalah identitas pasien dengan detail :
![Screenshot_2020-06-09 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/84118385-21903200-aa5d-11ea-9cae-d26b74b192fa.png)

### Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 ini waktu cari nama pasien

![image](https://user-images.githubusercontent.com/63390998/84629857-349b7a00-af15-11ea-94d0-9378324f052d.png)

**Comment by sandisunandar99** [comment]
@shintadewiaw sok baru pisan itu aku benerin
