### ISSUE TITLE
[Hasil Test] Penyesuaian Field di Single Entry

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#172]
## Keterangan Form
Grup 1 Pencarian pasien
Grup 2 Identitas Pasien
Grup 3 Hasil Pengetesan

## Daftar Lab
1. LAB JABAR
2. BTKL Jakarta
3. RSHS
4. IPB
5. LIPI
6. RSUI
7. Citra Arafik
8. Labkesda Kota Bekasi
9. RS Kota Bekasi (Chasbullaqh Abd Majid)
10. Labkesda Kab Bekasi
11. RSP Kerawang
12. BVET Subang-RSUD
13. UNPAD JATINANGOR
14. Lab FK Unswagati
15. BB Vet Bogor
16. Pelabuhan
17. Labkesda Kota Bandung
18. Poltekes
19. BKH/Kesmavet Jabar
20. RS Waled
21. RS Gn Jati
22. Al Ihsan - UNISBA
23. RS Cibinong

## List Sasaran

1. ODP
2. PDP
3. OTG
4. Kontak Erat
5. Tenaga Kesehatan
6. Pendaftar Pikobar
7. Pedagang Pasar
8. Pemuka Agama
9. Ulama
10. Pelaku Perjalanan
11. Pusat Keramaian
12. Lainnya

## Acceptance Criteria
- [x] Button multiple entry dihide
- [x] Peserta diganti jadi Pasien
- [ ] Field sasaran dihilangkan
- [x] Kategori dipindah ke grup 3
- [x] Tempat pengetesan ditambah Lab
- [ ] Kategori dibuat optional
- [x] Hide button "Simpan & Tambahkan Dilaporan Kasus"

### Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by erlangganugraha** [comment]
Tambahan :

1. swab ke by default : 1
2. Sasaran (list minta ke kabiondi)
3. NIK, "Tidak ada NIK" maka muncul input : "Alasan tidak ada NIK"
4. No Telepon, "Tidak ada No Telepon" maka muncul input : "Alasan tidak ada No Telepon"

Case 1 :
Cari melalui sumber lapor kasus

Case 2 :
Cari melalui sumber pendaftaran

Case 3 :
Buat redaksi "Data tidak ditemukan di Laporan Kasus atau Pendaftaran Pikobar, Harap Data diri pasien diinputkan manual"

**Comment by erlangganugraha** [comment]
kang @sandisunandar99  itu list labnya udh saya simpen dideskripsi cardnya

**Comment by shintadewiaw** [comment]
Sasaran tidak ada datanya sehingga tidak bisa disimpan (required)

![image](https://user-images.githubusercontent.com/63390998/84500936-c7eb6a00-acdf-11ea-9d90-3c17033c6e85.png)

@sandisunandar99 @naufalihsank

**Comment by naufalihsank** [comment]
@shintadewiaw coba di refresh teh page nya

**Comment by shintadewiaw** [comment]
@naufalihsank oke sudah ada mas, nuhun

**Comment by shintadewiaw** [comment]
@naufalihsank eh sori mas yang dinkes depok kok masih belum ada ya? tadi banjar yang bisa

**Comment by naufalihsank** [comment]
@shintadewiaw harusnya ga ngaruh sih, bentar
