### ISSUE TITLE
[Manajemen User] Penyesuaian create user

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#175]

**Comment by shintadewiaw** [comment]
mas @firmanJS  ini saya coba tambah data pengguna baru ada error unit_id required

**Tambah Data Pengguna**
![image](https://user-images.githubusercontent.com/63390998/84481519-6536a600-acc0-11ea-93eb-2d0cfa672350.png)

**Error**
![image](https://user-images.githubusercontent.com/63390998/84481353-2bfe3600-acc0-11ea-9d40-1d5a2aa7b931.png)
