### ISSUE TITLE
[Manajemen User] Penyesuaian update user

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#176]

**Comment by shintadewiaw** [comment]
Saat edit user, jika hak akses diubah menjadi Dinkes Kota maka tidak perlu menampilkan kolom Unit Kerja

![image](https://user-images.githubusercontent.com/63390998/84621244-4aed0a00-af04-11ea-9594-b5f3efb5c150.png)

@firmanJS @Arif9878

**Comment by firmanJS** [comment]
@shintadewiaw ini hanya di frontend aja ya
