### ISSUE TITLE
[Rujukan] Filter list rujukan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#209]
## Benchmark
![Screenshot_2020-06-18 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/84980086-54bc7a80-b15b-11ea-8cd0-a4dd584f1003.png)

## Design
![mockup](https://user-images.githubusercontent.com/42407562/84987344-28f4c100-b16a-11ea-8a40-16bc201f7976.png)

## Acceptance Criteria

- [ ] Filter data bisa berdasarkan sbb 
- [ ] 1. Tempat Rujukan
- [ ] 2. Status/kriteria pasien
- [ ] 3. Tanggal rujuk
- [ ] 4. Alamat tempat tinggal pasien (Kab/kota, kecamatan, kelurahan)
- [ ] 5. Hasil
- [ ] Terdapat tombol reset

### Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by ReksaMohammad** [comment]
@erlangganugraha @shintadewiaw 

![Filter List Pasien Rujukan](https://user-images.githubusercontent.com/42407562/84987344-28f4c100-b16a-11ea-8a40-16bc201f7976.png)

**Comment by shintadewiaw** [comment]
Setiap ngefilter muncul toast
![image](https://user-images.githubusercontent.com/63390998/85373404-6936b380-b55d-11ea-8e87-49d26b78a1fe.png)

@Arif9878 @khihadysucahyo

**Comment by khihadysucahyo** [comment]
@shintadewiaw kenapa ini wkwk?

**Comment by shintadewiaw** [comment]
salah mindah maap wkwk
