### ISSUE TITLE
[Detail Profil Kasus] Bug Detail

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#215]
![image](https://user-images.githubusercontent.com/63390998/85008672-7af80f80-b187-11ea-8696-da5a04dc2605.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw ini di frontendnya kayanya errornya

**Comment by shintadewiaw** [comment]
Wkwk mas arip suruh bikin BEnya juga tadi

**Comment by khihadysucahyo** [comment]
Okay sapp
