### ISSUE TITLE
[Kelola Pengguna] Bug Unit Kerja

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#249]
![image](https://user-images.githubusercontent.com/63390998/85969403-b8636500-b9f1-11ea-9d99-eaeedeff2b4a.png)

**Comment by firmanJS** [comment]
@shintadewiaw ini ketika edit ?

**Comment by shintadewiaw** [comment]
@firmanJS iya mas

**Comment by firmanJS** [comment]
@shintadewiaw di aku aman ko
