### ISSUE TITLE
Update profil user

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#256]
![Screenshot_2020-07-01 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/86190890-d22ab680-bb6f-11ea-9500-ab6719a2f30b.png)

### Acceptance Criteria
- [ ] Title caption : "Perbaharui Profil"
- [ ] Form disamakan dengan page ubah pengguna
- [ ] Ketika proses update berhasil, maka direct ke page sebelumnya diakses
- [ ] Terdapat validasi username
- [ ] Field "Hak akses" dibuat disabled

### Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by khihadysucahyo** [comment]
@erlangganugraha validasi usernamenya rulenya apa ya?

**Comment by khihadysucahyo** [comment]
API Check user by specified username
`{host}/api/users/username/{{value}}`
cc @Arif9878

**Comment by shintadewiaw** [comment]
mas @khihadysucahyo validasinya masih belum bisa yaa

![image](https://user-images.githubusercontent.com/63390998/86424527-fff93200-bd0c-11ea-8fe4-5830d7d7e8de.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw katanya udah ada wkwk

**Comment by khihadysucahyo** [comment]
@shintadewiaw coba cek card yg backend

**Comment by shintadewiaw** [comment]
@khihadysucahyo lah naha gabisa ya? wait kucek yang managemen user mas

**Comment by shintadewiaw** [comment]
@khihadysucahyo yang managemen user error juga wkwk kamu atau mas firman yang mau benerin?

**Comment by khihadysucahyo** [comment]
@shintadewiaw sebenarnya itu error validasi di model. bukan bug. Nah sekarang kita mau ngecek sebelum submit atau ketika submit?

**Comment by khihadysucahyo** [comment]
@shintadewiaw kalo mau ngecek sebelum submit, bisa pake API yg aku buatkan di card backend

**Comment by khihadysucahyo** [comment]
@shintadewiaw btw yg error di ss itu usernamenya udah ada kan ya, atau belum ada tapi error?

**Comment by shintadewiaw** [comment]
sebelumnya tuh, sebelum submit mas validasinya, cardnya yang mana sih?

**Comment by shintadewiaw** [comment]
oh yang ss itu tadinya aku ganti dinkeskotabandung, terus ada notif berhasil, pas aku buka lagi edit profil ga keganti, cuma teryata ada error yang aku inspect

**Comment by khihadysucahyo** [comment]
> API Check user by specified username
> `{host}/api/users/username/{{value}}`
> cc @Arif9878 

@shintadewiaw ini API yg aku buatkan untuk dipake validasi di FE sebelum submit, btw kalo API CRUD user itu masih sama, gada perubahan.

**Comment by shintadewiaw** [comment]
siaap mas, tolong di implemen ya mas @Arif9878

**Comment by Arif9878** [comment]
@khihadysucahyo validasi username dan email di pindah ke on BE karena saat pas edit username dan di kembaliin ke username semula response nya selalu true
