### ISSUE TITLE
[Laporan Kasus] Hapus Data Kontak Erat

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#276]
## AC

- [x] Terdapat pop up konfirmasi hapus data
- [x] Data yang bisa dihapus hanya data kontak yang belum dibuatkan laporan

**Comment by firmanJS** [comment]
@muhammaddyzf {{host}}/api/close-contacts/:close_contact 
:close_contact = _id
