### ISSUE TITLE
[Laporan Kasus] Edit Data Kontak Erat

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#277]
## Desain
<img width="816" alt="List Kontak Erat - Tambah Kontak Erat" src="https://user-images.githubusercontent.com/11548871/87136501-cce30f80-c2c5-11ea-8eb2-d486526a8118.png">

## AC

- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli *merah
---

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [ ] Tablet
- [ ] Desktop

**Comment by firmanJS** [comment]
PUT {{host}}/api/cases-revamp/:id/contact 
:id = id kontak erat
