### ISSUE TITLE
[Laporan Kasus] Revamp Input Laporan Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#279]
### Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=34%3A2503&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

### AC

- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] Untuk field dibawah ini perlu ada didatabase kita (aplikasi pelaporan pikobar) dengan diambil automatis berdasarkan user login
![Screenshot_2020-07-03 Create New Identification Bersatu Lawan Covid-19(1)](https://user-images.githubusercontent.com/11548871/86442120-7b6fd900-bd37-11ea-9362-10f227c220d9.png)

- [x] Untuk tanggal wawancara by default terisi tanggal sekarang
- [x] Terdapat validasi NIK jika sudah digunakan
- [x] Jika tanggal lahir diisi maka usia akan automatis terhitung dari tanggal lahir
- [x] Jika lokasi saat ini dipilih Rumah, maka muncul 2 pilihan sbb :
  - [x] 1. Pilihan sesuai alamat tempat tinggal
  - [x] 2. Tidak sesuai alamat tempat tinggal, maka muncul inputan alamat

---

### UX
![Screenshot_2020-07-03 Figma](https://user-images.githubusercontent.com/11548871/86446256-e6bca980-bd3d-11ea-9ddb-e932a3f9794c.png)
- [x] Jika dicheklist "Dari luar negeri", maka muncul field inputan negara dikunjungi dan diset mandatory beserta inputan tgl mulai & pulang perjalanan
- [ ] Jika dicheklist "Dari luar kota", maka muncul field inputan kota yang dikunjungi dan diset mandatory beserta inputan tgl mulai & pulang perjalanan
- [x] Untuk inputan pilihan "Kontak erat dengan suspek ?", jika user memilih jawaban Ya. Maka muncul inputan Nama Pasien Terkait yang dimana bisa dicari dalam proses penginputannya
- [x] Untuk inputan pilihan "Kontak erat dengan kasus konfirmasi (Positif) ?", jika user memilih jawaban Ya. Maka muncul inputan Nama Pasien Terkait yang dimana bisa dicari dalam proses penginputannya

#### Tambahan UX

- [x] Untuk field inputan pilihan Ya/Tidak by default jawabannya "Tidak"
- [x] Jika pertanyaan kunjungan tempat dipilih "Ya", maka muncul inputan **Lokasi/tempat** serta **Tanggal Kunjungan**

---
#### Tambahan
- [x] Penambahan Field Inputan Tanggal Kontak didalam form tambah kontak erat
- [x] Penambahan Field Inputan Tanggal Kunjungan dipertanyan kunjungi tempat
- [x] Penambahan Field Inputan List Petugas Kesehatan

**Comment by firmanJS** [comment]
up ac nya @shintadewiaw

**Comment by ReksaMohammad** [comment]
![Buat Laporan Kasus](https://user-images.githubusercontent.com/42407562/86550655-3208cf00-bf6d-11ea-9cd6-adfcb3467189.png)

**Comment by firmanJS** [comment]
@ReksaMohammad update kasus hanya bisa update identitas aja ? pas bagian yang lain di klik panah nya ga ada form nya di figma

**Comment by firmanJS** [comment]
@muhammaddyzf  api untuk cek exisiting nik 

{{host}}/api/cases-revamp/check?params=nik

response true = sudah ada false = belum ada

**Comment by ReksaMohammad** [comment]
@firmanJS semua bisa itu kang sebenernya, cuma di figmanya engga di tampilin semua cuma identitas aja soalnya defaultnya yg kebuka itu identitas

**Comment by shintadewiaw** [comment]
Tambah kasus baru error ID already exists in the database
![image](https://user-images.githubusercontent.com/63390998/87123879-d06c9b80-c2b1-11ea-814e-c6044c28bc48.png)

@firmanJS

**Comment by firmanJS** [comment]
up testing lagi @shintadewiaw

**Comment by shintadewiaw** [comment]
mas @firmanJS dashboadnya kok ga update ya? 
ini login pake faskes mas, apotekcipa,apotekcipa890
![image](https://user-images.githubusercontent.com/63390998/87218577-6a9a1580-c37e-11ea-80d1-df8bc5100643.png)

![image](https://user-images.githubusercontent.com/63390998/87218589-738ae700-c37e-11ea-82d5-aa9b923dfda7.png)

**Comment by firmanJS** [comment]
@shintadewiaw ini card nya dipisah aja sin ini kan untuk input

**Comment by shintadewiaw** [comment]
@firmanJS oh iya bener wkwk siap mas
