### ISSUE TITLE
[Kontak Erat] Form Identifikasi Kontak Erat

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#295]
## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=174%3A1133&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

## AC

- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] NIK & No telepon dibuat mandatory, jika tidak ada NIK/No telepon maka inputkan alasan tidak ada NIK/No telepon
- [x] By default nama pewawancara get from nama pengguna
- [x] Tanggal wawancara pelacakan kontak by default terisi tanggal sekarang
- [x] Terdapat validasi NIK jika sudah digunakan
- [x] Jika tanggal lahir diisi maka usia akan automatis terhitung dari tanggal lahir

---

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

**Comment by khihadysucahyo** [comment]
@erlangganugraha alasan nik/no telp ini dibuat tiap field [alasan nik & alasan nohp] atau jadi satu field alasan aja?
