### ISSUE TITLE
[Laporan Kasus] Tambah Data Kontak Erat

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#322]
## Desain
<img width="816" alt="List Kontak Erat - Tambah Kontak Erat" src="https://user-images.githubusercontent.com/11548871/87136501-cce30f80-c2c5-11ea-8eb2-d486526a8118.png">

## AC

- [ ] Layout disamakan dengan desain yang sudah dibuat
- [ ] Terdapat field2 yang mandatory dengan melabeli * merah
---

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

## Responsiveness
- [ ] Mobile
- [ ] Tablet
- [ ] Desktop

**Comment by firmanJS** [comment]
@muhammaddyzf POST {{host}}/api/cases-revamp/:id/contact
