### ISSUE TITLE
[Laporan Kasus] Edit Data Pasien

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#324]
## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=174%3A1133&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

## AC
- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] Dibuat pop up
- [x] NIK & No telepon dibuat mandatory, jika tidak ada NIK/No telepon maka inputkan alasan tidak ada NIK/No telepon

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [ ] Tablet
- [ ] Desktop

**Comment by firmanJS** [comment]
@muhammaddyzf 

get detail hampir sama dengan api exisiting 

GET api/cases/:id

update juga PUT api/cases/:id

**Comment by shintadewiaw** [comment]
@firmanJS mas ubah data  pasien error 500

![image](https://user-images.githubusercontent.com/63390998/87380874-9a832c00-c5bd-11ea-9808-cdc081081e12.png)

**Comment by firmanJS** [comment]
@shintadewiaw di aku normal kok update nya semua kolom atau gimana ?

**Comment by shintadewiaw** [comment]
@firmanJS aku coba lagi ga kenapa napa mas :( pindah e2e aja mas

**Comment by firmanJS** [comment]
@shintadewiaw boleh kalau udah yakin mah harus di rekam lagi tadi muncul error seperti itu ketika ubah semua kolom atau beberapa bagian ajah
