### ISSUE TITLE
[Laporan Kasus] Update Status Pasien

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#325]
## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=174%3A1133&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

## AC
- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] Dibuat pop up
- [x] NIK & No telepon dibuat mandatory, jika tidak ada NIK/No telepon maka inputkan alasan tidak ada NIK/No telepon

---
## UX
- [x] Field inputan hasil tetap dimuncul jika memilih kriteria **OTG,ODP, PDP & Positif** + memilih tahapan **selesai**
- [x] Jika dipilih ODP, PDP, dan Positif maka inputan gejala + tanggal muncul gejala diset mandatory 

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

**Comment by firmanJS** [comment]
@muhammaddyzf 

get detail {{host}}/api/cases/:id/last-history 

:id = _id

update {{host}}/api/history_cases
