### ISSUE TITLE
[Laporan Kasus] Data Dashboard Tidak Update

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#329]
### **How to Reproduce Bug:**
1. Login sebagai faskes
2. Data dashboard tidak sesuai dengan data pada list kasus

![image](https://user-images.githubusercontent.com/63390998/87218577-6a9a1580-c37e-11ea-80d1-df8bc5100643.png)

![image](https://user-images.githubusercontent.com/63390998/87218589-738ae700-c37e-11ea-82d5-aa9b923dfda7.png)

**Comment by firmanJS** [comment]
@shintadewiaw jangan nyimpen username sama password di github ya nanti kena issue security lagi 
aku edit deskripsi nya
japri aja user sama passnya :+1:

**Comment by shintadewiaw** [comment]
@firmanJS oh wkwkwk siap mas
