### ISSUE TITLE
[Laporan Kasus] Bug Data List Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#340]
### **How to Reproduce Bug:**
1. Login sebagai dinkeskotatasikmalaya
2. Membuat pengguna faskes baru 
3. Login sebagai faskes baru
4. Ketika buka list kasus (seharusnya kosong) tetapi data list kasus dinkes masuk ke list kasus faskes tersebut

![image](https://user-images.githubusercontent.com/63390998/87382107-5f362c80-c5c0-11ea-88e0-4898554040bc.png)

**Comment by firmanJS** [comment]
@shintadewiaw ini karena unit yang di assign ke user tersebut sudah ada datanya cc @khihadysucahyo
