### ISSUE TITLE
[Dashboard] API Dashboard Kriteria Baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#375]
## Desain
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3164%3A0

## AC
- [ ] Terdapat filter berdasarkan wilayah
- [ ] Roles disamakan dengan dashboard lama
- [ ] Disamakan dengan rumus

## Rumus
1. Rumus lama
![Aplikasi Pelaporan@2x(25)](https://user-images.githubusercontent.com/11548871/88286549-1fd3b280-cd1b-11ea-849c-1b3dad5d9b90.png)

2. Rumus Baru
![Aplikasi Pelaporan@2x(30)](https://user-images.githubusercontent.com/11548871/88371635-a2617e00-cdbe-11ea-9ee0-042804999c66.png)

**Comment by khihadysucahyo** [comment]
kang @firmanJS tadi dari erlangga saya diminta support juga di task ini, boleh minta tolong di breakdown kang apa yang harus dilanjutkan.

**Comment by khihadysucahyo** [comment]
{{host}}/api/dashboard/v2/summary-case-criteria

**Comment by khihadysucahyo** [comment]
@rendiriz
