### ISSUE TITLE
[Data Kasus] Query Data Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#376]
## Step

- [ ] Step 1 : Melakukan Query OTG ke Kontak Erat
- [ ] Step 2 : Crosscheck Hasil Query OTG ke Kontak Erat
- [ ] Step 3 : Melakukan Query ODP ke Suspek
- [ ] Step 4 : Crosscheck Hasil Query ODP ke Suspek
- [ ] Step 5 : Melakukan Query PDP ke Suspek
- [ ] Step 6 : Crosscheck Hasil Query PDP ke Suspek
- [ ] Step 7 : Melakukan Query Positif ke Konfirmasi
- [ ] Step 8 : Crosscheck Hasil Query Positif ke Konfirmasi
- [ ] End Step : Push ke production

## Rumus
![Query Kriteria Baru](https://user-images.githubusercontent.com/11548871/88368628-a7233380-cdb8-11ea-829e-3c2bb4cebdb2.png)

**Comment by firmanJS** [comment]
Query update nanti di eksekusi mang @sandisunandar99 aku bagian crosschecknya cc @erlangganugraha
