### ISSUE TITLE
[Kontak Erat] Bug Kontak Erat

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#405]
### **How to Reproduce Bug:**
1. Login sebagai dinkes
2. Membuat Laporan Kontak Erat
3. Ketika menekan tombol simpan error

![89ac72d7-cdc7-4cb9-bbf6-868ec822f661](https://user-images.githubusercontent.com/63390998/89150235-4f3eb680-d588-11ea-8be4-720c958c33af.jpg)

**Comment by khihadysucahyo** [comment]
ini gmn ya skenario testingnya @shintadewiaw ?
