### ISSUE TITLE
[Laporan Kasus] Input data faktor riwayat perjalanan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#411]
> faktor riwayat perjalanan ini bertujuan menncatat data riwayat perjalanan pasien selama 14 hari kebelakang, guna sebagai salah satu acuan faktor resiko.

## Ref
![Screenshot_2020-08-04 REV-05_Pedoman_P2_COVID-19_13_Juli_2020 pdf](https://user-images.githubusercontent.com/11548871/89317271-56a8b180-d6a7-11ea-951c-3d618fa9e92b.png)

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A3168&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

## AC
- [x] Create API data negara + kota
- [x] Create API data provinsi + kota indonesia 
- [x] Bisa > 1 data input
- [x] Bisa menghapus data
- [x] Pertanyaan ; "Dalam 14 hari sebelum sakit, apakah memiliki riwayat perjalanan ?" diset mandatory 
- [x] Input negara dibuat dropdown
- [x] Input provinsi dibuat dropdown
- [x] Input kota dibuat dropdown

## UX

- [x] Jika jenis perjalanannya dipilih dari luar negeri maka :

> Inputan tempat perjalanan adalah ; Negara & kota

- [x] Jika jenis perjalanannya dipilih dari luar Kota maka :

> Inputan tempat perjalanan adalah ; Provinsi & kota

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/89770240-ae706e00-db28-11ea-856c-5cb29868a77e.png)
 

"travelling_history_before_sick_14_days": true,
	"travelling_history":[
		{
			"travelling_type" : "Dari Luar Negri",
			"travelling_visited" : "Brazil",	
			"travelling_date": "2020-08-01",
			"travelling_arrive": "2020-08-15"
		},
		{
			"travelling_type" : "Dari Luar Kota",
			"travelling_visited" : "Bali",	
			"travelling_date": "2020-08-01",
			"travelling_arrive": "2020-08-15"
		}
	],


![image](https://user-images.githubusercontent.com/6767399/89770280-bf20e400-db28-11ea-89a0-ac130bcc5fc6.png)

	"visited_local_area_before_sick_14_days": true,
	"visited_local_area": [
		{
			"visited_local_area_province" : "JAWA BARAT",
			"visited_local_area_city" :"BANDUNG"
		}
	],

cc : @Arif9878
