### ISSUE TITLE
[Laporan Kasus] Input data faktor riwayat bepergian ke tempat publik

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#412]
> faktor riwayat bepergian ke tempat publik ini bertujuan mencatat data riwayat pasien selama 14 hari kebelakang, guna sebagai salah satu acuan faktor resiko.

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A3168&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

## AC
- [x] Bisa > 1 data input
- [x] Bisa menghapus data
- [x] Pertanyaan ; "Dalam 14 hari sebelum sakit, apakah pernah mengunjungi RS/ Pasar/tempat publik lainnya ?" diset mandatory 
- [x] Option Kategori Tempat ; Pasar Modern/Tradisional, Pasar Hewan, Fasilitas Kesehatan, Tempat Wisata, Tempat Ibadah, Restoran, Tempat Publik Lainnya
- [x] Input Nama tempat yang dikunjungi terdapat placeholder
- [x] Type Input date time untuk Tanggal & waktu berkunjung 
- [x] Type Input number untuk Lama kunjungan/durasi

## UX

- [x] Jika Dalam 14 hari sebelum sakit, apakah pernah mengunjungi RS/ Pasar/tempat publik lainnya ? dipilih **Ya** maka :

> Kategori tempat diset mandatory

**Comment by sandisunandar99** [comment]
"has_visited_public_place": true,
	 "visited_public_place": [
		 {
				"place_category": "PASAR",
				"place_name": "pasar ikan",
				"place_address": "jalan peta",
				"place_date_visited": "2020-08-01",
				"place_duration_visited": "60"
		 },
		 {
				"public_place_category": "PASAR",
				"public_place_name": "pasar ikan",
				"public_place_address": "jalan peta",
				"public_place_date_visited": "2020-08-01",
				"public_place_duration_visited": "60"
		 }
	 ],

**Comment by sandisunandar99** [comment]
cc : @Arif9878
