### ISSUE TITLE
[Laporan Kasus] Multiple input faktor kontak paparan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#414]
> faktor Kontak Paparan ini bertujuan mencatat data riwayat pasien selama 14 hari kebelakang, guna sebagai salah satu acuan faktor resiko.

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A3168&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

## AC
- [x] Bisa > 1 data input
- [x] Bisa menghapus data
- [x] Pertanyaan ; "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya?" diset mandatory 
- [x] Hubungan seharusnya dibuat select option, isinya ;

- Keluarga serumah
- Teman Kerja
- Jamaah ditempat ibadah
- Lainnya

## UX

- [x] Jika Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya? dipilih **Ya** maka :

> - Nama Kontak diset mandatory
> - Kriteria Kontak diset mandatory

- [x] Hubungan, jika dipilih "Ya", maka ;

> - Show inputan lainnya dibawah 

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

## Browser
- [x] Mozilla Firefox

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/90609417-309a1a00-e22e-11ea-96e9-f3a162406e8f.png)

mas ini kalau pilih "Tidak" form yang kontak primer harusnya ga mandatory

**Comment by shintadewiaw** [comment]
mas @sandisunandar99  ini kalau pilih "tidak" masih error ya, seharusnya ga mandatory formnya kalau pilih "tidak"
![image](https://user-images.githubusercontent.com/63390998/91167935-f2ee3300-e6fe-11ea-86d5-763aedb35acf.png)

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/91169378-73159800-e701-11ea-8642-84f3055e822b.png)
@shintadewiaw 
ini sudah ga di buat required sin dari kemarin2 jg ,, coba clear cache,,

**Comment by shintadewiaw** [comment]
eh bentar mas, wkwkwk terburu buru di close

Jika Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya? dipilih "Ya" maka :
Nama Kontak diset mandatory
Kriteria Kontak diset mandatory

nah tadi kalo formnya ketutup gini dia bisa simpan tanpa masukin nama kontak & kriteria
![image](https://user-images.githubusercontent.com/63390998/91178855-f63dea80-e70f-11ea-95fd-430fca296ddc.png)

kalau formnya dibuka baru dia ada validasinya
![image](https://user-images.githubusercontent.com/63390998/91179159-56349100-e710-11ea-89cc-fd23b9d01320.png)

ini mas @Arif9878 kali ya?
