### ISSUE TITLE
[Laporan Harian] API Total Setiap Kriteria

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#430]
## Rumus
![Aplikasi Pelaporan@2x(33)](https://user-images.githubusercontent.com/11548871/89815559-337e7600-db6f-11ea-95d2-7156071e3821.png)

## AC
- [ ] Value untuk Kolom Dinas Kesehatan Provinsi ; Jawa Barat
- [ ] Value untuk kolom dinas kesehatan kota/kab berdasarkan user login
- [ ] Value untuk kolom Nama Petugas berdasarkan Nama Lengkap user login & No Hp, dgn format (Nama Lengkap - No Hp). Contoh isian ; Dinas Kesehatan Kota Cimahi - 089682632631

Count data sbb ;

- [ ] Total yg dihitung adalah kotak yg berwarna orange (*lihat pada rumus)
- [ ] Total yg dihitung perhari ini
- [ ] Total yg dihitung dalam 1 minggu terakhir
- [ ] Total yg dihitung dalam 1 bulan terakhir
- [ ] Terdapat filter berdasarkan tgl update riwayat
- [ ] Bisa diexport ke excel
- [ ] Bisa diexport to image

**Comment by khihadysucahyo** [comment]
API: {{host}}/api/reports/daily-report
cc @Arif9878

**Comment by erlangganugraha** [comment]
No. 1 = kriteria : kontak erat & status pasien terakhir : masih dikarantina
No. 2 = kriteria : kontak erat & status pasien terakhir : masih dikarantina & tgl update riwayat pasien : today, day-7, last month


2. 2.4 = kriteria : konfirmasi + riwayat perjalanan : dari luar negeri / luar kota
   2.5 = kriteria : konfirasi + punya riwayat sbg kontak erat / pernah ke tempat publik / ke area transmisi lokal
   2.6 = 2.1 - (2.4 + 2.5)

cc @khihadysucahyo

**Comment by shintadewiaw** [comment]
2.4 = Dalam 14 hari sebelum sakit, apakah memiliki riwayat dari luar negeri/luar kota ?

2.5 = History status kontak erat

2.6 = !(Dalam 14 hari sebelum sakit, apakah memiliki riwayat dari luar negeri/luar kota ?) && !(History status kontak erat)

**Comment by shintadewiaw** [comment]
3.1 = Konfirmasi dengan status sakit

**Comment by shintadewiaw** [comment]
### Feedback 26 Agustus 2020
1. "Jumlah kasus konfirmasi kontak" tidak muncul pada laporan harian
![image](https://user-images.githubusercontent.com/63390998/91252017-e31a3180-e786-11ea-8e72-395f537cffc6.png)
![UMUR](https://user-images.githubusercontent.com/63390998/91251946-c3830900-e786-11ea-90e4-44c50f7cc1e8.png)

2. Jumlah kontak erat menjadi suspek tidak terhitung
![image](https://user-images.githubusercontent.com/63390998/91256495-ad2e7a80-e791-11ea-941e-621735e2ea43.png)
![UMUR](https://user-images.githubusercontent.com/63390998/91256481-a4d63f80-e791-11ea-92d1-87d41394435d.png)

3. Jumlah kontak erat menjadi kasus konfirmasi tidak terhitung
![image](https://user-images.githubusercontent.com/63390998/91257132-4f029700-e793-11ea-9456-c75ab368cb5c.png)
![KONTAK ERAT](https://user-images.githubusercontent.com/63390998/91257187-79eceb00-e793-11ea-94d8-289018e9ae30.png)

4.  Jumlah kasus konfimrasi pernjalanan (impor) seharusnya diambil dari "Dalam 14 hari sebelum sakit, apakah memiliki riwayat dari luar negeri/luar kota ?"

5. Jumlah kasus konfirmasi kontak seharusnya diambil dari "History status kontak erat sebelum menjadi konfirmasi"

6. Jumlah kasus konfirmasi tidak ada riwayat perjalanan atau kontak erat, seharusnya diambil dari "!(Dalam 14 hari sebelum sakit, apakah memiliki riwayat dari luar negeri/luar kota ?) && !(History status kontak erat)"

**Comment by shintadewiaw** [comment]
7. Jumlah reaktif periksa RTPCR tidak masuk pada laporan harian

8. Jumlah reaktif periksa RTPCR(+) tidak masuk pada laporan harian

9. Jumlah kasus konfirmasi (RS. Rujukan & Isolasi/Karantina Mandiri) tidak masuk pada laporan harian

**Comment by khihadysucahyo** [comment]
> 1. Jumlah reaktif periksa RTPCR tidak masuk pada laporan harian
> 2. Jumlah reaktif periksa RTPCR(+) tidak masuk pada laporan harian
> 3. Jumlah kasus konfirmasi (RS. Rujukan & Isolasi/Karantina Mandiri) tidak masuk pada laporan harian

@shintadewiaw 
> 1. Jumlah reaktif periksa RTPCR tidak masuk pada laporan harian --> semua `lab_confirm`
> 2. Jumlah reaktif periksa RTPCR tidak masuk pada laporan harian --> semua `lab_confirm && positive`
