### ISSUE TITLE
[Laporan Kasus] Export List Kasus Rev 5

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#446]
## AC

- [ ] Penamaan file "Data Kasus [Username] - [Tanggal Time Sekarang], Contoh : Data Kasus Dinkes Kota Cimahi - 12/04/202 19:45 WIB
- [ ] Data Yang Diexport sbb ;

1. Nama Pewawancara
2. No HP Pewawancara
3. Tanggal Wawancara
4. Nama Pasien
4. NIK
5. Alasan tidak ada NIK
6. No Telepon
7. Alasan Tidak Ada No Telepon
8. Nama Ortu
9. Tempat Lahir
10. Tanggal Lahir
11. Usia Tahun
12. Usia Bulan
12. Jenis Kelamin
13. Kota/Kab
14. Kecamatan
15. Kel/Desa
16. Alamat Lengkap (RT/RW)
17. Pekerjaan
18. Alamat Kantor
19. Kewarganegraan (By Default Indonesia. Tetapi kika pilih WNA, maka isian data sesuai negara asal)
20. Kriteria
21. Status Pasien Terakhir
22. Lokasi Saat Ini (Rumah/Rumah Sakit/Lainnya)
23. Terdapat Gejala Ya/Tidak
24. Tanggal Muncul Gejala
25. Gejala (termasuk gejala lainnya jika ada)
26. Kondisi Penyerta (termasuk kondisi penyerta lainnya jika ada)
27. Diagnosis ARDS (Ya/Tidak)
28. Diagnosis Pneumonia (Ya/Tidak)
29. Diagnosis Lainnya
30. Data Kontak Erat (Nama - Id Case)
31. Dari Luar Negeri (Ya/Tidak)
32. Negara Yang Dikunjungi
33. Tanggal Mulai Perjalanan
34. Tanggal Pulang Perjalanan
35. Dari Luar Kota (Ya/Tidak)
36. Kota Yang Dikunjungi
37. Tanggal Mulai Perjalanan
38. Tanggal Pulang Perjalanan
39. Kontak Dengan Kasus Suspek (Ya/Tidak)
40. Kontak Dengan Nama Kasus Suspek
39. Kontak Dengan Kasus Konfirmasi (Ya/Tidak)
40. Kontak Dengan Nama Kasus Konfirmasi
41. Mengunjungi Pasar Hewan (Ya/Tidak
42. Nama Lokasi Pasar Hewan
43. Tgl Kunjungan Ke Pasar Hewan
44. Mengunjungi Tempat Publik (Ya/Tidak
45. Nama Lokasi Tempat Publik
46. Tgl Kunjungan Ke Tempat Publik
47. Kelompok ISPA Berat (Ya/Tidak)
48. Petugas Kesehatan (Ya/Tidak)
49. Alat Pelindung yang Digunakan
50. Pemeriksaan Serum (Ya/Tidak)
51. Pemeriksaan Sputum (Ya/Tidak)
52. Pemeriksaan Swab Nasofaring/Orofaring (Ya/Tidak)
53. Merokok (Ya/Tidak)
55. Konsumsi Alkohol (Ya/Tidak)
55. Aktifitas Fisik
56. Penghasilan
57. Tanggal Input
58. Tanggal Update Riwayat
59. Author

## Contoh Hasil File Export ;
[Data Kasus Example - 18_08_2020 16 00 WIB.xlsx](https://github.com/jabardigitalservice/pikobar-pelaporan-backend/files/5093020/Data.Kasus.Example.-.18_08_2020.16.00.WIB.xlsx)

data yang ditakeout
 // "Pemeriksaan Serum" 
 // "Pemeriksaan Sputum"
 // "Pemeriksaan Swab Nasofaring/Orofaring"
 // "Mengunjungi Pasar Hewan"
 // "Nama Lokasi Pasar Hewan"
 //"Tgl Kunjungan Ke Pasar Hewan":

**Comment by shintadewiaw** [comment]
1. Nama pewawancara & Tanggal Wawancara valuenya belum masuk (Nama = User Login, Tanggal = Tanggal Input Kasus)
2. Usia sebaiknya jangan langsung di konversi di tahunnya, melainkan dipisah contoh: 10 Tahun 0 Bulan
![image](https://user-images.githubusercontent.com/63390998/91724753-f9c9e980-ebc7-11ea-84bd-603024b25128.png)
3. Alamat Lengkap Undefined
![image](https://user-images.githubusercontent.com/63390998/91724701-e61e8300-ebc7-11ea-94b1-078c29b48f9a.png)
4.

**Comment by shintadewiaw** [comment]
ada error waktu mau export ya guys @firmanJS @sandisunandar99 
![image](https://user-images.githubusercontent.com/63390998/92553545-5d6daa00-f28d-11ea-9e08-42bb391a2580.png)
