### ISSUE TITLE
[Laporan Kasus] Tambahan Cetak Laporan PE

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#447]
## AC

- [ ] Lenkapi data sbb sesuai yang sudah ditandai pada kotak merah ;

- [ ] Form 1

![Aplikasi Pelaporan@2x(35)](https://user-images.githubusercontent.com/11548871/90572235-bc378a80-e1dd-11ea-925d-aea46e68e7ff.png)
---
- [ ] Form 2
![Aplikasi Pelaporan@2x(36)](https://user-images.githubusercontent.com/11548871/90572317-eab56580-e1dd-11ea-8e5a-ed52604e92f1.png)
---

- [ ] Form 3
![Aplikasi Pelaporan@2x(37)](https://user-images.githubusercontent.com/11548871/90572327-f2750a00-e1dd-11ea-815f-62031cf41d48.png)

**Comment by shintadewiaw** [comment]
### Feedback Laporan PE (25/08/2020)
1. Umur 6 bulan seharusnya 0 Tahun 6 Bulan (tahun jangan langsung di konversi)
![UMUR](https://user-images.githubusercontent.com/63390998/91126519-5f047300-e6ce-11ea-83fd-0dc8def93dc2.png)

2.  Apa pasien mempunyai diagnosis atau etiologi lain? di form sudah memilih tidak terisi pada form PE tidak terceklist
![image](https://user-images.githubusercontent.com/63390998/91126652-b60a4800-e6ce-11ea-9804-27000768dd2a.png)

![UMUR](https://user-images.githubusercontent.com/63390998/91126619-98d57980-e6ce-11ea-9724-5361d07a7f2e.png)

3. Status pasien terakhir & tanggal  tidak terisi
![image](https://user-images.githubusercontent.com/63390998/91126695-cf12f900-e6ce-11ea-87b4-85f7049ecaf9.png)
![UMUR](https://user-images.githubusercontent.com/63390998/91126730-e18d3280-e6ce-11ea-830e-00409770a6de.png)

4. Mengisikan "Dalam 4 hari sebelum sakit, apakah memiliki kontak dengan kasus/probable" tetapi tidak muncul di laporan PE
![image](https://user-images.githubusercontent.com/63390998/91126854-2d3fdc00-e6cf-11ea-821d-e73ae6a96c97.png)
![UMUR](https://user-images.githubusercontent.com/63390998/91126909-4ba5d780-e6cf-11ea-9b4c-16ac69b4d60b.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw "Mengisikan "Dalam 4 hari sebelum sakit, apakah memiliki kontak dengan kasus/probable" tetapi tidak muncul di laporan PE" ini yg suspek doang, coba cek dirumusnya

**Comment by khihadysucahyo** [comment]
@shintadewiaw 
> * [ ]  Form 2
>   ![Aplikasi Pelaporan@2x(36)](https://user-images.githubusercontent.com/11548871/90572317-eab56580-e1dd-11ea-8e5a-ed52604e92f1.png)

**Comment by shintadewiaw** [comment]
suspek/probabel ga sih tapi di keterangannya?wkwk cc: @erlangganugraha

**Comment by erlangganugraha** [comment]
Suspek & probable @shintadewiaw @khihadysucahyo 
sorry kurang parameter dirumus nya

**Comment by khihadysucahyo** [comment]
wkwk yg umur ternyata di dbnya nyimpennya 0.5 ini pantesan
![image](https://user-images.githubusercontent.com/31666194/91249886-ec54cf80-e781-11ea-87b5-ba5545fade12.png)

**Comment by shintadewiaw** [comment]
jadi gimana mas? bisa diubah tidak?

**Comment by shintadewiaw** [comment]
Jika menambahkan "Serum" pada Pemeriksaan Lain, muncul juga pada "Laboratorium Konfirmasi"
![image](https://user-images.githubusercontent.com/63390998/91535684-bb20fe80-e93d-11ea-8fbb-83e8c72a3d8b.png)

**Comment by khihadysucahyo** [comment]
> 2. Memilih "Ya" pada Dalam 14 hari sebelum sakit, apakah memiliki kontak
>    dengan kasus suspek/probable COVID-19 ?  value yang masuk "Tidak"
>    ![image](https://user-images.githubusercontent.com/63390998/91535922-1bb03b80-e93e-11ea-8a48-16f738eb7065.png)
>    ![image](https://user-images.githubusercontent.com/63390998/91535948-266ad080-e93e-11ea-9cad-d071ad729be2.png)

@shintadewiaw ini dianggap "tidak" karena kontaknya kosong
karena ini aku ngambilnga di kontak primer, field kriteria
gimana2 ?

**Comment by khihadysucahyo** [comment]
@shintadewiaw coba kita bedah bareng inputannya wkwk
jadi kalo misal centang ya, semua di kontap paparan kecentang juga ga?
atau harusnya dilihat dari field kriteria di form kontak primer?

**Comment by shintadewiaw** [comment]
> @shintadewiaw coba kita bedah bareng inputannya wkwk
> 
> jadi kalo misal centang ya, semua di kontap paparan kecentang juga ga?
> 
> atau harusnya dilihat dari field kriteria di form kontak primer?

Hah gimana gimana mas?wkwkwk tar deh kita tes bareng aja ya

**Comment by khihadysucahyo** [comment]
> > @shintadewiaw coba kita bedah bareng inputannya wkwk
> > 
> > jadi kalo misal centang ya, semua di kontap paparan kecentang juga ga?
> > 
> > atau harusnya dilihat dari field kriteria di form kontak primer?
> 
> Hah gimana gimana mas?wkwkwk tar deh kita tes bareng aja ya

@shintadewiaw wkwk gass deh mau kapan, sekarang/senin?

**Comment by shintadewiaw** [comment]
> > > @shintadewiaw coba kita bedah bareng inputannya wkwk
> > > 
> > > jadi kalo misal centang ya, semua di kontap paparan kecentang juga ga?
> > > 
> > > atau harusnya dilihat dari field kriteria di form kontak primer?
> > 
> > Hah gimana gimana mas?wkwkwk tar deh kita tes bareng aja ya
> 
> @shintadewiaw wkwk gass deh mau kapan, sekarang/senin?

Sekarang kuy

**Comment by shintadewiaw** [comment]
https://meet.google.com/vhi-knxh-vev

**Comment by shintadewiaw** [comment]
@khihadysucahyo ini sementara ku closed aja kali ya mas, nanti kalo dari FEnya udah, ku cek lagi
