### ISSUE TITLE
[Input Hasil Test] Bug Perhitungan Total RDT/PCR

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#457]
### Deskripsi:
Ketika menambahkan data baru, total perhitungan RDT  tidak sesuai seperti yang sudah di inputkan

![ER1](https://user-images.githubusercontent.com/63390998/91006009-80982880-e602-11ea-98e0-22c869971f45.jpg)

![ER2](https://user-images.githubusercontent.com/63390998/91006016-842baf80-e602-11ea-98aa-82e2d3e0649b.jpg)

**Comment by sandisunandar99** [comment]
shin yang ini mksdnya gmna ya?? itu kn insert 1 otomatis 1 juga,, bug nya dmana nya??

**Comment by shintadewiaw** [comment]
ini jadi aku baru bikin banget kan mas datanya, pas di input totalnya langsung RDT 4x sama PCR 14x padahal aku masukinnya RDT dan (ke-1)

![ER2](https://user-images.githubusercontent.com/63390998/91014970-8c8ce600-e614-11ea-8db1-cca89e05b1c4.jpg)

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 besok cobain yang dinkes sumedang yaa, ini yang tadi di input mas sandi aku hapus terus ku input ulang jadi gini totalnya

![image](https://user-images.githubusercontent.com/63390998/91063170-d519c300-e657-11ea-8a2e-3ba192095c15.png)
