### ISSUE TITLE
[Kasus Keterkaitan] Data Kasus Keterkaitan import into database

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#461]

**Comment by sandisunandar99** [comment]
yang ini tuh dari si cindy itu ya ? @erlangganugraha

**Comment by erlangganugraha** [comment]
Ini yang tim data itu kang, data infector & infectee yg perlu diupdate/import ke database kita @sandisunandar99
