### ISSUE TITLE
[Laporan Harian] Export laporan harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#468]
## Desain
![Aplikasi Pelaporan@2x(13) 2](https://user-images.githubusercontent.com/11548871/87882836-23bab880-ca2d-11ea-8bed-80b282f1dd38.png)

## AC
- [ ] Format export disamakan dengan lampiran 4
- [ ] Format File Name ; Nama Dinkes Kota/Kab - Tanggal Filter - Nama Petugas/Pengguna

## Format Excel
https://docs.google.com/spreadsheets/d/1Xo_aGlZksx_8COKmCVg3MKUdWdR9yT7GhMT98aXHhF4/edit#gid=0

## Browser
- [ ] Mozilla Firefox

**Comment by erlangganugraha** [comment]
@khihadysucahyo udah saya update ACnya utk penamaan filenya

plus contoh format excelnya

**Comment by khihadysucahyo** [comment]
@erlangganugraha Format File Namenya gini: **Nama Dinkes Kota/Kab - Tanggal Filter - Nama Petugas/Pengguna**
Nama pengguna juga banyak yg dinamain dinkes gimana?
jadi nanti **DInkes Kota Bandung - 2019/01/01 - DInkes Kota Bandung**

**Comment by erlangganugraha** [comment]
gpp mas @khihadysucahyo

**Comment by shintadewiaw** [comment]
Yang ini belum disesuaikan di excelnya ya mas
![image](https://user-images.githubusercontent.com/63390998/91730257-ea4e9e80-ebcf-11ea-9882-53ee9130b25c.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw  yang ini jadinya ga dibinding di excelnya, jadi cukup di penamaan file aja.
soalnya dari package xls yg dipake di pelaporan ga bisa custom header

**Comment by shintadewiaw** [comment]
baiklah @khihadysucahyo
