### ISSUE TITLE
[List Kasus] OTG ditambahkan pada Perhitungan Total Data Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#47]
**Expected Result**: OTG ditambahkan pada perhitungan total data kasus

**Checklist**

- [x] OTG ditambahkan pada perhitungan data kasus

- [x] Perhitungan data sesuai

**Comment by firmanJS** [comment]
@shintadewiaw api done tinggal nunggu frontend

**Comment by shintadewiaw** [comment]
perhitungannya belum masuk mas yang otg @firmanJS 
![image](https://user-images.githubusercontent.com/63390998/79826415-db581400-83c5-11ea-88bb-7e85115799d2.png)
![image](https://user-images.githubusercontent.com/63390998/79826447-f3c82e80-83c5-11ea-91e4-4034094d7184.png)
