### ISSUE TITLE
[List Kasus] CRUD Dari luar kota/negeri

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#494]
## User Story
Sebagai user faskes/dinkes. Saya ingin melihat, menambah, mengubah ataupun menghapus data dari luar kota/negeri yang sudah saya input saat buat laporan kasus baru. **Maka dari itu perlu ada fitur CRUD dari luar kota/negeri.**

## UI

![Luar Kota](https://user-images.githubusercontent.com/42407562/92200459-1dc94b80-eea4-11ea-97bb-6d7450706d59.png)

link prototype ; https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=-2995%2C-6884%2C0.23642143607139587&scaling=min-zoom

## AC
- [x] Responsive

#### 1. Page List Dari Luar Kota/Negeri

- [x] Menampilkan data dari luar kota/negeri, layout disamakan dengan desain
- [x] Order by tgl update desc
- [x] Terdapat pilih aksi (CTA); Edit Data & Hapus Data
- [x] Terdapat buttom Tambah data dari luar kota/negeri, **jika diklik** direct ke form input data dari luar kota/negeri 

#### 2. Page Form Input Data dari luar kota/negeri
- [x] Field inputan disamakan dengan desain
- [x] Bisa input data
- [x] Direct ke list dari luar kota/negeri, jika proses input berhasil

#### Page Form Edit Data dari luar kota/negeri
- [x] Field inputan disamakan dengan desain
- [x] Bisa edit data
- [x] Direct ke list dari luar kota/negeri, jika proses edit berhasil

## Browser
- [x] Mozilla

**Comment by firmanJS** [comment]
dokumentasi api ada di folder History Travel Postman @Arif9878
