### ISSUE TITLE
[List Kasus] CRUD Ke transmisi lokal

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#495]
## User Story
Sebagai user faskes/dinkes. Saya ingin melihat, menambah, mengubah ataupun menghapus data Ke transmisi lokal yang sudah saya input saat buat laporan kasus baru. **Maka dari itu perlu ada fitur CRUD Ke transmisi lokal.**

## UI

![List Kasus - Riwayat Area Transmisi Lokal](https://user-images.githubusercontent.com/42407562/92200504-3f2a3780-eea4-11ea-8631-8aabc33e2103.png)

link prototype ; https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=-2995%2C-6884%2C0.23642143607139587&scaling=min-zoom

## AC
- [x] Responsive

#### 1. Page List Ke transmisi lokal

- [x] Menampilkan data Ke transmisi lokal, layout disamakan dengan desain
- [x] Order by tgl update desc
- [x] Terdapat pilih aksi (CTA); Edit Data & Hapus Data
- [x] Terdapat buttom Tambah data Ke transmisi lokal, **jika diklik** direct ke form input data Ke transmisi lokal 

#### 2. Page Form Input Data Ke transmisi lokal
- [x] Field inputan disamakan dengan desain
- [x] Bisa input data
- [x] Direct ke list Ke transmisi lokal, jika proses input berhasil

#### Page Form Edit Data Ke transmisi lokal
- [x] Field inputan disamakan dengan desain
- [x] Bisa edit data
- [x] Direct ke list Ke transmisi lokal, jika proses edit berhasil

## Browser
- [x] Mozilla

**Comment by firmanJS** [comment]
dokumentasi api ada di folder Local Transmission Postman @Arif9878
