### ISSUE TITLE
[List Kasus] CRUD ke tempat publik

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#496]
## User Story
Sebagai user faskes/dinkes. Saya ingin melihat, menambah, mengubah ataupun menghapus data Ke tempat publik yang sudah saya input saat buat laporan kasus baru. **Maka dari itu perlu ada fitur CRUD Ke tempat publik.**

## UI

![List Kasus - Riwayat Tempat Publik](https://user-images.githubusercontent.com/42407562/92201267-4f431680-eea6-11ea-9763-6cd1cd82815e.png)

link prototype ; https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=-11233%2C-18969%2C0.6189496517181396&scaling=min-zoom

## AC
- [ ] Responsive

#### 1. Page List Ke tempat publik

- [ ] Menampilkan data Ke tempat publik, layout disamakan dengan desain
- [ ] Order by tgl update desc
- [ ] Terdapat pilih aksi (CTA); Edit Data & Hapus Data
- [ ] Terdapat buttom Tambah data Ke tempat publik, **jika diklik** direct ke form input data Ke tempat publik 

#### 2. Page Form Input Data Ke tempat publik
- [ ] Field inputan disamakan dengan desain
- [ ] Bisa input data
- [ ] Direct ke list Ke tempat publik, jika proses input berhasil

#### Page Form Edit Data Ke tempat publik
- [ ] Field inputan disamakan dengan desain
- [ ] Bisa edit data
- [ ] Direct ke list Ke tempat publik, jika proses edit berhasil

## Browser
- [ ] Mozilla

**Comment by firmanJS** [comment]
dokumentasi api ada di folder Public Place Postman @Arif9878
