### ISSUE TITLE
[List Kasus] CRUD Kontak Paparan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#498]
## User Story
Sebagai user faskes/dinkes. Saya ingin melihat, menambah, mengubah ataupun menghapus data kontak paparan yang sudah saya input saat buat laporan kasus baru. **Maka dari itu perlu ada fitur CRUD kontak paparan.**

## UI

![List Kasus - Riwayat Kontak Paparan](https://user-images.githubusercontent.com/42407562/92875067-d3f7dc80-f432-11ea-9632-ef276fb0064b.png)

link prototype ; https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=357%2C-1310%2C0.1340549886226654&scaling=min-zoom

## AC
- [ ] Responsive

#### 1. Page List kontak paparan

- [ ] Menampilkan data kontak paparan, layout disamakan dengan desain
- [ ] Order by tgl update desc
- [ ] Terdapat pilih aksi (CTA); Edit Data & Hapus Data
- [ ] Terdapat buttom Tambah data kontak paparan, **jika diklik** direct ke form input data kontak paparan 

#### 2. Page Form Input Data kontak paparan
- [ ] Field inputan disamakan dengan desain
- [ ] Bisa input data
- [ ] Direct ke list kontak paparan, jika proses input berhasil

#### Page Form Edit Data kontak paparan
- [ ] Field inputan disamakan dengan desain
- [ ] Bisa edit data
- [ ] Direct ke list kontak paparan, jika proses edit berhasil

## Browser
- [ ] Mozilla

**Comment by erlangganugraha** [comment]
![image](https://user-images.githubusercontent.com/11548871/92876753-a875f180-f434-11ea-87dd-166fc38bf8fb.png)

kang @ReksaMohammad @zidneeey  untuk case diluar jawa barat flow penginputan diformnya seperti apa ?
cc @firmanJS @sandisunandar99

**Comment by firmanJS** [comment]
@erlangganugraha @ReksaMohammad mau tanya dong bukan nya kemaren kolom untuk kontak paparan hanya cari nama kasus nya aja ya kolom lain nya di hilangkan ?

**Comment by zidneeey** [comment]
### **Flow Input Faktor Kontak/Paparan**
(note: detail form di bawah belum sesuai, sesuaikan dari figma WIP)
@erlangganugraha @ReksaMohammad @firmanJS @sandisunandar99 

<img width="1155" alt="Screen Shot 2020-09-11 at 14 58 57" src="https://user-images.githubusercontent.com/62755122/92888353-6dc58680-f43f-11ea-8068-6d33bf167d34.png">
<img width="1038" alt="Screen Shot 2020-09-11 at 15 00 49" src="https://user-images.githubusercontent.com/62755122/92888534-9cdbf800-f43f-11ea-96d8-193130bdf554.png">
<img width="1045" alt="Screen Shot 2020-09-11 at 14 59 18" src="https://user-images.githubusercontent.com/62755122/92888326-6900d280-f43f-11ea-8b3f-704d8e7e58a1.png">

**Comment by firmanJS** [comment]
@ReksaMohammad kalo desain udah beres mention nya mang

**Comment by ReksaMohammad** [comment]
> @ReksaMohammad kalo desain udah beres mention nya mang

masih nunggu review dari @zidneeey mang, wait wait

**Comment by firmanJS** [comment]
> > @ReksaMohammad kalo desain udah beres mention nya mang
> 
> masih nunggu review dari @zidneeey mang, wait wait

siap gasskeun nanti tag urang mang @ReksaMohammad

**Comment by ReksaMohammad** [comment]
> > > @ReksaMohammad kalo desain udah beres mention nya mang
> > 
> > 
> > masih nunggu review dari @zidneeey mang, wait wait
> 
> siap gasskeun nanti tag urang mang @ReksaMohammad

done mang @firmanJS, flownya ngikutin yg di whimsical nyak
