### ISSUE TITLE
[Revamp Kontak Erat] Mapping data antara 2 collection

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#499]
![Aplikasi Pelaporan Rev 5@2x](https://user-images.githubusercontent.com/11548871/92419414-8e6bb300-f197-11ea-888e-73b5ba7f69c0.png)

Migrasi data yang sudah sesuai struktur data + memiliki status sudah diwawancara
Skip data yang sudah ada dilist kasus (bisa dimatchingkan dgn NIK/No Telepon)
Skip data yang tidak memiliki district code karena tidak bisa generate id_case
Skip data yang status belum diwawancara karena belum dibuat laporannya

Eksekusinya :
Setelah Menu Kontak Erat dibagian sub menu buat laporan dihide
Buat laporan kasus pada group form kontak paparan sudah selesai
Pada list kasus, lihat kontak erat hanya read only (exclude tambah, edit, & hapus)

Result :
Terdata dilist kasus sebagai kriteria kontak erat
Export data yang diskip berbentuk excel
Menu kontak erat dibagian sub menu list identifikasi dihide

Task Front End :
[Menu Kontak Erat] ] Hide sub menu buat laporan dimenu kontak erat
[Sub Menu List Kasus] Hide pilih aksi + tombol tambah data kontak erat dilihat kontak erat

**Comment by khihadysucahyo** [comment]
@erlangganugraha @shintadewiaw 
**step migrasi data:**
1. old fitur kontak erat -> readonly
2. [Sambil menunggu fitur revamp] user bisa langsung membuat kasus kriteria kontak erat,
   dg catatan kasus sudah bisa menginputkan dengan memilih kontak primer(kasus terdaftar)
3. karena diinputkan langsung dari laporan kasus, mungkin akan dianggap is_reported=true
4. scheduling eksekusi migrasi malam hari

**setelah migrasi:**
1. data pada [aksi->lihat kontak erat], yg semula bersumber dari closecontact table,
   akan diambil dari data kasus ?status=closecontact&parent=this.case

**develop revamp kontak erat:**
1. Kebutuhan api:
1.1 aksi tambah kontek baru (dedicated api / versioning route)
1.2 Buat Laporan kontak erat baru (exisiting post cases API & additional payload)
1.3 list kontak erat pada menu buat laporan kontak erat (existing cases api, additional param)
1.4 List kasus (adding needed: additional param)

**Comment by khihadysucahyo** [comment]
![Screenshot from 2020-09-11 12-57-57](https://user-images.githubusercontent.com/31666194/92870860-7feaf900-f42e-11ea-921e-0ca32d050602.png)

@erlangganugraha @shintadewiaw btw nanya dong, berati data2 kasus dg kriteria kontak erat di production itu,
berarti ga ada yg punya parent kan ya? 

_** mau saya tandai nanti ketika migrasi, untuk data2 kasus kontak erat di prod itu emang ga ada parentnya_

**Comment by erlangganugraha** [comment]
betuuul nih ada yg punya parent, ada yang tidak punya @khihadysucahyo 
btw saya baru kepikiran yang dimigrasi itu yang sudah diwawancara ? kalo yang belum diwawancara perlu dimigrasi juga sepertinya tapi masih dalam status belum diwawancara

**Comment by khihadysucahyo** [comment]
@erlangganugraha bisa aja ikut di migrasi tapi tetap dengan catatan ini:
1. jika nik/hp terisi, maka akan dicek dulu di data kasus sudah ada/belum, jika ada akan di skip kan ya(?)
2. jika !(nik/hp) maka akan tetap dimigrasi

nah setelah di migrasi, 
untuk di _list kasus -> aksi lihat kontak erat_ ,
1. datanya tetap ambil ke tabel lama kah? , **(sementara, berbarengan dg crud revamp kontak erat)**
2. atau lngsng diubah ambil dari tbl kasus `(status=closecontact&parent=id) ` **(push prod tanpa nunggu revamp kontakerat)**

cc @shintadewiaw

**Comment by khihadysucahyo** [comment]
@erlangganugraha @shintadewiaw up
