### ISSUE TITLE
[Laporan PE] Value Kontak Paparan Tidak Masuk

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#503]
Menginputkan "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya" pada Kontak Paparan tetapi value yang masuk ke Faktor Riwayat Perjalanan
![image](https://user-images.githubusercontent.com/63390998/92200072-0e95ce00-eea3-11ea-9a67-ef950dc3c561.png)

Masuknya kesini
![RIWAYAT](https://user-images.githubusercontent.com/63390998/92200090-16557280-eea3-11ea-92aa-228776d2898f.png)

Seharusnya kesini bukan?
![image](https://user-images.githubusercontent.com/63390998/92200204-72b89200-eea3-11ea-8492-960d02c39fa6.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw bukannya bener ya wkkw

**Comment by khihadysucahyo** [comment]
> Masuknya kesini
> ![RIWAYAT](https://user-images.githubusercontent.com/63390998/92200090-16557280-eea3-11ea-92aa-228776d2898f.png)
> 
ini seinngatku rumusnya suspek / probable

**Comment by khihadysucahyo** [comment]
> ![image](https://user-images.githubusercontent.com/63390998/92200204-72b89200-eea3-11ea-8492-960d02c39fa6.png)

yang ini hanya yg konfirmasi

**Comment by shintadewiaw** [comment]
@khihadysucahyo eh wkwkwk, yaudah kalo gitu benerin valuenya aja mas

**Comment by khihadysucahyo** [comment]
@shintadewiaw @erlangganugraha

**Comment by shintadewiaw** [comment]
mangga pak bos @erlangganugraha

**Comment by khihadysucahyo** [comment]
@shintadewiaw eh tapi harusnya kecentag ya wkwk, itu centangnya ngebug berarti

**Comment by shintadewiaw** [comment]
> @shintadewiaw eh tapi harusnya kecentag ya wkwk, itu centangnya ngebug berarti

Nah iya value itu maksudnya wkwk

**Comment by khihadysucahyo** [comment]
@shintadewiaw kirain value ditabel kontaknya wkwk, okay deh

**Comment by shintadewiaw** [comment]
mas mas, kalo dari probable kuubah jadi konfirmasi dianya jadi gamasuk kemana mana
![image](https://user-images.githubusercontent.com/63390998/92231911-cba21d80-eed7-11ea-8778-f7be5c459fd4.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw di ui nya emang udah bisa edit kontak paparan? Kok aku nyari g ada ya kwkw

**Comment by khihadysucahyo** [comment]
@shintadewiaw yg diedit bukan kriteria si kasus "TEST KONTAK PRIMER PE" kan?

atau kontak primernya si kasus itu, yaitu si "HADI"?

**Comment by khihadysucahyo** [comment]
@shintadewiaw bareng2 kuy kita bedah wkwk

**Comment by shintadewiaw** [comment]
EH SALAH MALAH NGEDIT RIWAYATNYA WKWKWK

**Comment by khihadysucahyo** [comment]
@shintadewiaw btw kalo ngedit riwayat bisa aja data kontak primernya hilang, kalo dari request/ui di form inputnya belum ada ketika edit

**Comment by shintadewiaw** [comment]
@khihadysucahyo oh i see, yaudah kita menunggu formnya ada dulu baru ku test kaya tadi yaa, sipp selesai maaci mas, ku closed dulu

**Comment by khihadysucahyo** [comment]
> @khihadysucahyo oh i see, yaudah kita menunggu formnya ada dulu baru ku test kaya tadi yaa, sipp selesai maaci mas, ku closed dulu

@shintadewiaw wkwk sipsip 👌 
cara tes sementara mungkin bisa buat kasus baru terus2an satu2 tiap mau ngecek di kontak primer PE wkwkw

**Comment by shintadewiaw** [comment]
Iya itulah yang kulakuan selama ini oi🙃🙃🙃
