### ISSUE TITLE
[Kontak Erat] Error Ketika Buat Laporan

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#506]
Role: Faskes
Deskripsi: Ketika buat laporan kontak erat error (seperti di screenshot)

![image](https://user-images.githubusercontent.com/63390998/92230020-96480080-eed4-11ea-9a33-c94447a81b88.png)
![image](https://user-images.githubusercontent.com/63390998/92230031-9e07a500-eed4-11ea-8d16-ae47de9e64d8.png)

**Comment by khihadysucahyo** [comment]
@shintadewiaw kok undefined ya uri paramnya wkkw

**Comment by shintadewiaw** [comment]
@khihadysucahyo ulalaaa coba kita tanya bapak ini @Arif9878

**Comment by khihadysucahyo** [comment]
@shintadewiaw semua listnya error ketika mau buat laporan? Atau beberapa aja?
Terus kalo yg error ditutup/resfresh dicoba lg mau ga?

**Comment by shintadewiaw** [comment]
@khihadysucahyo semua mas aku cobain gabisaa, udah ku refresh, clear cache, logout

**Comment by shintadewiaw** [comment]
@khihadysucahyo cobain deh, login faskescipa, passwordnya kaya biasa

**Comment by khihadysucahyo** [comment]
@shintadewiaw btw ini kang sandi ada nambah gield activity_other , tapi di validasinya belum ditambahin
Otw ditambahkan

**Comment by khihadysucahyo** [comment]
> @shintadewiaw btw ini kang sandi ada nambah gield activity_other , tapi di validasinya belum ditambahin
> Otw ditambahkan

![image](https://user-images.githubusercontent.com/31666194/92233870-43be1280-eedb-11ea-884f-8628b04d625f.png)
https://github.com/jabardigitalservice/pikobar-pelaporan-backend/commit/b749dbfa669df2686eb89bce5c603324b1137938#diff-54b39f7bc352cc6bc5bfeda3db960228
