### ISSUE TITLE
[Revamp Kontak Erat] Page awal buat laporan kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#532]
## AC
- [ ] Dibuat responsive
- [ ] Terdapat button Tambah Kasus Baru, direct ke page buat laporan kasus baru
- [ ] Terdapat pencarian by nama pasien
- [ ] Terdapat list data kontak erat yang belum diwawancara
- [ ] Terdapat button buat laporan disetiap list data pasien
- [ ] List data order by tgl updated DESC
- [ ] List data by default 100 rows

## Browser

- [ ] Mozilla Firefox

**Comment by khihadysucahyo** [comment]
## [API] list of cases that haven't been interviewed

`GET: {host}/api/cases`

```
params: {
  is_reported: false,
  search: { $or:  [name/nik/idcase/phone] }
}
```

**Comment by khihadysucahyo** [comment]
## [API] action create reports

`PUT: {{host}}/api/cases/:id/closecontact`

```
payload:
{
   ...casePayload,
   is_reported: true
}
```
