### ISSUE TITLE
[Revamp Kontak Erat] Buat laporan kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#534]
## UI
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5188%3A21103

### Page Data Pasien

- [ ] Dibuat responsive

### Page Kasus Keterkaitan

- [ ] Dibuat responsive
- [ ] Asal daerah by deault Jawa Barat
- [x] Terdapat pencarian Nama / NIK / Telp
- [ ] NIK, Nama, Kriteria dibuat mandatory
- [ ] Bisa mendata > 1 kontak keterkaitan
- [ ] Bisa hapus data

### UX

- [x] 1. Jika asal daerah Jawa Barat & hasil pencarian ditemukan, maka; Autofill & Disabled Edit utk identitas pasien, sbb;
NIK, Nama, Kriteria, No Telepon, Tanggal Lahir, Jenis Kelamin, Pekerjaan, Alamat

- [ ] 2. Jika asal daerah jawa barat & hasil tidak ditemukan, maka; Tidak auto fill & input manual dengan kriteria hanya bisa memilih kontak erat

- [ ] 3. Jika asal daerah diluar jawa barat & hasil pencarian ditemukan, maka; Autofill & Disabled Edit utk identitas pasien, sbb;
NIK, Nama, Kriteria, No Telepon, Tanggal Lahir, Jenis Kelamin, Pekerjaan, Alamat

- [ ] 4. Jika asal daerah luar jawa barat & hasil tidak ditemukan, maka; Tidak auto fill & input manual dengan kriteria bebas pilih

**Comment by khihadysucahyo** [comment]
## [API] Insert multiple records (based on latest wip ui prototype)

`POST: {host}/api/cases/:id/closecontact`**
```
/**
 * rules: [
 *   id_case: "optional (fill in if case already exists)"
 * ]
 **/

payload:
[
    {
        "id_case": null,
        "status": "CLOSECONTACT",
        "name": "tes 3",
        "nik": "32241241241224",
        "phone_number": "012912831823",
        "birth_date": "2020-08-20",
        "occupation": "apa aja",
        "gender": "L",
        "address_street": "Arcamanik",
        "address_district_code": "32.73",
        "address_district_name": "KOTA BANDUNG",
        "address_subdistrict_code": "32.73.01",
        "address_subdistrict_name": "Jl Gg Bangbayang",
        "address_village_code": "32.73.01.02",
        "address_village_name": "Jl Gg Bangbayangs",
        "rt": "12",
        "rw": "20",
        "relation": null,
        "relation_others": null,
        "activity": [],
        "activity_others": null,
        "first_contact_date": null,
        "last_contact_date": null
    }
]
```

**Comment by khihadysucahyo** [comment]
## [API] Delete closecontact case (based on latest wip ui prototype)

`DELETE: {host}/api/cases/:id/closecontact/:contactCaseId`**
```

available flags:
- id_case_registrant
- is_access_granted

exception response:
{
    "status": 422,
    "message": "this current active case haven't an access to this related case"
}
```

**Comment by khihadysucahyo** [comment]
## Pencarian nama, bisa pake existing API
`{{host}}/api/search?name=`

**Comment by khihadysucahyo** [comment]
@erlangganugraha punten kang minta tolong di share dong untuk kodefikasi id kasus luar jabar, yg pernah didiskusikan bareng kang @firmanJS

**Comment by khihadysucahyo** [comment]
> @erlangganugraha punten kang minta tolong di share dong untuk kodefikasi id kasus luar jabar, yg pernah didiskusikan bareng kang @firmanJS

@erlangganugraha up

**Comment by erlangganugraha** [comment]
![Aplikasi Pelaporan Rev 5](https://user-images.githubusercontent.com/11548871/94420394-4d6f2900-01ae-11eb-9232-6ea9d7433b20.png)

**Comment by erlangganugraha** [comment]
cc @khihadysucahyo
