### ISSUE TITLE
[Dashboard] Bug Rekap Demografis

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#603]
### How to Reproduce Bug
Login sebagai dinkeskotabogor
**Actual Result:**
1. Menginputkan data pada input kasus
2. Mengecek apakah data pada rekap demografis sudah sesuai dengan data yang di inputkan
3. Data belum sesuai dengan data yang telah di inputkan

**Expected Result:**
1. Menginputkan data pada input kasus
2. Mengecek apakah data pada rekap demografis sudah sesuai dengan data yang di inputkan
3. Data sesuai dengan data yang telah di inputkan

**Feedback**
- [x] Value umur tidak masuk pada kolom Rekap Demografis
- [x] Jumlah pada WNA-WNI belum sesuai, di data hanya 1 WNA tetapi di kolom WNI juga terhitung 1
- [x] Jumlah pada Laki-Laki & Perempuan belum sesuai, di data hanya 1 Laki - Laki tetapi di Perempuan juga terhitung 1

**Lampiran**
1. Rekap Data (dinkeskotabogor)

DATA KONTAK ERAT
Duma: Bogor Selatan - Bojongkerta - Kontak Erat Discarded  - 90th 3bulan - L

DATA KONFIRMASI
Sanjo: Bogor Barat - Cilendek Barat - WNI - Konfirmasi Meninggal - 26th 7bulan - L
Mia: Bogor Tengah - Cibogor - WNA - Konfirmasi - 12th 3bulan - P

DATA PROBABEL
Aminah: Bogor Timur - Katulampa - WNI - Probabel - Selesai isolasi/sembuh 31th 1bulan - L

DATA SUSPEK
Maudi Ayunda: Bogor Barat - Bubulak - WNI - Suspek - Discarded - 100th 0bulan - P

2. Screenshot Rekap Demografis
![image](https://user-images.githubusercontent.com/63390998/96968033-92327980-153a-11eb-8fc7-144f7509a82e.png)

**Comment by shintadewiaw** [comment]
mas @rafidrbbn minta link figma untuk design dashboard dong

**Comment by shintadewiaw** [comment]
mas @firmanJS yang ini masih belum sesuai, dia datanya kaya double double gitu mas, misal data aslinya laki laki, nah di tabelnya perempuan juga kehitung

![image](https://user-images.githubusercontent.com/63390998/97163081-ac768c80-17b2-11eb-8dd1-a130d3f47157.png)

![image](https://user-images.githubusercontent.com/63390998/97163190-d334c300-17b2-11eb-844d-1665ff3d87d1.png)

**Comment by firmanJS** [comment]
Hemm besok sambil share screen aja deh di msteam ya @shintadewiaw

**Comment by rafidrbbn** [comment]
> mas @rafidrbbn minta link figma untuk design dashboard dong

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5188%3A18866&viewport=541%2C-30%2C0.15992286801338196&scaling=min-zoom

ini teh
