### ISSUE TITLE
Tambahan cetak laporan PE

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#612]
## List revisi

- [ ] Status pasien terakhir sebaiknya tercheklist berdasarkan kondisi pasien terakhir, contoh atas nama pasien sakti perdana

Detail ;
![Screenshot_2020-11-02 pelaporan-covid19(2)](https://user-images.githubusercontent.com/11548871/97841068-b1d65880-1d17-11eb-9d92-712227860e67.png)
![Screenshot_2020-11-02 Laporan PE - covid-1016200003689 pdf](https://user-images.githubusercontent.com/11548871/97841097-ba2e9380-1d17-11eb-9f1f-9aa96b29baed.png)

- [x] Title "Lampiran 6. Formulir Penyelidikan Epidemiologi Coronavirus Disease (COVID-19)" sebaiknya dihilangkan saja

**Comment by khihadysucahyo** [comment]
@erlangganugraha itu ga terchecklist karena "Masih Karantina" ga ada di FORM PE

**Comment by khihadysucahyo** [comment]
@erlangganugraha yg di FORM PE hanya ada [Sembuh, Masih Sakit, Mennggal]

cc @shintadewiaw

**Comment by khihadysucahyo** [comment]
@erlangganugraha ditambahin opsi checklistnya atau langsung sama dengan veluenya aja ya?
misal 
- status pasien terakhir: **Masih Dikarantina**

**Comment by khihadysucahyo** [comment]
> @erlangganugraha ditambahin opsi checklistnya atau langsung sama dengan veluenya aja ya?
> misal
> 
> * status pasien terakhir: **Masih Dikarantina**

up @erlangganugraha

**Comment by erlangganugraha** [comment]
> 
> 
> @erlangganugraha ditambahin opsi checklistnya atau langsung sama dengan veluenya aja ya?
> misal
> 
>     * status pasien terakhir: **Masih Dikarantina**

tambahkan valuenya aja mas, tdk perlu pake checklist
