### ISSUE TITLE
Export Excel Rekap Kontak Erat, Suspek, Probable & Terkonfirmasi pada dashboard kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#613]
## User story
Sebagai user, saya ingin export rekap kontak erat & suspek kedalam format excel untuk laporan harian ke stakeholder

## AC

- [x] Format Data yang diexport disamakan dengan table Rekap Kontak Erat, Suspek, Probable & Terkonfirmasi yang ada didashboard
- [x] Jika difilter, maka data yang diexport berdasarkan data yang difilter
- [ ] File name yang diexport : Rekap Data Kriteria+ Nama Tab filter + User login + tanggal export, contoh : "Rekap Data Terkonfirmasi Dinkes Kota Bandung - 02_11_2020 23 45 WIB"

**Comment by firmanJS** [comment]
@Arif9878 

`api {{host}}/api/dashboard/v2/export-criteria?criteria=CONFIRMATION`

**Comment by shintadewiaw** [comment]
mas @firmanJS disini tambahin kriteria juga ya
![image](https://user-images.githubusercontent.com/63390998/98327617-88bf0c00-2026-11eb-9df6-c90176a135ee.png)

**Comment by shintadewiaw** [comment]
ini butuh parameter juga berarti ya mas dari FE? @firmanJS

**Comment by firmanJS** [comment]
iya betul @shintadewiaw

**Comment by shintadewiaw** [comment]
@Arif9878 mas minta tolong sekalian ini ya

**Comment by firmanJS** [comment]
udah beres shin test coba @shintadewiaw

**Comment by shintadewiaw** [comment]
mas @firmanJS baru ngeh penamaan filenya masih salah seharusnya gini:
"Rekap Data Terkonfirmasi Dinkes Kota Bandung - 02_11_2020 23 45 WIB"

yang sekarang gini:
![image](https://user-images.githubusercontent.com/63390998/98504948-bc01d500-228a-11eb-90e8-978641a31398.png)

yang demografis sekalian ya mas, cardnya udah ku close wkwkwk

**Comment by shintadewiaw** [comment]
Rekap Data Demografis + Nama Tab filter + User login + tanggal export, contoh : "Rekap Data Demogafis Dinkes Kota Bandung - 02_11_2020 23 45 WIB"

**Comment by shintadewiaw** [comment]
naha belum ada perubahan ya mas? @firmanJS 
![image](https://user-images.githubusercontent.com/63390998/98512551-0c802f00-2299-11eb-8c10-cb12661bcc15.png)

**Comment by firmanJS** [comment]
> naha belum ada perubahan ya mas? @firmanJS
> ![image](https://user-images.githubusercontent.com/63390998/98512551-0c802f00-2299-11eb-8c10-cb12661bcc15.png)

@shintadewiaw wait di cek lagi

**Comment by firmanJS** [comment]
@shintadewiaw api udah up kalo masih error coba colek arif kasih tau ada perubahan nama nya

**Comment by shintadewiaw** [comment]
mas belum juga ni 
![image](https://user-images.githubusercontent.com/63390998/98641034-b1644000-235d-11eb-8452-bd3cbb62bb55.png)

minta tolong ya mas arip @Arif9878
