### ISSUE TITLE
Improvement fitur import data kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#623]
## Bakground
Jumlah keterisian data semakin hari terus menurun, untuk meningkatkan keterisian data selain penambahan jumlah resource penginput data. Diperlukan juga fitur input data dalam jumlah banyak dalam 1x proses. Maka dari itu perlu dibuatkan fitur import.

Fitur import sudah ada disistem pelaporan, tetapi perlu kita sesuaikan dengan form input revisi 5

## Syarat Ketentuan Menggunakan Fitur Import

1. NIK wajib mandatory
2. Pola transmisi wajib diisi jika pasien berkriteria konfirmasi
3. Max jumlah data <200
4. Import diperuntukan untuk data baru, data yang sudah terinput sebaiknya diupdate melalui aplikasi sesuai dgn kondisi sekarang
5. Ideal import dilakukan jam 07:00 - 08:00 (pagi) & jam 15:00 - 19:00 (senja menuju malam)
6. Fitur import diperuntukkan role dinkes kota/kab
7. Untuk proses pelacakan kontak sebaiknya tidak menggunakan fitur import

## Template import
link :

## AC

- [x] Terdapat pesan error, jika proses import dijalankan mengalami error
- [x] Maximal rows <200, jika melebihi terdapat alert (pesan)
- [x] Pada form import, terdapat content Syarat & Ketentuan
- [x] Pada form import, terdapat tata cara penggunaan import
- [x] Pada form import, terdapat template import yang bisa didownload
- [x] Jika NIK ada yang kosong, maka data tidak masuk + terdapat pesan, contoh "NIK dirows 99 kosong, harap diisi terlebih dahulu"
- [x] Ketika data mandatory kosong, maka data tidak masuk + terdapat pesan error wajib diisi
- [x] Pada kolom gejala, jika diisi = " ", "-", "Tidak". Maka untuk field terdapat gejala terisi "Tidak"
- [x] Pada kolom kondisi penyerta, jika diisi = " ", "-", "Tidak". Maka untuk field terdapat gejala terisi "Tidak"
- [x] Pada kolom etiologi lainnya terisi, maka jawaban yang menimbulkan etiologi "Ya"
- [x] Data Pola transmisi wajib diisi jika pasien berkriteria konfirmasi
- [x] Jika proses import berhasil, maka data ditampilkan pada list kasus

> NB ; Untuk testing fitur import sebaiknya dilakukan full skenario

**Comment by erlangganugraha** [comment]
> 
> 
> @erlangganugraha @shintadewiaw yang ini boleh minta tolong dipindah ke card backend, biar ke linked pull requestnya.

done

**Comment by shintadewiaw** [comment]
validasi jika data lebih dari 200
![image](https://user-images.githubusercontent.com/63390998/98765535-ef6e6c00-2410-11eb-8473-29e61afa6b87.png)

@khihadysucahyo @arif890

**Comment by shintadewiaw** [comment]
error ketika menginputkan data tidak lengkap
![image](https://user-images.githubusercontent.com/63390998/98793907-12157a80-243b-11eb-9fa5-25a717ed5ea8.png)

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/98893298-bf889c80-24d4-11eb-911d-c99ec5ea23ec.png)


- [ ] NIK kosong tetapi pesan error duplikasi

- [ ] Ketika import menulis tanggal lahir 21 tetapi di aplikasi menjadi 22 (kalkulasi 

- [ ] Ketika import menulis tanggal gejala 20 tetapi di aplikasi menjadi 22

- [ ] Panah Hasil Pemeriksaan Tidak Bisa di Klik ---> Ini ke siapa ya(?)

- [ ] Saat import menulis gejala demam, tetapi di aplikasi tidak terchecklist (masuk pada gejala lainnya)

- [ ] Value pemeriksaan fisik yang masuk hanya Suhu

- [ ] Faktor Paparan - Input Ya pada "Apakah pasien termasuk cluster ISPA berat?" value yang masuk Tidak

- [ ] Faktor Paparan - Input Ya pada "Apakah pasien memiliki hewan peliharaan?" value yang masuk Tidak

- [ ] Faktor Paparan - Input "Kacamata Pelindung Google" pada Alat pelindung yang digunakan, value tidak masuk

- [ ]  Faktor Paparan - Input Ya pada "Apakah melakukan prosedur yang menimbulkan erosol?" value yang masuk Tidak

FE
- [ ] Pesan error sebaiknya dibuat (-) kebawah satu satu




*Sementara ini dulu bakal kutambah kalau ada lagi

**Comment by khihadysucahyo** [comment]
@shintadewiaw Kacamata Pelindung **Goggle**

**Comment by khihadysucahyo** [comment]
@shintadewiaw Value pemeriksaan fisik yang masuk hanya Suhu , data sudah benar. ini di frontendnya value selain suhu dibaca string spertinya @Arif9878 

@shintadewiaw kalo mau nyoba buat aja laporan kasus biasa lewat app -> terus refresh pastikan untuk ga ngecache->terus cek field pemeriksaan

**Comment by shintadewiaw** [comment]
@khihadysucahyo iya kemaren nyoba di appnya emang muncul semua mas

**Comment by shintadewiaw** [comment]
Panah Hasil Pemeriksaan Tidak Bisa di Klik ---> Ini ke siapa ya(?)

ini ga ada hubungannya sama development bukan? @khihadysucahyo
