### ISSUE TITLE
Tambah data master rumah sakit dan lab

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#677]
1. Dipurwakarta ada 2 tempat pusat isolasi baru untuk pasien, maka diaplikasi pelaporan perlu ditambahkan
2. Kab garut mempunyai lab Lab RSUD. dr. Slamet Garut

## Acceptance criteria
- [x] Menambah tempat rumah sakit darurat baru sbb ;
1. Hotel Aruni Purwakarta
Alamat: Jl. Veteran No.13, Mulyamekar, Kec. Babakancikao, Kabupaten Purwakarta, Jawa Barat 41151
Telepon: 0812-9369-2222

2. Prime Plaza Hotel Purwakarta
Alamat: Jalan Kota Bukit Indah Raya No.Blok L, Cinangka, Kec. Bungursari, Kabupaten Purwakarta, Jawa Barat 41181
Telepon: (0264) 351888

- [x] Menambah data lab baru sbb ;
Lab RSUD. dr. Slamet Garut
Alamat: Jl. Rsu DR. Slamet No.12, Sukakarya, Kec. Tarogong Kidul, Kabupaten Garut, Jawa Barat 44151
Jam buka: Open 24 hours
Telepon: (0262) 232720
Provinsi: Jawa Barat

relate dengan https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/issues/816

**Comment by shintadewiaw** [comment]
jadi ada error mas @sandisunandar99 
![image](https://user-images.githubusercontent.com/63390998/100406379-3ce90b00-3098-11eb-82a9-727daf6bb9be.png)

**Comment by shintadewiaw** [comment]
https://github.com/jabardigitalservice/pikobar-pelaporan-backend/commit/5faffd1b432611f3524cb28f2d50b9beabf75b6b
@firmanJS

**Comment by sandisunandar99** [comment]
![image](https://user-imag@shintadewiaw thubusercontent.com/6767399/100411073-33b16b80-30a3-11eb-835e-588d7eb4d250.png)
@shin

**Comment by sandisunandar99** [comment]
oh @shintadewiaw  aku lupa ngasih tau ,, kemarin aku nambhain nya langsung di porduction
