### ISSUE TITLE
Pengaturan role superadmin

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#678]
#### Laporan Kasus

- [x] 1. Buat Laporan Kasus
- [x] 2. Verifikasi Kasus Baru
     - [x]     2.1 Proses Verifikasi Kasus
- [x] 3. List Kasus 
     - [x] 3.1 Lihat & Detail Kasus
     - [x] 3.2 Cetak Laporan PE
     - [x] 3.3 Hapus Kasus

**Comment by shintadewiaw** [comment]
btw mas @sandisunandar99 kalau nambah kasus di superadmin masuknya cuma di superadmin ajakan? ga ganggu user user lain?

**Comment by shintadewiaw** [comment]
@sandisunandar99 mas untuk cetak PE & hapus kasusnya belum ada
