### ISSUE TITLE
Tracking Issue Load Performance

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#685]
### Deskripsi:
Ada issue ketika melakukan verifikasi kasus (dinkes) loading lama sampai 1-2 menit, ketika perpindahan menu juga loading lama

### **Penyebab**
- Pada tanggal 24 november ada 2 dinkes yang memakai aplikasi pelaporan bersama sama sehingga CPU Usage mencapai 100%
- 

### **Solusi**
1. Dilakukan reconfig spesifikasi CPU server yang semula 2core menjadi 4core **[update]**
2. Dilakukan monitoring utilitas setelahnya **[update]**

### **Lampiran**
a. Data terakhir import user adalah tanggal 23 november
![image](https://user-images.githubusercontent.com/63390998/100195750-61bf7000-2f2a-11eb-97e3-436802ac81b7.png)

b. Total CPU Usage tanggal 24 november
![image](https://user-images.githubusercontent.com/63390998/100195931-a4814800-2f2a-11eb-94f9-65b65334b68c.png)

**Comment by sandisunandar99** [comment]
@shintadewiaw sementara task yg ini close dlu mungkin ya,, soalnya perlu analisis dan beberapa pertimbangan sebelum di eksekusi
