### ISSUE TITLE
Perubahan Label Informasi Klinis

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#686]
## User Story
Sebagai semua user, saya ingin mengetahui setiap summary informasi klinis

## Desain/Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5648%3A20757&viewport=734%2C197%2C0.057318221777677536&scaling=scale-down-width

## Acceptance Criteria
- [x] Tambahkan label perhitungan total informasi klinis

**Comment by khihadysucahyo** [comment]
@shintadewiaw ini jadi tetap ditambahkan kah sesauai desain? atau mengacu ke AC sebelumnya di card ini #664

**Comment by shintadewiaw** [comment]
nah iya jadi gimana er? di FE udah dibuatin, tinggal fungsi di BEnya @erlangganugraha

**Comment by erlangganugraha** [comment]
ooh ini card yang berawal dari inisiatif kang rafid yak wkwkwk, sebelumnya maafkan guys karena miss comss ini tuh.
Gow saja tanggung guys @shintadewiaw @khihadysucahyo

**Comment by khihadysucahyo** [comment]
@Arif9878
