### ISSUE TITLE
[Dashboard] API Diagram Angka Harian & Kumulatif dari Kriteria/Status

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#69]
## User Story
Sebagai dinkes saya ingin melihat statistik baik itu agregat hariannya ataupun kumulatif sehingga saya chart ini bisa dijadikan salah satu untuk membuat keputusan penanganan ataupun perencanaan tentang wabah ini 

## Mockup
![Screenshot_2020-04-29 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/80515992-01c11500-89ad-11ea-877f-b24c5a33f5b6.png)

![Screenshot_2020-04-29 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/80515986-fff75180-89ac-11ea-9d87-4ed52421f884.png)

#### 1. Angka Harian OTG
- [x] OTG dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Sumbu X (Tanggal) diset 14 hari
- [ ] Ketentuan perhitungan OTG
  - [x] 1. Proses = Count status OTG dengan tahapan proses
  - [x] 2. Selesai = Count status OTG dengan tahapan selesai
  - [ ] 3. Total = Count status OTG dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 2. Angka Harian ODP
- [x] ODP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Sumbu X (Tanggal) diset 14 hari
- [ ] Ketentuan perhitungan ODP
  - [x] 1. Proses = Count status ODP dengan tahapan proses
  - [x] 2. Selesai = Count status ODP dengan tahapan selesai
  - [ ] 3. Total = Count status ODP dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 3. Angka Harian PDP
- [x] PDP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Sumbu X (Tanggal) diset 14 hari
- [ ] Ketentuan perhitungan PDP
  - [x] 1. Proses = Count status PDP dengan tahapan proses
  - [x] 2. Selesai = Count status PDP dengan tahapan selesai
  - [ ] 3. Total = Count status PDP dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total
 
#### 4. Angka Harian Positif
- [x] Positif dengan legenda : Aktif, Sembuh & Meninggal, yang dimana sumbu X adalah tanggal & sumbu Y adalah angka
- [ ] Sumbu X (Tanggal) diset 14 hari
- [ ] Ketentuan perhitungan Positif
  - [x] 1. Aktif = Count status Positif dengan tahapan proses
  - [x] 2. Sembuh = Count status Positif yang hasilnya sembuh & tahapannya selesai
  - [x] 3. Meninggal = Count status Positif yang hasilnya meninggal & tahapannya selesai
  - [ ] 4. Total = Count status Positif dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Aktif, Total Sembuh, Meninggal, Grand Total

#### 1. Kumulatif OTG
- [x] OTG dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Ketentuan perhitungan OTG
  - [x] 1. Proses = Count status OTG dengan tahapan proses
  - [x] 2. Selesai = Count status OTG dengan tahapan selesai
  - [ ] 3. Total = Count status OTG dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 2. Kumulatif ODP
- [x] ODP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Ketentuan perhitungan ODP
  - [x] 1. Proses = Count status ODP dengan tahapan proses
  - [x] 2. Selesai = Count status ODP dengan tahapan selesai
  - [ ] 3. Total = Count status ODP dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 3. Kumulatif PDP
- [x] PDP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Ketentuan perhitungan PDP
  - [x] 1. Proses = Count status PDP dengan tahapan proses
  - [ ] 2. Selesai = Count status PDP dengan tahapan selesai
  - [ ] 3. Total = Count status PDP dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total
 
#### 4. Kumulatif Positif
- [x] Positif dengan legenda : Aktif, Sembuh & Meninggal, yang dimana sumbu X adalah tanggal & sumbu Y adalah angka
- [ ] Ketentuan perhitungan Positif
  - [ ] 1. Aktif = Count status Positif dengan tahapan proses
  - [ ] 2. Sembuh = Count status Positif yang hasilnya sembuh & tahapannya selesai
  - [ ] 3. Meninggal = Count status Positif yang hasilnya meninggal & tahapannya selesai
  - [ ] 4. Total = Count status Positif dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Aktif, Total Sembuh, Meninggal, Grand Total

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by alifianif** [comment]
1. Tanggal yang diset di sumbu X masih lebih dari 12 hari @firmanJS 
2. Untuk semua diagram, pop up yang muncul hanya jumlah Proses dan jumlah Selesai per-hari. Namun di AC terdapat grand total seperti di bawah ini:
![image](https://user-images.githubusercontent.com/17422311/81365660-f4292f00-9112-11ea-90c1-47213bf919ae.png)
Grand total tersebut ditampilkan juga di pop up atau bagaimana ya? @erlangganugraha

**Comment by firmanJS** [comment]
@alifianif cek slack juga ada pertanyaan dari @sandisunandar99

**Comment by sandisunandar99** [comment]
@alifianif coba yang ini, bandingkan lagi yang ada di desain dengan yang di tulis di ace nya sesuai ga,, soalnya menurut saya ada beberapa yang mungkin beririsan .. contoh seperti menghitung total kumulatif.. kan kumulatif itu menjumlahkan dari perharinya dan hari yg terakhir itu total dari jumlah sekian hari kebelakang,,

**Comment by alifianif** [comment]
Tadi pagi pas diskusi sepertinya untuk yang kumulatif sudah benar, kang. Tapi untuk diagram angka hariannya yang dibatasi menjadi 14 hari terbaru. dan untuk yang diagram harian itu dikerjainnya sama mas rendi ya, nanti AC-nya saya revisi @sandisunandar99 @rendiriz

**Comment by sandisunandar99** [comment]
oh oke2,,,

**Comment by sandisunandar99** [comment]
@alifianif yang ini card nya di pisah ga ya untuk backend dan fronend?? soalnya kan kalo secara di backend sudah done kan,,

**Comment by erlangganugraha** [comment]
saya pisah kang @sandisunandar99
