### ISSUE TITLE
Issue district name pada collection cases

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#694]
## Temuan anomali data
![WhatsApp Image 2020-11-26 at 8 33 13 PM](https://user-images.githubusercontent.com/11548871/100402662-66516900-308f-11eb-977e-d90622c2b5ba.jpeg)
![Screenshot_2020-11-27 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/100402664-67829600-308f-11eb-83f6-3cb4700fba1c.png)
![Screenshot_2020-11-27 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/100402666-681b2c80-308f-11eb-8312-ed74b7e40cd3.png)

**Comment by shintadewiaw** [comment]
@erlangganugraha
