### ISSUE TITLE
[List Kasus] Perhitungan Jumlah pada List Kasus dan Dashboard Tidak Sesuai

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#71]
**Status OTG**
![image](https://user-images.githubusercontent.com/63390998/80562232-539b8680-8a11-11ea-8625-5b814ce157fa.png)

![image](https://user-images.githubusercontent.com/63390998/80562263-63b36600-8a11-11ea-8a53-be3cb1395401.png)

**Status ODP**
![image](https://user-images.githubusercontent.com/63390998/80562389-ce64a180-8a11-11ea-98e5-3d50d7cb18d2.png)

![image](https://user-images.githubusercontent.com/63390998/80562405-da506380-8a11-11ea-8921-1f511a9f334b.png)

**Status PDP***
![image](https://user-images.githubusercontent.com/63390998/80562482-171c5a80-8a12-11ea-8fe6-7b1011c40da5.png)

![image](https://user-images.githubusercontent.com/63390998/80562624-6cf10280-8a12-11ea-9852-d163b6a22ed5.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878 kenapa ya kalo di filter kadang datanya ga ketemu? 

![image](https://user-images.githubusercontent.com/63390998/80676680-8319c400-8ae1-11ea-80a5-83de32304561.png)

**Comment by alifianif** [comment]
mau nambahin dong, itu jumlah OTG juga kayanya blm bener mas, di total ada 17 tp di list ada 18... @Arif9878 
![image](https://user-images.githubusercontent.com/17422311/80676937-0dfabe80-8ae2-11ea-92f6-0359d4c5766b.png)
![image](https://user-images.githubusercontent.com/17422311/80676979-2539ac00-8ae2-11ea-8e50-36dc8a25f2a8.png)

**Comment by firmanJS** [comment]
@alifianif udah done ya ini karena datanya status nya ada yang ngaco
