### ISSUE TITLE
Bug Improvement Rekap Demografis

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#710]
## User story
Sebagai dinkes kota/kab, saya ingin melihat rekap demografis berdasarkan sebaran umur

## Kebutuhan Rekap Demografis
![Screenshot_2020-11-22 (61) WhatsApp](https://user-images.githubusercontent.com/11548871/99906959-a1107580-2d0c-11eb-9378-b6d2f7cfec24.png)

## Acceptance Criteria
Tambahan sebaran umur sbb ; 

- [x] 40-49					
- [x] 50-59					
- [x] 60-69					
- [x] 70-79					
- [x] ≥ 80

**Comment by shintadewiaw** [comment]
@firmanJS waktu input semua umur yang di AC ga ada yang masuk mas, jangan lupa filternya by Kecamatan ya mas

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/100702613-945ae400-33d4-11eb-9d3c-a694f4cc5ad4.png)

![image](https://user-images.githubusercontent.com/63390998/100702804-ed2a7c80-33d4-11eb-955b-ac81261f3a15.png)


![image](https://user-images.githubusercontent.com/63390998/100702633-a0df3c80-33d4-11eb-904a-d1bead4996d2.png)

- [ ] Rekap Kontak Erat,Suspek,Probabel & Konfirmasi - Seharusnya kolom Kecamatan hanya memfilter Kecamatan saja tidak perlu menampilkan kelurahan


- [ ] Rekap Demografis - Seharusnya kolom Kecamatan hanya memfilter Kecamatan saja tidak perlu menampilkan kelurahan


@firmanJS mas tambahan yaa

**Comment by firmanJS** [comment]
udah bener juga ah @shintadewiaw btw ketika masuk halaman default filter terkonfirmasi ya kamu tadi masukin data status nya kontak erat cek lagi hehehe :runner:

**Comment by firmanJS** [comment]
Untuk labeling tinggal di frontend nya kaya nya cc @Arif9878

**Comment by shintadewiaw** [comment]
wkwkwkw wait kucek lagi @firmanJS

**Comment by Arif9878** [comment]
@shintadewiaw gimana sih sin yang ku tanya kan poin Seharusnya kolom Kecamatan hanya memfilter Kecamatan saja tidak perlu menampilkan kelurahan

**Comment by shintadewiaw** [comment]
@firmanJS jadi mas firrman, gambar yang ini yang ditampilkan di FE nya itu nyampur sama kelurahan, seharusnya yang di tampilkan adalah kecamatan aja
![image](https://user-images.githubusercontent.com/63390998/100702613-945ae400-33d4-11eb-9d3c-a694f4cc5ad4.png)

![image](https://user-images.githubusercontent.com/63390998/100702804-ed2a7c80-33d4-11eb-955b-ac81261f3a15.png)

ini contoh kecamatan kota bogor 
![image](https://user-images.githubusercontent.com/63390998/100702633-a0df3c80-33d4-11eb-904a-d1bead4996d2.png)

**Comment by firmanJS** [comment]
okay otw push @shintadewiaw

**Comment by firmanJS** [comment]
karena di data nya ada yang masuk ke kolom kecamatan rif @Arif9878

**Comment by firmanJS** [comment]
Gimana yang ini udah ok kah ? @shintadewiaw jika nemu bug anomali data lagi nanti kasih tau ya

**Comment by shintadewiaw** [comment]
@firmanJS pindah ke E2E aja mas

**Comment by firmanJS** [comment]
catatan hasil diskusi : 

1. api dan frontend tidak ada masalah 
1. penyebab data tidak sesuai karena ada anomali data

**Comment by shintadewiaw** [comment]
mas @firmanJS teryata yang masuk itu kecamatan saat dia inputnya diluar distict code author
![image](https://user-images.githubusercontent.com/63390998/100823920-b3ff1480-3487-11eb-83e8-9d86b5f6157c.png)

![image](https://user-images.githubusercontent.com/63390998/100823868-992ca000-3487-11eb-93c5-698f3fe0279e.png)

**Comment by shintadewiaw** [comment]
yaudah mas solusi sementara diubah kecamatan/keluarahn aja dulu redaksinya @firmanhxc 
cc: @Arif9878

**Comment by firmanhxc** [comment]
@shintadewiaw Apa ini mention2 sy, Bismillah dlu klo mau mulai kerja. 😉

**Comment by firmanJS** [comment]
> @shintadewiaw Apa ini mention2 sy, Bismillah dlu klo mau mulai kerja. 😉

Biasa kurang fokus om @firmanhxc wkwkw
