### ISSUE TITLE
Notifikasi laporan kasus baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#725]
## User Story
Sebagai dinkes kota/kab, saya ingin diberikan notifikasi laporan kasus baru dari faskes agar saya bisa tahu bahwa ada laporan baru dari faskes

## Desain/Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6534%3A24604&viewport=591%2C-31722%2C0.5571706891059875&scaling=scale-down-width

## Acceptance Criteria

- [x] 1. Notifikasi diterima ketika puskesmas mengajukan laporan baru
- [x] 2. List notifikasi limit 10 berdasarkan yang terbaru baik yang sudah dibaca atau belum dibaca
- [x] 3. Terdapat waktu/data notifikasi pada setiap list notifikasi
- [x] 4. Terdapat fixed button untuk melihat semua notifikasi
- [ ] 5. Terdapat kategori label notifikasi setiap list notifikasi
- [x] 6. Terdapat jumlah notifikasi pada icon lonceng berdasarkan paramater yang belum diklik/dibaca
- [x] 7. Terdapat jumlah notifikasi pada judul notifikasi berdasarkan paramater yang belum diklik/dibaca
- [x] 8. Terdapat dot label untuk menandakan notifikasi belum dibaca

## UX
1. Jika diklik item notifikasi laporan baru, maka sbb : 

- [x] 1.1 Tandai notifikasi bahwa sudah dibaca/dibuka
- [x] 1.2 Muncul pop up detail summary proses verifikasi

2. Jika data sudah diverifikasi, maka sbb :

- [ ] 2.1 Muncul pop up detail verifikasi dengan catatan dibawah data sudah terverifikasi
- [ ] 2.2 Button tolak & verifikasi kasus disabled

3. Jika data sudah ditolak, maka sbb :

- [ ] 3.1 Muncul pop up detail verifikasi dengan catatan dibawah data ditolak
- [ ] 3.2 Button tolak & verifikasi kasus disabled

NB : Untuk filter kategori, searching, pengaturan notifikasi, dan fungsi tandai sudah dibaca jangan dulu didevelop

**Comment by khihadysucahyo** [comment]
Ada 2 user dinkes di kota bandung = dinkeskotabandung1, dinkeskotabandung2
notifikasi akan ada di kedua user itu.

ownershipnya group atau per-user:

- [ ] misalnya jika dinkeskotabandung1 sudah membaca notifnya, ditandai bahwa dinkeskota1 saja yg "sudah baca"
- [ ] atau ownershipnya group "dinkes kota bandung" ,  jadi misal salah satu sudah baca, pada login dinkeskotabandung1 & dinkeskotabandung2 dianggap "sudah baca"

@erlangganugraha @shintadewiaw

**Comment by shintadewiaw** [comment]
biasanya sih kaya gini mas 

--> misalnya jika dinkeskotabandung1 sudah membaca notifnya, ditandai bahwa dinkeskota1 saja yg "sudah baca"
meskipun mereka satu kesatuan tapi kan loginnya masing masing, cmiiw

@khihadysucahyo @erlangganugraha

**Comment by khihadysucahyo** [comment]
@shintadewiaw sipsip berarti ownershipnya user ya, in progress juga aku bikin gini sih.
