### ISSUE TITLE
Notifikasi Kontak Erat Selesai Masa Karantina

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#727]
## User Story
Sebagai dinkes kota/kab dan faskes, saya ingin diberikan notifikasi pasien kontak erat yang selesai masa karantinanya, agar saya bisa segera mengupdate statusnya menjadi discarded

## Desain/Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6534%3A24604&viewport=591%2C-31722%2C0.5571706891059875&scaling=scale-down-width

## Acceptance Criteria
- [ ] Terdapat notifikasi kepada dinkes kota/kab atau faskes ketika kontak erat selesai masa karantina
- [ ] Selesai masa karantina terhitung sejak awal tanggal update status pasien dinyatakan sebagai **kontak erat - masa karantina**
- [x] Terdapat list notifikasi pada menu notifikasi
- [x] Terdapat jumlah notifikasi pada icon notif
- [x] Ketika diklik item pesan notifikasi, maka direct ke page detail pasien

**Comment by khihadysucahyo** [comment]
@erlangganugraha untuk data2 lama  yang sudah lewat 14 hari tetap di notif kah?,
