### ISSUE TITLE
Fitur Multiple Update Status Kontak Erat

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#728]
## User Story
Ketika ada penumuan kasus konfirmasi baru, maka dilakukan proses pelacakan kontak. Ketika proses pelacakan kontak, maka terdapat list kontak erat dengan pasien konfirmasi. Yang dimana kontak erat ini akan dipantau selama 14 Hari, biasanya orang-orang yang dipantau akan dimulai pemantauannya secara bersamaan, **otomatis ketika perubahan selesai masa karantinanya **(Discarded)** akan sama.** Oleh karena itu user ingin bisa mengupdate status menjadi discarded secara bersamaan, maka ;

Sebagai dinkes kota/kab dan faskes, saya ingin melakukan multiple update status kontak erat agar saya mudah untuk mengupdate statusnya dalam satu kali aksi.

## Desain/Prototype
![List Kasus - Checked](https://user-images.githubusercontent.com/42407562/101867118-0093cf80-3bad-11eb-91fc-1fef152ff03f.png)

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=229%2C-10997%2C0.3699679970741272&scaling=min-zoom

## Acceptance Criteria
- [ ] Terdapat tombol untuk mengaktifkan multiple update
- [ ] Terdapat filter untuk memilah data
- [ ] Terdapat checklist untuk memilih data yang akan diupdate statusnya
- [ ] Ketika list data kontak erat sudah terpilih, maka muncul pop up form multiple update status pasien
- [ ] User bisa memilih status pasien terakhir dan tanggal update status pasien terakhir
- [ ] Ketika proses multiple update status pasien berhasil, maka direct ke  menu list kasus

**Comment by Arif9878** [comment]
@firmanJS  apinya kurang field final_result kang
![Screen Shot 2020-12-15 at 15 10 28](https://user-images.githubusercontent.com/20775950/102188496-f0029280-3ee7-11eb-9297-d203c35bfe8b.png)
![Screen Shot 2020-12-15 at 15 10 15](https://user-images.githubusercontent.com/20775950/102188505-f264ec80-3ee7-11eb-8bd9-391d0e804174.png)

**Comment by shintadewiaw** [comment]
mas @firmanJS ketika sudah update status nanti ditambahkan di informasi klinis ya riwayat barunya
