### ISSUE TITLE
Improvement dashboard hasil test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#730]
## User Story
Sebagai dinkes kota/kab dan faskes, saya ingin memonitoring jumlah hasil test yang saya input. Selain itu agar saya tahu jumlah pasien yang dilakukan test berdasarkan sebaran kecamatan, sasaran, dan demografis

## Desain/Prototype
![Screenshot_2020-12-15 Figma(2)](https://user-images.githubusercontent.com/11548871/102185915-68675480-3ee4-11eb-8c8b-5b68cf8bdc31.png)
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6678%3A1107&viewport=229%2C-10997%2C0.3699679970741272&scaling=min-zoom

## Acceptance Criteria
- [x] Terdapat Perkembangan Jumlah Hasil Tes dalam bentuk chart
- [x] Chart Perkembangan Jumlah Hasil Tes bisa difilter berdasarkan metode pemeriksaan
---
- [x] Terdapat Jumlah Hasil Tes berdasarkan Wilayah per kecamatan dalam bentuk chart
- [x] Jika login sebagai dinkes prov/superadmin, maka chart Jumlah Hasil Tes berdasarkan Wilayah per kota/kab
---
- [x] Terdapat Jumlah Hasil Tes berdasarkan Sasaran  dalam bentuk chart
---
- [x] Terdapat Perbandingan Jenis Kelamin dalam bentuk pie chart
- [x] Pie chart Perbandingan Jenis Kelamin bisa difilter berdasarka hasil pemeriksaan
---
- [x] Terdapat Perbandingan Usia dan Jenis Kelamin  dalam bentuk chart
- [x] chart Perbandingan Jenis Kelamin bisa difilter berdasarka hasil pemeriksaan

**Comment by firmanJS** [comment]
up UI @erlangganugraha

**Comment by firmanJS** [comment]
![Screenshot from 2020-12-11 13-40-17](https://user-images.githubusercontent.com/5679509/101871627-7fd9d100-3bb6-11eb-8954-f619682f9943.png)

ini rumus persen nya ngitung dari apa ya ???
kalo bisa masukin aja rumusnya @erlangganugraha

**Comment by erlangganugraha** [comment]
![Screenshot_2020-12-15 Figma(1)](https://user-images.githubusercontent.com/11548871/102185766-263e1300-3ee4-11eb-82d9-e70f0ef9a788.png)
kang @firmanJS jadinya seperti ini chartnya, jadi ga ada parameter **target jumlah sasarannya**

**Comment by firmanJS** [comment]
@Arif9878 api di bagi menjadi beberapa endpoint

1. /api/dashboard/summary-input-test
2. /api/dashboard/summary-test-result
3. /api/dashboard/summary-test-result-gender
4. /api/dashboard/summary-test-result-age

**Comment by shintadewiaw** [comment]
@firmanJS mas ini yang pilihan Lab valuenya jadi error
![image](https://user-images.githubusercontent.com/63390998/104684367-769ad180-572b-11eb-9777-07bb115a37b1.png)

**Comment by firmanJS** [comment]
@shintadewiaw itu di frontend deh kaynaya soalnya api udah ada resultnya coba colek @Arif9878

**Comment by shintadewiaw** [comment]
- [ ] 1. Ketika filter data yang di input pada tahun 2020 tidak ada data yang muncul

![image](https://user-images.githubusercontent.com/63390998/104686031-fb3b1f00-572e-11eb-9383-4d9ffb90a3ba.png)
![image](https://user-images.githubusercontent.com/63390998/104686412-bc599900-572f-11eb-95f8-5972e33e3d29.png)

- [x] 2. Dikarenakan tanggal hanya 1 (tidak ada tanggal awal/akhir) sebaiknya di validasi bisa memilih tanggal awal terlebih dahulu kemudian akhir, jangan bisa mundur (contoh klik tanggal 5 kemudian tanggal 1)

![image](https://user-images.githubusercontent.com/63390998/104686795-85d04e00-5730-11eb-95eb-3556a8215a0c.png)


- [ ] 3. Penamaan Status pada kolom "Jumlah hasil tes berdasarkan sasaran" sebaiknya berbahasa indonesia

![image](https://user-images.githubusercontent.com/63390998/104686911-c203ae80-5730-11eb-934c-16d619e7452f.png)

- [ ] 4. Jumlah Hasil Tes berdasarkan Wilayah value seharusnya adalah kota/kab

![image](https://user-images.githubusercontent.com/63390998/104687063-0abb6780-5731-11eb-9cda-502841ee228a.png)

- [x] 5. Perhitungan total Laki - Laki dan Perempuan masih salah

![image](https://user-images.githubusercontent.com/63390998/104687267-7ac9ed80-5731-11eb-8346-dbc6fa02f043.png)
![image](https://user-images.githubusercontent.com/63390998/104687219-5e2db580-5731-11eb-8609-b88f201f1d93.png)

- [ ] 6. Perhitungan umur 0 belum masuk pada dashboard

![image](https://user-images.githubusercontent.com/63390998/104687402-b4025d80-5731-11eb-9e74-c67368b4351d.png)
![image](https://user-images.githubusercontent.com/63390998/104687377-a947c880-5731-11eb-9618-899feb1268de.png)

**Comment by shintadewiaw** [comment]
mas @firmanJS yang perhitungan umur 0-10 tahun masih salah
![image](https://user-images.githubusercontent.com/63390998/105007070-19c05380-5a6a-11eb-8716-23ed43f2121b.png)
![image](https://user-images.githubusercontent.com/63390998/105007236-4e340f80-5a6a-11eb-828b-98e49a0f3681.png)

**Comment by shintadewiaw** [comment]
mas @firmanJS waktu di filter jenis kelaminnya malah ga muncul

![image](https://user-images.githubusercontent.com/63390998/105140301-12f91580-5b2a-11eb-9074-8c48a5566bdb.png)

**Comment by shintadewiaw** [comment]
@firmanJS jenis kelamin belum ada perubahan
