### ISSUE TITLE
Fixing pengurutan data pasien pada list kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#750]
## Issue
Data pasien pada list kasus tidak berurutan berdasarkan tanggal update
![WhatsApp Image 2020-12-16 at 2 05 45 PM](https://user-images.githubusercontent.com/11548871/102317568-55b75300-3faa-11eb-84f8-ebf5f292d48e.jpeg)

## Acceptance Criteria

- [ ] Sebaiknya pengurutan data pasien berdasarkan tanggal update dari yang terbaru - terlama (Desc)

**Comment by firmanJS** [comment]
ini dari api udah betul cuma di fe kayanya harus ganti binding datanya

@Arif9878 untuk tanggal diperbarui terakhir ambil dari kolom updatedAt yang case ya

**Comment by firmanJS** [comment]
todo : perlu di cek ketika update riwayat kenapa tidak mengambil ke tangal yang akhir atau data riwayat terakhir

**Comment by firmanJS** [comment]
buat card baru aja @shintadewiaw bug ketika update riwayat klinis tanggal di list kasus tidak mengacu ke list riwayat baru
