### ISSUE TITLE
Update data suspek meninggal menjadi suspek discarded

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#753]
## User Story
Sebagai pemilik data, saya ingin merubah data suspek meninggal menjadi **suspek discarded** agar data saya sesuai dengan pedoman revisi 5 kemenkes

## Acceptance Criteria

- [x] Semua data suspek - meninggal diubah menjadi **suspek - discarded**

NB : Proses dilakukan setelah pilihan meninggal dibagian front end sudah dilakukan

**Comment by sandisunandar99** [comment]
tinggal running di prod yes :+1: 

cc : @shintadewiaw @erlangganugraha
