### ISSUE TITLE
Update data kontak erat meninggal menjadi kontak erat discarded

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#754]
## User Story
Sebagai pemilik data, saya ingin merubah data kontak erat meninggal menjadi **kontak erat discarded** agar data saya sesuai dengan pedoman revisi 5 kemenkes

## Acceptance Criteria
- [x] Semua data kontak erat - meninggal diubah menjadi **kontak erat - discarded**

NB : Proses dilakukan setelah pilihan meninggal dibagian front end sudah dilakukan

**Comment by sandisunandar99** [comment]
tinggal running di prod yes :+1: 

cc : @shintadewiaw @erlangganugraha
