### ISSUE TITLE
Bug Tanggal Update Terakhir pada List Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#758]
## Deskripsi
Tanggal Diperbaharui Terakhir mengacu ke tanggal riwayat yang paling lama (seharusnya riwayat terakhir diperbaharui)

### How to Reproduce Bug
1. Login sebagai dinkeskotabogor
2. Update riwayat klinis kasus dengan tanggal sekarang

**Actual Result:**
Tanggal diperbaharui terakhir pada list kasus mengacu ke riwayat yang terlama (bukan yang terbaru/sekarang)

**Expected Result:**
Tanggal diperbaharui terakhir mengacu pada riwayat terakhir yang di update

**Lampiran**
![image](https://user-images.githubusercontent.com/63390998/102448723-55c85900-4065-11eb-8c79-bcd1a8cfe82e.png)
![image](https://user-images.githubusercontent.com/63390998/102448773-742e5480-4065-11eb-8f48-715d490d118c.png)

**Comment by firmanJS** [comment]
@shintadewiaw ini kayanya udah deh dulu pernah di buat sama hadi

**Comment by khihadysucahyo** [comment]
bantu jawab, itu keliru di frontend binding datanya
![image](https://user-images.githubusercontent.com/31666194/102457246-feca8000-4074-11eb-9a49-c88dc7ddf36d.png)
