### ISSUE TITLE
[Dashboard] Chart berdasarkan umur perjenis kelamin

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#76]
### 1. Chart Usia Perjenis Kelamin
![Screenshot_2020-04-29 pelaporan-covid19(3)](https://user-images.githubusercontent.com/11548871/80525858-148f1600-89bc-11ea-9594-395bd37d89ad.png)

## Benchmark 
https://pikobar.jabarprov.go.id/data

### 2. Chart Usia Perjenis Kelamin
- [x] Terdapat jumlah total positif aktif per range usia disetiap masing-masing jenis kelamin
- [x] Terdapat pop up/title ketika dihover menampilkan title total positif aktif
- [x] Terdapat keterangan Legenda pria & wanita

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by alifianif** [comment]
Jumlahnya belum sesuai dengan jumlah positif aktif, masih berdasarkan total data di laporan kasus
@Arif9878 @firmanJS

**Comment by shintadewiaw** [comment]
mas @firmanJS Perhitungan umur tidak muncul/NaN (seperti di gambar)

![image](https://user-images.githubusercontent.com/63390998/80937909-254aec00-8e01-11ea-80e3-aa4c65b01ab3.png)
