### ISSUE TITLE
Penambahan tempat isolasi baru Dormitory Anggrek

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#776]
## Detail Profile
Dormitory Anggrek
Wanakerta, Kec. Bungursari, Kabupaten Purwakarta, Jawa Barat 41181
(0264) 351288
https://maps.app.goo.gl/Bfz1ghoXUqsqCaMq6

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/104261359-f4ef3d80-54b7-11eb-8e4c-c88c01dcf1f1.png)

**Comment by firmanJS** [comment]
ini udah beres nya kamari
