### ISSUE TITLE
[Export Kasus] Error export data utk dinkes kota tasik

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#78]

**Comment by azophy** [comment]
![2020-05-01-163616_1366x768_scrot](https://user-images.githubusercontent.com/2698551/81028936-73b5c480-8ead-11ea-8e6c-09c66fadf1b5.png)

Waktu aku coba tanggal 1 mei export kota tasik gak ada masalah
