### ISSUE TITLE
Penambahan data lab baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#781]
## User Story
User request untuk ditambahkan pilihan lab baru, karena user sering mengirim sample pada lab tersebut

## Lab Baru
1. BBTKLPP Jakarta
Alamat: Jl. Bambu Apus Raya No.6, RT.12/RW.3, Bambu Apus, Kec. Cipayung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13890
Jam buka: Closed ⋅ Opens 7:30AM
Telepon: (021) 8484912
Provinsi: Jakarta

2. Badan Penelitian dan Pengembangan Kesehatan Kemenkes RI
Alamat: Jl. Percetakan Negara No.29, RT.23/RW.7, Johar Baru, Kec. Johar Baru, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10560
Jam buka: Closed ⋅ Opens 8AM
Telepon: (021) 4261088
Provinsi: Jakarta

3. UPT Labkesda Kab. Bogor
Alamat: Jl. KSR Dadi Kusmayadi No.27B, Tengah, Cibinong, Bogor, Jawa Barat 16914
Jam buka: Closed ⋅ Opens 8AM
Telepon: (021) 8753269
Provinsi: Jawa Barat

## Acceptance Criteria
- [ ] Data lab baru berhasil ditambahkan pada pilihan lab didalam input pelaporan hasil test
- [ ] Data lab baru berhasil ditambahkan pada pilihan lab didalam input form pemeriksaan penunjang

**Comment by shintadewiaw** [comment]
@firmanJS mas firman langsung nambahin di prod atau di staging?

**Comment by firmanJS** [comment]
> @firmanJS mas firman langsung nambahin di prod atau di staging?

@shintadewiaw prod langsung
