### ISSUE TITLE
[Laporan Harian] API Tabel data agregat perkriteria setiap dinkes daerah

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#79]
## Benchmark Desain
![Screenshot_2020-05-01 Pikobar - Pusat Informasi dan Koordinasi COVID-19 Jawa Barat](https://user-images.githubusercontent.com/11548871/80810521-3a036600-8bee-11ea-8001-7537f16bfa0f.png)

![WhatsApp Image 2020-04-30 at 2 28 08 PM](https://user-images.githubusercontent.com/11548871/80810562-569f9e00-8bee-11ea-9685-4c05628f43d9.jpeg)

## Desain
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=249%3A3227

## Acceptance Criteria

- [ ] Terdapat title header "Tabel Covid-19 Disetiap Kabupaten Kota Jawa Barat"
- [ ] Data yang ditampilan didalam tabel, sbb :

1. Nama Dinkes Kab/Kota
2. Total OTG (Proses + Selesai)
3. Total ODP Proses (Proses + Selesai)
4. Total PDP Proses (Proses + Selesai)
5. Total Positif (Proses + Selesai)
6. Grand Total 

- [ ] Terdapat filter range tgl penginputan
- [ ] Terdapat Sorting berdasarkan kolom
- [ ] Terdapat button reset
- [ ] Terdapat button expor

**Comment by ReksaMohammad** [comment]
monggo di cek https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5%3A4423

**Comment by sandisunandar99** [comment]
ini positif nya positif apa?? diambil yang aktif aja atau semuanya aktif meninggal sembuh?
@erlangganugraha

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/81537714-d0c2e600-9397-11ea-9588-ca8ba326e343.png)

untuk yang ini sudah di buat se detail mungkin ya untuk output di backedn nya,, (y)

**Comment by sandisunandar99** [comment]
cc : @rendiriz
