### ISSUE TITLE
Anomali data konfirmasi - masih dikarantina

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#797]
## Anomali Data
![Screenshot_2021-01-21 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/105331443-0a760d00-5c06-11eb-9f79-dc2d57708923.png)
Terdapat data-data konfirmasi dengan status pasien terakhirnya **Masih Dikarantina**

## Ketentuan Kriteria & Status Pasien Terakhir
1. Kontak Erat, maka pilihan status pasien terakhir : (Masih Dikarantina, Discarded)
2. Suspek, maka pilihan status pasien terakhir : (Masih Sakit, Discarded)
3. Probable, maka pilihan status pasien terakhir : (Masih Sakit, Selesai Isolasi/Sembuh, Meninggal)
4. Konfirmasi, maka pilihan status pasien terakhir : (Masih Sakit, Selesai Isolasi/Sembuh, Meninggal)

## Acceptance Criteria

- [x] Untuk kriteria **konfirmasi** tidak ada status pasien terakhirnya **Masih Dikarantina**
- [x] Konversi data konfirmasi - masih dikarantina menjadi **konfirmasi - masih sakit**

**Comment by shintadewiaw** [comment]
er ini aku ngeceknya di data dinkes mana? @erlangganugraha
