### ISSUE TITLE
Perbaikan dashboard kasus baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#799]
## Issue
![Screenshot_2021-01-25 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/105656020-e5c6b180-5ef3-11eb-903b-49a24efafc1e.png)
List kecamatan yang ada pada table **Rekap Kontak Erat, Suspek, Probable & Terkonfirmasi** ataupun **Rekap Demografis** **tidak sesuai**. Karena tidak berdasarkan **kotanya**

## Acceptance Criteria
- [x] List kecamatan yang ada pada table **Rekap Kontak Erat, Suspek, Probable & Terkonfirmasi** ataupun **Rekap Demografis** sebaiknya berdasarkan **kotanya**
- [x] Jika ada data pasien diluar kecamatan tersebut dicantumkan pada list **Diluar kota/kab**

**Comment by shintadewiaw** [comment]
mas @firmanJS misal yang ditampilkan di munculin by kecamatan si author duluan bisa ga ya?hehe
![image](https://user-images.githubusercontent.com/63390998/107200208-fc0f5a00-6a29-11eb-978e-eab33fc9f81a.png)

**Comment by firmanJS** [comment]
bisa sih cuman perlu banyak loop takut nanti performa agak lambat, aku coba dulu :runner: @shintadewiaw

**Comment by firmanJS** [comment]
skip aja shin, kalo minor mah effort nya ke performa nanti @shintadewiaw

**Comment by shintadewiaw** [comment]
@firmanJS okaay mas, ku closed yak
