### ISSUE TITLE
[Export Kasus] Penambahan kolom kondisi penyerta

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#80]
## Acceptance Criteria :

- [x] Tambahan kolom kondisi penyerta dgn ketentuan format isian data disamakan dengan kolom gejala, Contoh : Diabetes, Penyakit jantung
- [x] Pemisah item kondisi penyerta menggunakan koma "," Contoh : Diabetes, Penyakit jantung
- [x] Jika hanya 1 item atau null item maka tidak ada koma ","
- [x] Posisi disetelah kolom gejala
- [x] Jika tidak ada isinya, kosongkan

> ## Notes
> Harap diperhatikan data lama yg belum mempunya isian data kondisi penyerta dimongo DB

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by alifianif** [comment]
![Untitled](https://user-images.githubusercontent.com/17422311/81150281-d3919580-8fa9-11ea-8831-363503f85360.png)
Isi kolom "Kondisi Penyerta" sama dengan kolom "Gejala" @firmanJS

**Comment by shintadewiaw** [comment]
mas @firmanJS error ini lagi waktu mau export

![image](https://user-images.githubusercontent.com/63390998/81367821-62bcbb80-9118-11ea-88df-a29da0484b98.png)

**Comment by firmanJS** [comment]
@shintadewiaw coba pake yang banjar

**Comment by shintadewiaw** [comment]
sama aja mas @firmanJS 

![image](https://user-images.githubusercontent.com/63390998/81386194-ce198400-913e-11ea-84c2-e0086825460c.png)

**Comment by firmanJS** [comment]
@shintadewiaw di coba lagi ya

**Comment by shintadewiaw** [comment]
**Waktu Input**
![kondisi penyerta](https://user-images.githubusercontent.com/63390998/81393830-2d7d9100-914b-11ea-86aa-ee048f6f2624.png)

**Setelah di Export** kondisi penyertanya ga masuk
![image](https://user-images.githubusercontent.com/63390998/81393928-59991200-914b-11ea-8eed-ae5780ad7b48.png)


@firmanJS

**Comment by firmanJS** [comment]
@shintadewiaw sip ini dari frontend nya ya ada yang salah pas insert

**Comment by shintadewiaw** [comment]
@Arif9878
