### ISSUE TITLE
Penyesuaian Grafik Dashboard Hasil Test

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#800]
### Deskripsi:
Sebaiknya default untuk menampilkan grafik dimulai tahun berjalan contoh sekarang 2021, agar tidak bercampur dengan data pada tahun 2020

![image](https://user-images.githubusercontent.com/63390998/105656931-f4ae6380-5ef5-11eb-8873-a900fc8c7d31.png)

**Comment by firmanJS** [comment]
ini masuk ke list improvement dulu aja deh karena lumayan panjang juga wkwk aku belum nemu query nya @shintadewiaw
