### ISSUE TITLE
Validasi fitur import data kasus untuk ketentuan kriteria

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#806]
## Issue
Data yang diimport terdapat anomali data karena belum ada validasi ketentuan kriteria, maka perlu ada validasi untuk menghandlenya

##  Ketentuan :
Jika Pilih kriteria **Konfirmasi** maka hanya bisa memilih :
1. Masih Sakit
2. Selesai Isolasi/Sembuh
3. Meninggal

Jika Pilih kriteria **Probable** maka hanya bisa memilih :
1. Masih Sakit
2. Selesai Isolasi/Sembuh
3. Meninggal

Jika Pilih kriteria **Kontak Erat** maka hanya bisa memilih :
1. Masih Dikarantina
2. Discarded

Jika Pilih kriteria **Suspek** maka hanya bisa memilih :
1. Masih Dikarantina
2. Discarded

## Acceptance Criteria
Jika ada data kriteria yang tidak sesuai dengan ketentuan, maka : 

- [x] 1. Show alert "Kriteria dengan **nama kriteria** dirows 99 tidak sesuai dengan ketentuan, harap diperbaiki terlebih dahulu sesuai ketentuan" *contoh
- [x] 2. Semua data belum diinput kedalam database, sebelum diperbaiki

**Comment by shintadewiaw** [comment]
mas @firmanJS yang ku highlight gausah ditampilkan ya
redaksinya begini aja mas: Status Pasien Terakhir 'Masih Dikarantia' tidak sesuai dengan ketentuan, harap diperbaiki sesuai dengan kententuan yang telah diberikan
 ![image](https://user-images.githubusercontent.com/63390998/106112171-8086f080-617f-11eb-87e2-562aec784ef6.png)
