### ISSUE TITLE
[Dashboard] Chart berdasarkan jenis kelamin

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#81]
### 1. Pie Chart Jenis kelamin
![Screenshot_2020-04-29 pelaporan-covid19(2)](https://user-images.githubusercontent.com/11548871/80525761-ef020c80-89bb-11ea-8943-016c6128a193.png)

link board: https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5%3A4423
link prototype: https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5%3A4427&viewport=-1082%2C-2343%2C1.025492787361145&scaling=min-zoom

## Benchmark 
https://pikobar.jabarprov.go.id/data

### 1. Chart Jenis Kelamin
- [ ] Terdapat jumlah persentase perbandingan jenis kelamin dgn ketentuan sbb :
- [ ] Yang dihitung hanya positif aktif (Status Positif - Tahapan Proses)
- [ ] Jumlah yang ditampilkan berupa persentase antara laki-laki dengan perempuan
- [ ] Terdapat pop up/title ketika dihover menampilkan title jenis kelamin + jumlah angka & persentasenya
- [ ] Terdapat keterangan Legenda pria & wanita

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by firmanJS** [comment]
ini card nya sama kaya yang ini `https://github.com/jabardigitalservice/pikobar-pelaporan-backend/issues/76` kan ya @alifianif @erlangganugraha

**Comment by erlangganugraha** [comment]
![image](https://user-images.githubusercontent.com/11548871/81036914-116bbc80-8ecb-11ea-9857-a564366730b7.png)
aku cek jumlahnya belum sesuai @shintadewiaw harusnya Perempuannya 1

**Comment by firmanJS** [comment]
@shintadewiaw @erlangganugraha ijin menambahkan ini sebenernya udah bener salah nya tuh dari datanya ajah

data stagging yang sesuai 
1. dinkes kota banjar
2. dinkes kota sukabumi
