### ISSUE TITLE
Pengiriman data kesehatan kedalam riwayat info klinis

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#812]
## User Story
Sebagai surveilans, saya ingin melihat lapor kesehatan yang sudah dilaporkan oleh pasien, agar saya bisa melihat perkembangan pasien selama masa karantina

## Alur Sistem Pengiriman Data Kesehatan
![Integrasi Lapor Mandiri X Pelaporan-Flow System Pengiriman Data](https://user-images.githubusercontent.com/11548871/105956346-40a20980-60aa-11eb-9f4a-deedfafc67ce.jpg)

## Acceptance Criteria

- [ ] Surveilans bisa melihat data yang dilaporkan oleh pasien diform riwayat info klinis

**Comment by erlangganugraha** [comment]
@shintadewiaw ini jangan diclose dlu, karena lagi die2e sama squad pikobar hehe

**Comment by shintadewiaw** [comment]
@sandisunandar99 ketika data NIK null dan nomor telpon diisi, informasi klinis tidak terupdate
