### ISSUE TITLE
[Export Kasus] Update data sumber pelaporan yg masih kosong

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#83]

**Comment by shintadewiaw** [comment]
mas @firmanJS waktu klik export langsung error

![image](https://user-images.githubusercontent.com/63390998/81037589-71fbf900-8ecd-11ea-856a-03e136f820e2.png)

**Comment by firmanJS** [comment]
@shintadewiaw coba di reload lagi di aku bisa

**Comment by shintadewiaw** [comment]
masih sama mas, coba login pake dinkeskotabanjar

**Comment by firmanJS** [comment]
di aku bisa @shintadewiaw coba pake incognito

**Comment by shintadewiaw** [comment]
wkwkkw aku pake incognito :( 
cobain lip @alifianif 

![image](https://user-images.githubusercontent.com/63390998/81041084-1afb2180-8ed7-11ea-83fa-4fc0589cb5c2.png)

**Comment by firmanJS** [comment]
@shintadewiaw aku paham aku nyobain nya di production kamu di stagging pantesan beda wkkwkw ini langsung test production ajah karena data nya yang salah

**Comment by shintadewiaw** [comment]
mas @firmanJS card ini teh maksutnya kolom ini kemaren ga muncul datanya mas?

![image](https://user-images.githubusercontent.com/63390998/81041764-d2446800-8ed8-11ea-8e38-0d5f540f9642.png)

**Comment by firmanJS** [comment]
@shintadewiaw iya ga muncul dalam artian bukan kosong datanya ya, tapi kolom nya di database ga ada

**Comment by shintadewiaw** [comment]
@firmanJS oh maksutnya kemaren kolom Sumber Lapor belum ditambahin di excel export? ambigu judul cardnya jadi bingung wkwk maap

**Comment by alifianif** [comment]
di aku masih gabisa mas @firmanJS , masalahnya sama kaya shinta. Muncul warning tapi kosong. Dan ini udah di clear cache 2 kali di incognito malah wkwk
![image](https://user-images.githubusercontent.com/17422311/81049981-77673c80-8ee9-11ea-9616-57976bee953d.png)

**Comment by shintadewiaw** [comment]
ni lip jawabannya @alifianif  ----> aku paham aku nyobain nya di production kamu di stagging pantesan beda wkkwkw ini langsung test production ajah karena data nya yang salah
