### ISSUE TITLE
[Dashboard] Hide "Undefined" pada Chart Usia

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#84]
![image](https://user-images.githubusercontent.com/63390998/81036026-b4223c00-8ec7-11ea-920f-bb7c0f7c665f.png)

**Comment by firmanJS** [comment]
@shintadewiaw ini login sebagai dinkes apa ?

**Comment by shintadewiaw** [comment]
@firmanJS dinkes banjar mas

**Comment by shintadewiaw** [comment]
eh naha ini di To do?wkwk

**Comment by firmanJS** [comment]
@shintadewiaw salah klik aku kepencet close issue wkwkwk

**Comment by firmanJS** [comment]
@shintadewiaw di refresh browser nya coba pake ctrl+f5 atau ctrl+shift+r udah done ini

**Comment by shintadewiaw** [comment]
@firmanJS sok pindahin ke E2E mas
