### ISSUE TITLE
Ekspolarasi skenario antrian fitur export data

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#842]
## User Story
Sebagai tim pikobar, saya ingin memperbaiki fitur export agar server tidak mengalami incident

## Acceptance Criteria

- [x] Ekspolarasi skenario antrian fitur export data

**Comment by firmanJS** [comment]
list api ada di folder queue cc @Arif9878

**Comment by shintadewiaw** [comment]
mas ada error @firmanJS 
![image](https://user-images.githubusercontent.com/63390998/114341248-820f6480-9b83-11eb-8ad5-f23ccee1f169.png)

**Comment by firmanJS** [comment]
> mas ada error @firmanJS
> ![image](https://user-images.githubusercontent.com/63390998/114341248-820f6480-9b83-11eb-8ad5-f23ccee1f169.png)

itu validasi yang kemarin shin jadi begini rule nya 

tiap dinkes email nya tidak boleh sama ketika akan membuat antrian jadi di validasi
ketika dikirim ulang atau resend hasil export itu email bisa sama tidak ada validasi

@shintadewiaw

**Comment by shintadewiaw** [comment]
@firmanJS oh mungkin redaksi errornya aja yang diperbaiki ya mas, redaksinya emang dari BE doang atau bisa dibuat dari FE juga?

**Comment by firmanJS** [comment]
> @firmanJS oh mungkin redaksi errornya aja yang diperbaiki ya mas, redaksinya emang dari BE doang atau bisa dibuat dari FE juga?

iya redaskinya aja paling boleh di BE juga bisa @shintadewiaw

**Comment by firmanJS** [comment]
tulis redaksinya mau jadi bagaimana sin @shintadewiaw

**Comment by shintadewiaw** [comment]
Email 'abc@gmail.com' telah digunakan, silahkan ubah alamat email anda!

gitu gimana mas?wkwk @firmanJS

**Comment by firmanJS** [comment]
> Email '[abc@gmail.com](mailto:abc@gmail.com)' telah digunakan, silahkan ubah alamat email anda!
> 
> gitu gimana mas?wkwk @firmanJS

Boleh, jangan ada perubahan lagi nanti redaksinya 😄

**Comment by shintadewiaw** [comment]
kok belum ada perubahan mas @firmanJS ?
![image](https://user-images.githubusercontent.com/63390998/114493223-5dc78c80-9c44-11eb-8ff6-24917a9b47c7.png)

**Comment by firmanJS** [comment]
belum di approve pull request nya :laughing:

**Comment by firmanJS** [comment]
sundul udah di approve @shintadewiaw

**Comment by shintadewiaw** [comment]
mas @firmanJS kan udah di validasi, tapi kok formnya ke next ke terimakasih ya? FE atau BE sih mas?
![image](https://user-images.githubusercontent.com/63390998/114648970-e0664f80-9d09-11eb-9a25-1fcaa298a338.png)

**Comment by firmanJS** [comment]
> mas @firmanJS kan udah di validasi, tapi kok formnya ke next ke terimakasih ya? FE atau BE sih mas?
> ![image](https://user-images.githubusercontent.com/63390998/114648970-e0664f80-9d09-11eb-9a25-1fcaa298a338.png)

tetap tenang @shintadewiaw  di FE itu colek @Arif9878
