### ISSUE TITLE
Enhancement filter list data kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#843]
## User Story
Sebagai user saya ingin memfilter data kasus dilist kasus yang saya inputkan (berdasarkan author), agar saya mengetahui berapa jumlah data yang sudah saya laporkan dan **kesesuaian jumlah data yang ada didashboard dan list kasus sama**

## Acceptance Criteria

- [ ] Data yang difilter berdasarkan author

**Comment by firmanJS** [comment]
ini jadinya gimana ?

dashboard mengikuti list kasus atau kebalikan nya mang @erlangganugraha ?
