### ISSUE TITLE
[Import Kasus] Pesan Error Import

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#85]
Pesan Validasi Error Import (Tanggal Lahir) diubah menjadi "Tanggal Lahir Harus Berisi Angka (tttt-bb-hh)"

![image](https://user-images.githubusercontent.com/63390998/81050685-9c0fe400-8eea-11ea-9874-720606c26799.png)

**Comment by firmanJS** [comment]
@shintadewiaw ini import kali ya bukan export ? :satisfied:

**Comment by shintadewiaw** [comment]
@firmanJS oiya maap oleng wkwkwk

**Comment by firmanJS** [comment]
@shintadewiaw ini export atau import ? kalo import yang ngerjain nya hadi ya :confused:
