### ISSUE TITLE
Kelola Pengguna - Perbaikan Unit Kerja

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#852]
### Deskripsi:
Perlu dicek terkait unit kerja pada kelola pengguna, karena hanya ada sedikit data pada dropdown unit kerja

**Comment by firmanJS** [comment]
@shintadewiaw cek cek

**Comment by shintadewiaw** [comment]
mas @firmanJS kok malah ga ada datanya ni
![AA](https://user-images.githubusercontent.com/63390998/109904988-ac424c80-7cd0-11eb-8df7-e80022202679.png)

**Comment by firmanJS** [comment]
> mas @firmanJS kok malah ga ada datanya ni
> ![AA](https://user-images.githubusercontent.com/63390998/109904988-ac424c80-7cd0-11eb-8df7-e80022202679.png)

coba konfirmasi ke @Arif9878 result api nya soalnya ada @shintadewiaw

**Comment by shintadewiaw** [comment]
mas aripppppp @arif9878

**Comment by Arif9878** [comment]
okey wait on chek @shintadewiaw @firmanJS

**Comment by Arif9878** [comment]
<img width="1440" alt="Screen Shot 2021-03-04 at 14 58 39" src="https://user-images.githubusercontent.com/20775950/109930598-669a7980-7cfa-11eb-8f6c-b83d53091bbf.png">
<img width="1440" alt="Screen Shot 2021-03-04 at 14 59 01" src="https://user-images.githubusercontent.com/20775950/109930611-6b5f2d80-7cfa-11eb-9f63-d42f58123441.png">
@firmanJS response BE unit kerja antara yang staging dengan production beda

**Comment by firmanJS** [comment]
sip @Arif9878 on the check
