### ISSUE TITLE
Penambahan data lab kota tasikmalaya

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#871]
## User Story
User request untuk ditambahkan pilihan lab baru, karena user sering mengirim sample pada lab tersebut

## Lab Baru
1. Labkesda Kota Tasikmalaya
Address: Panyingkiran, Indihiang, Tasikmalaya, West Java 46151
Phone: (0265) 345849
Province: West Java

## Acceptance Criteria
- [ ] Data lab baru berhasil ditambahkan pada pilihan lab didalam input pelaporan hasil test
- [x] Data lab baru berhasil ditambahkan pada pilihan lab didalam input form pemeriksaan penunjang

**Comment by firmanJS** [comment]
@shintadewiaw mention kalo udah ok biar nanti segera di up :rocket:
