### ISSUE TITLE
Input Hasil Test - Bug Konversi Umur

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#882]
### How to Reproduce Bug
Login sebagai dinkeskotabogor (staging)
Input kasus dengan nama lita, umur 80 tahun 5 bulan, klik save
Input hasil test memasukkan nama lita (umur di konversi menjadi 89,42) klik save
Buka menu dashboard hasil test

**Actual Result:**
Muncul toast error

**Lampiran:**
![image](https://user-images.githubusercontent.com/63390998/111760429-47dadc00-88d1-11eb-9613-2950b5df438f.png)
![image](https://user-images.githubusercontent.com/63390998/111598660-092a2080-8802-11eb-82a6-4f8b115472ed.png)

**Comment by firmanJS** [comment]
@shintadewiaw gas check shin
