### ISSUE TITLE
Bug Perhitungan Data Lokasi Sebaran

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-backend#917]
### **How to Reproduce Bug:**
Server: Staging
Akses: kota bogor

**Actual Result:**
- Data yang tampil di lokasi sebaran hanya kasus konfirmasi dan suspek
- Jika dihitung sesuai dengan author data sebagai berikut:
a. Suspek: 1 pasien✅
b. Konfirmasi: 5 pasien (yang muncul di lokasi sebaran hanya 4)
c. Kontak erat: 3 pasien (tidak muncul sama sekali)
d. Probable: 2 pasien (tidak muncul sama sekali)

**Expected Result**
Jumlah data pada lokasi sebaran (by author kota/kab) seharusnya muncul sebanyak jumlah data pada list kasus  (by author kota/kab)

**Lampiran**
Jumlah data probable pada list kasus
![image](https://user-images.githubusercontent.com/63390998/114378456-eba66780-9bb1-11eb-8b2c-af222e3bf685.png)

Pada lokasi sebaran tidak ada data probable
![image](https://user-images.githubusercontent.com/63390998/114378526-0082fb00-9bb2-11eb-9b93-eca11ec8596b.png)

**Comment by firmanJS** [comment]
yang ini kayanya udah bener shin @shintadewiaw aku cek result api nya udah bener
di frontend ada filter kayanya waktu nampilin datanya, soalnya pas di cek datanya ada beberapa data yang bukan wilayah bogor tapi di input oleh dinke bogor atau faskes bogor

**Comment by shintadewiaw** [comment]
mas @Arif9878 di FEnya di filter by apa mas?

**Comment by Arif9878** [comment]
@shintadewiaw filter by kode_kab sin

**Comment by firmanJS** [comment]
@shintadewiaw udah bener ya datanya aku perbarui
