### ISSUE TITLE
[Export Kasus] Penambahan kolom catatan tambahan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#93]
## Acceptance Criteria :

- [x] Tambahan kolom catatan tambahan
- [x] Posisi sebelum author
- [x] Jika tidak ada isinya, kosongkan

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
mas @firmanJS misal di catatannya ada enter kebawah gitu di excelnya bisa ikutan ke enter ga sih?
![image](https://user-images.githubusercontent.com/63390998/81533272-1c719180-9390-11ea-8e36-4246ccf69981.png)

**Comment by firmanJS** [comment]
@shintadewiaw ga bisa kayanya
