### ISSUE TITLE
Membuat fungsi pengiriman data hasil lab ke draft

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#946]
## Flow System
![Proses Bisnis Pendaftaran, SIM Lab, Pelaporan-Page-6](https://user-images.githubusercontent.com/11548871/115659757-3ae45900-a365-11eb-8d3d-984793074803.jpg)

## Acceptance Criteria
- [x] Data hasil lab terkirim ke tab menu draft berdasarkan kewilayahan faskes
- [ ] Jika data hasil lab tidak memungkinkan untuk menentukan pengiriman data hasil lab kepada surveilans, maka data dikirimkan kepada dinkes kota/kab bersangkutan sesuai alamat domisili data hasil positif

**Comment by shintadewiaw** [comment]
**Report Pengetesan:** https://app.qase.io/public/report/4b77843ff0f967e0ec03fef09b304e29f0d03201
