### ISSUE TITLE
Membuat fungsi update data hasil lab ke form pemeriksaan penunjang

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#947]
## Flow System
![Proses Bisnis Pendaftaran, SIM Lab, Pelaporan-Page-6](https://user-images.githubusercontent.com/11548871/115659757-3ae45900-a365-11eb-8d3d-984793074803.jpg)

## Acceptance Criteria
- [ ] Data hasil lab terkirim ke form pemeriksaan penunjan berdasarkan kewilayahan faskes

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 ada feedback untuk yang tempat pemeriksaan di hardcode jadi LAB JABAR yaa
![image](https://user-images.githubusercontent.com/63390998/117411507-d4069880-af3d-11eb-9e90-552b0102bb3e.png)

**Comment by sandisunandar99** [comment]
> mas @sandisunandar99 ada feedback untuk yang tempat pemeriksaan di hardcode jadi LAB JABAR yaa
> ![image](https://user-images.githubusercontent.com/63390998/117411507-d4069880-af3d-11eb-9e90-552b0102bb3e.png)
> 

Iya sin udh jdi lab jabar pas ketika updtenya

**Comment by shintadewiaw** [comment]
@sandisunandar99 tadi waktu di cek (jam 1) belum ada perubahan mas, apa baru aja diubahnya?

**Comment by sandisunandar99** [comment]
> @sandisunandar99 tadi waktu di cek (jam 1) belum ada perubahan mas, apa baru aja diubahnya?

![Screenshot_20210507-160159_GitHub.jpg](https://user-images.githubusercontent.com/6767399/117426112-b6412f80-af4d-11eb-981d-e6f069670b48.jpg)

Udh sin tuh wkwk

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 ini masih null hari ini dicek
![image](https://user-images.githubusercontent.com/63390998/118432770-a2db5480-b703-11eb-9185-7a775e0ce65f.png)

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 udah merge belum ni? masih belum ada perubahan mas
![image](https://user-images.githubusercontent.com/63390998/118934707-da046c80-b974-11eb-9aaa-7f552fc52acc.png)

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 belum berubah juga ni :(
![image](https://user-images.githubusercontent.com/63390998/119077375-5e5efa00-ba1e-11eb-9ea0-c79e1f90c422.png)
