### ISSUE TITLE
Membuat fitur history export data

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#950]
## User Story
- Sebagai user saya ingin melihat riwayat data yang saya pernah export sehingga saya bisa mengetahui list export data yang pernah saya lakukan

## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=7516%3A28127&viewport=430%2C58%2C0.021072477102279663&scaling=min-zoom&page-id=3085%3A0

## Acceptance Criteria

- [x] User bisa melihat data history expor data
- [x] User bisa mencari data berdasarkan nama file
- [x] User bisa memfilter data berdasarkan tanggal unduh dan status
- [x] User bisa mendownload ulang file
- [x] User bisa melihat riwayat email mana saja yang pernah dikirimkan hasil export data
- [x] Urutan data yang ditampilkan berdasarkan tanggal unduh
- [x] Terdapat pagination, limit data 30

**Comment by erlangganugraha** [comment]
button filter belum clickable diprototypenya @rafidrbbn

**Comment by firmanJS** [comment]
value filter status `Progress` `Sent` `Error` @Arif9878 dokumentasi ada dipostman

**Comment by shintadewiaw** [comment]
mas @firmanJS  ada bug di pagination 
![image](https://user-images.githubusercontent.com/63390998/116852889-5aaa3580-ac1f-11eb-83d4-ae09ed278265.png)

**Comment by firmanJS** [comment]
apanya yang bug shin @shintadewiaw

**Comment by shintadewiaw** [comment]
### Feedback 30/04 @firmanJS 

- [ ] Ketika klik resend sebaiknya progress bar mengulang dari 10% dan status diubah menjadi "diproses"
![image](https://user-images.githubusercontent.com/63390998/116979368-1c7c4700-acef-11eb-8565-3b882c8dd62f.png)

- [ ] Mas di emailnya redaksinya ada yang typo, misalkan redaksinya diubah berdasarkan data yang diunduh bisa ga mas?
Misal: Berikut merupakan Data Informasi Klinis Aplikasi Pelaporan Kasus Pikobar / Berikut merupakan Data Pasien Aplikasi Pelaporan Kasus Pikobar
![image](https://user-images.githubusercontent.com/63390998/116980155-15a20400-acf0-11eb-9cf1-226d5a75cd2c.png)

**Comment by firmanJS** [comment]
kalo untuk resend gak perlu progress bar karena ini tidak ada schema antrian, jadi jika telat itu by default karena server aws email nya suka agak telat

**Comment by shintadewiaw** [comment]
@firmanJS  kenapa angkanya jadi NAN% ya mas?

**Comment by firmanJS** [comment]
> @firmanJS kenapa angkanya jadi NAN% ya mas?

kaya di frontend nya sih, karena jika resend email harusnya gak masuli list karena itu bukan antrian @shintadewiaw
