### ISSUE TITLE
API Improvement export data pasien

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#951]
## Acceptance Criteria
- [ ] Membuat fungsi generate export data pasien skema antrian
- [ ] Terdapat validasi email jika sudah digunakan oleh akun lain
- [ ] Format penamaan file export adalah : Data Pasien Akun Login - Tanggal export (contoh : Data Pasien Dinkes Kota Bandung - 22-04-2021)

**Comment by shintadewiaw** [comment]
**Feedback 07 Mei 2021 @firmanJS **

- [x] Format penamaan file export belum dibedakan antara informasi klinis dengan data pasien

- [x] Redaksi nama file tidak sesuai dengan kewilayahannya  (Login Faskes)
![image](https://user-images.githubusercontent.com/63390998/117411996-6b6beb80-af3e-11eb-8a2b-c41afca67883.png)

- [x] Kirim data export tidak masuk pada email (Login Faskes)
![image](https://user-images.githubusercontent.com/63390998/117412140-9fdfa780-af3e-11eb-95ea-f9620a03ecda.png)

- [ ] Kirim data export tidak masuk pada email (Login Dinkes)
![image](https://user-images.githubusercontent.com/63390998/117412546-1aa8c280-af3f-11eb-895f-379bed3a5746.png)

- [ ] Redaksi nama file tidak sesuai dengan kewilayahannya (Login Dinkes)
![image](https://user-images.githubusercontent.com/63390998/117412418-fa790380-af3e-11eb-8bbb-c036714992ea.png)
