### ISSUE TITLE
API Improvement export riwayat klinis

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#952]
## Acceptance Criteria
- [x] Membuat fungsi generate export riwayat klinis skema antrian
- [x] Terdapat validasi email jika sudah digunakan oleh akun lain
- [x] Format penamaan file export adalah : Data Riwayat Klinis Akun Login - Tanggal export (contoh : Data Riwayat Klinis Dinkes Kota Bandung - 22-04-2021)

**Comment by shintadewiaw** [comment]
mas nama filenya typo
![image](https://user-images.githubusercontent.com/63390998/116641690-726f8880-a997-11eb-9334-8f469a5bc4e5.png)

**Comment by shintadewiaw** [comment]
mas @firmanJS nama riwayatnya typo, terus yang aku blok kuning di belakang itu bisa dihilangkan ga mas?
![image](https://user-images.githubusercontent.com/63390998/116644027-823d9b80-a99c-11eb-97f2-bcb4f0309a12.png)

**Comment by firmanJS** [comment]
siap meluncur @shintadewiaw gak bisa kayanya itu sebagai penanda soalnya shin buat nanti resend file biar ga ketuker

**Comment by shintadewiaw** [comment]
mas sama ini rt/rw kalau null gausah ditampilkan yaa
![image](https://user-images.githubusercontent.com/63390998/116644188-eb251380-a99c-11eb-95bf-1572ff390f6d.png)

**Comment by shintadewiaw** [comment]
**### Feedback 07 Mei 2020**

- [ ] Format penamaan file export belum dibedakan antara informasi klinis dengan data pasien

- [ ] Redaksi nama file tidak sesuai dengan kewilayahannya  (Login Faskes)
![image](https://user-images.githubusercontent.com/63390998/117411996-6b6beb80-af3e-11eb-8a2b-c41afca67883.png)

- [ ] Kirim data export tidak masuk pada email (Login Faskes)
![image](https://user-images.githubusercontent.com/63390998/117412140-9fdfa780-af3e-11eb-95ea-f9620a03ecda.png)

- [ ] Kirim data export tidak masuk pada email (Login Dinkes)
![image](https://user-images.githubusercontent.com/63390998/117412546-1aa8c280-af3f-11eb-895f-379bed3a5746.png)

- [ ] Redaksi nama file tidak sesuai dengan kewilayahannya (Login Dinkes)
![image](https://user-images.githubusercontent.com/63390998/117412418-fa790380-af3e-11eb-8bbb-c036714992ea.png)
