### ISSUE TITLE
Development notifikasi hasil lab positif ke surveilans/faskes

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#954]
## User Flow
1. Surveilans menerima notifikasi data hasil lab positif
2. Klik notifikasi, maka direct ke page **Laporan Labkes**
3. Klik salah satu data hasil lab positif untuk menginput data PE atau jika sudah terdata dilist kasus maka mengupdate data PE
4. Ajukan data PE kepada dinkes kota/kab
5. Verifikasi data PE oleh dinkes kota/kab
6. Data terverifikasi dan masuk ke **List Kasus**

## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?page-id=4986%3A12606&node-id=6534%3A25273&viewport=-800%2C-49266%2C0.8620098829269409&scaling=scale-down-width
## Acceptance Criteria
- [ ] Surveilans bisa menerima notifikasi informasi **hasil lab positif** yang dikirimkan dari sistem MAN LAB
- [ ] Surveilans menerima data hasil positif berdasarkan tanggung jawab kewilayahannya (berdasarkan alamat pasien)
- [ ] Jika data hasil lab tidak memungkinkan untuk penentuan pengiriman data hasil lab kepada surveilans, maka data dikirimkan kepada dinkes kota/kab bersangkutan sesuai alamat domisili data hasil positif
- [ ] Format notifikasi data hasil lab berbentuk akumulasi angka

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/116494168-7681a480-a8ca-11eb-847b-96576d5aca5a.png)

BTW ini ga salah bikin desain/ redaksi ya? kan survilance itu faskes bukan dinkes. sama itu kata2 20 hasil positif dari puskesmas  anu itu mungkin bisa di perbaiki juga soalnya kan yang nerima faskes dan data nya ini dikirim dari aplikasi labkes.
ini takutnyanya nnti jadi salah persepsi kedepannya mungkin bisa di rubah dlu ya

@rafidrbbn @erlangganugraha @shintadewiaw

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/120423742-387a1380-c395-11eb-9b4f-4ac2b8fd9214.png)

unutk yang notif @shintadewiaw @erlangganugraha

**Comment by shintadewiaw** [comment]
Data notifikasi belum masuk pada pelaporan (data telah terkirim dari simlab namun belum masuk pada pelaporan, perlu pengecekan dari pelaporan) 
cc: @sandisunandar99

**Comment by sandisunandar99** [comment]
> Data notifikasi belum masuk pada pelaporan (data telah terkirim dari simlab namun belum masuk pada pelaporan, perlu pengecekan dari pelaporan)
> cc: @sandisunandar99

okay sin ,,, lagi di cek nih,, ga tau kenapa ,, wkwkw aneh kemarin mah bisa

**Comment by sandisunandar99** [comment]
> Data notifikasi belum masuk pada pelaporan (data telah terkirim dari simlab namun belum masuk pada pelaporan, perlu pengecekan dari pelaporan)
> cc: @sandisunandar99

![image](https://user-images.githubusercontent.com/6767399/121664304-8ac3de80-cad1-11eb-8141-1c8fe1971ee8.png)

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 kok belum masuk juga ya notifnya, kita concall bertiga aja yu sama mas firman coding?

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/121840930-81bc5280-cd07-11eb-98bb-bd795771f57b.png)
