### ISSUE TITLE
[Peta Penyebaran] Revisi & penambahan filter

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-backend#97]
## Desain
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=342%3A0

## Acceptance Criteria
- [ ]  Terdapat fitur filter berdasarkan Kecamatan dan kelurahan/desa

**Comment by ReksaMohammad** [comment]
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=342%3A0

**Comment by alifianif** [comment]
- **Kota Banjar**
Data di kota banjar positif aktifnya ada 7, tapi yang muncul di peta hanya 3
![image](https://user-images.githubusercontent.com/17422311/82295242-aa292e80-99d9-11ea-8d7c-bd288665aad1.png)
![image](https://user-images.githubusercontent.com/17422311/82295296-bf9e5880-99d9-11ea-9c11-f2875b860a9f.png)
@rendiriz

**Comment by shintadewiaw** [comment]
mas @rendiriz ini saya filter by list kasus di kecamatan Regol kelurahan Ancol ga ada datanya
tapi di petanya ada 2 mas, beberapa case sama kaya gitu ga sesuai datanya

![image](https://user-images.githubusercontent.com/63390998/82295684-53702480-99da-11ea-9ab4-83f0cae196eb.png)

![image](https://user-images.githubusercontent.com/63390998/82295760-6f73c600-99da-11ea-9c07-b1eca7d3175e.png)

**Comment by firmanJS** [comment]
@shintadewiaw aku bantu jawab ini karena api nya dari tim data di stagging dan production data nya sama pake yang production jadi pasti akan ada perbedaan data.

**Comment by alifianif** [comment]
@firmanJS Jadi maksudnya data peta yang di staging tuh pake data dari production gitu ya? bukan data dari staging?

**Comment by firmanJS** [comment]
@alifianif iya begitu

**Comment by shintadewiaw** [comment]
tapi data yang production juga salah mas @firmanJS 

![image](https://user-images.githubusercontent.com/63390998/82300145-a0ef9000-99e0-11ea-8ff0-efde943eb941.png)

![image](https://user-images.githubusercontent.com/63390998/82300480-1ce9d800-99e1-11ea-8cdf-5f652220c40e.png)

**Comment by firmanJS** [comment]
@shintadewiaw yang di hitung positif aktif rumus nya itu ada yang sembuh berarti ga keitung :running:

**Comment by shintadewiaw** [comment]
@firmanJS eh iyaya, monmaap baru ngeh yang dihitung cuma positif aktif

nah bagaimana dengan ini mas?wkwkw dinkes banjar ni

![image](https://user-images.githubusercontent.com/63390998/82301320-435c4300-99e2-11ea-830c-3e8bc2925a76.png)

![image](https://user-images.githubusercontent.com/63390998/82301654-c087b800-99e2-11ea-9493-b6ba0ceafaba.png)

**Comment by firmanJS** [comment]
@shintadewiaw itu masih ada yang proses statusnya coba cek riwayat nya kayanya gak ke update masuk list bug tuh :laughing: wkwk

**Comment by alifianif** [comment]
Iyaya itu masuk bug list tuh. Tapi btw yang prosesnya cuma 1 mas sementara di peta ada 3 @firmanJS

**Comment by firmanJS** [comment]
@alifianif iya gak ke update itu di list nya coba cek di map ada id covid nya terus cari di list dan klik update riwayat liat riwayatnya
